% Generated Prolog reader for section header.
%
% This file is GENERATED by prolog_reader_generator.pl from the
% BPD Prolog IR. Do not edit by hand; re-run the generator to
% regenerate.
%
% Pulls in byte_readers.pl from the same directory (deployment
% copy of ir/include/byte_readers.pl — emitted alongside this
% file by emit_byte_readers_to_file/1).
%
% Generated by the BPD Prolog parser-generator
% (ir/include/prolog_reader_generator.pl).

:- consult(byte_readers).

% --- Per-field readers ---

read_field(header, magic, Bytes, Value) :-
    read_bytes(Bytes, 0, 4, Value).

read_field(header, version, Bytes, Value) :-
    read_u32_le(Bytes, 4, Value).

read_field(header, tensor_count, Bytes, Value) :-
    read_u64_le(Bytes, 8, Value).

read_field(header, metadata_kv_count, Bytes, Value) :-
    read_u64_le(Bytes, 16, Value).


% --- Section reader ---

read_section(header, Bytes, Pairs) :-
    read_field(header, magic, Bytes, V0),
    read_field(header, version, Bytes, V1),
    read_field(header, tensor_count, Bytes, V2),
    read_field(header, metadata_kv_count, Bytes, V3),
    Pairs=[field(magic, V0), field(version, V1), field(tensor_count, V2), field(metadata_kv_count, V3)].

