% Generated Prolog reader for GGUF v3 — all four sections.
%
% This file is GENERATED by prolog_reader_generator.pl from the
% BPD Prolog IR. Do not edit by hand; re-run the generator to
% regenerate.
%
% Sections implemented:
%   header              — 24-byte fixed header
%   metadata_kv_pair    — variable-width KV record (all 13 value types)
%   metadata_array      — nested array sub-record (type 9)
%   tensor_info_record  — variable-width tensor descriptor
%   tensor_data_section — opaque blob, 32-byte aligned start
%
% Pulls in byte_readers.pl from the same directory (deployment
% copy of ir/include/byte_readers.pl — emitted alongside this
% file by emit_byte_readers_to_file/1).
%
% Generated by the BPD Prolog parser-generator
% (ir/include/prolog_reader_generator.pl).

:- consult(byte_readers).

:- discontiguous read_section_at/5.


% ═══════════════════════════════════════════════════════════════════
% SECTION: header (24 bytes, fixed-width)
% ═══════════════════════════════════════════════════════════════════

% --- Per-field readers ---

read_field(header, magic, Bytes, Value) :-
    read_bytes(Bytes, 0, 4, Value).

read_field(header, version, Bytes, Value) :-
    read_u32_le(Bytes, 4, Value).

read_field(header, tensor_count, Bytes, Value) :-
    read_u64_le(Bytes, 8, Value).

read_field(header, metadata_kv_count, Bytes, Value) :-
    read_u64_le(Bytes, 16, Value).


% --- Section reader ---

read_section(header, Bytes, Pairs) :-
    read_field(header, magic, Bytes, V0),
    read_field(header, version, Bytes, V1),
    read_field(header, tensor_count, Bytes, V2),
    read_field(header, metadata_kv_count, Bytes, V3),
    Pairs = [field(magic, V0), field(version, V1),
             field(tensor_count, V2), field(metadata_kv_count, V3)].


% --- Convenience: read header at absolute byte offset ---
%
% read_section_at(+Section, +Bytes, +Offset, -Pairs, -Consumed)
%
% Slices Bytes from Offset, calls read_section/3, and returns the
% number of bytes consumed (fixed for header, computed for variable
% sections).

read_section_at(header, Bytes, Offset, Pairs, 24) :-
    bytes_slice_from(Bytes, Offset, Slice),
    read_section(header, Slice, Pairs).


% ═══════════════════════════════════════════════════════════════════
% SECTION: metadata_kv_pair (variable-width)
%
% Layout per GGUF v3 spec:
%   [u64 key_len] [key_bytes × key_len]
%   [u32 value_type]
%   [value — layout depends on value_type]
%
% Value types (0–12):
%   0  u8      1 byte
%   1  i8      1 byte
%   2  u16     2 bytes
%   3  i16     2 bytes
%   4  u32     4 bytes
%   5  i32     4 bytes
%   6  f32     4 bytes
%   7  bool    1 byte (0 or 1)
%   8  string  [u64 len] [bytes × len]
%   9  array   [u32 elem_type] [u64 count] [count × elem]
%  10  u64     8 bytes
%  11  i64     8 bytes
%  12  f64     8 bytes
% ═══════════════════════════════════════════════════════════════════

%% read_section_at(metadata_kv_pair, +Bytes, +Offset, -Pairs, -Consumed)
%%
%% Parses one metadata KV pair starting at Offset within Bytes.
%% Returns Pairs = [field(key,Key), field(value_type,VT), field(value,V)]
%% and Consumed = total bytes consumed by this record.

read_section_at(metadata_kv_pair, Bytes, Offset, Pairs, Consumed) :-
    %% Key: u64 length-prefixed string
    read_u64_le(Bytes, Offset, KeyLen),
    KeyBytesOffset is Offset + 8,
    bytes_slice(Bytes, KeyBytesOffset, KeyLen, KeySlice),
    (string(KeySlice) -> atom_string(Key, KeySlice) ; atom_codes(Key, KeySlice)),
    KeyConsumed is 8 + KeyLen,

    %% value_type: u32
    VTOffset is Offset + KeyConsumed,
    read_u32_le(Bytes, VTOffset, VT),
    VTConsumed is KeyConsumed + 4,

    %% value: dispatch on VT
    ValueOffset is Offset + VTConsumed,
    read_kv_value(VT, Bytes, ValueOffset, Value, ValueConsumed),

    Consumed is VTConsumed + ValueConsumed,
    Pairs = [field(key, Key), field(value_type, VT), field(value, Value)].


%% read_kv_value(+TypeCode, +Bytes, +Offset, -Value, -Consumed)
%%
%% Dispatches on the GGUF metadata value type code (0–12) and reads
%% the value starting at Offset. Returns the decoded Value and the
%% number of bytes consumed.

read_kv_value(0, Bytes, Offset, Value, 1) :-
    read_u8(Bytes, Offset, Value).

read_kv_value(1, Bytes, Offset, Value, 1) :-
    read_i8(Bytes, Offset, Value).

read_kv_value(2, Bytes, Offset, Value, 2) :-
    read_u16_le(Bytes, Offset, Value).

read_kv_value(3, Bytes, Offset, Value, 2) :-
    read_i16_le(Bytes, Offset, Value).

read_kv_value(4, Bytes, Offset, Value, 4) :-
    read_u32_le(Bytes, Offset, Value).

read_kv_value(5, Bytes, Offset, Value, 4) :-
    read_i32_le(Bytes, Offset, Value).

read_kv_value(6, Bytes, Offset, Value, 4) :-
    read_f32_le(Bytes, Offset, Value).

read_kv_value(7, Bytes, Offset, Value, 1) :-
    read_u8(Bytes, Offset, Raw),
    (Raw =:= 0 -> Value = false ; Value = true).

read_kv_value(8, Bytes, Offset, Value, Consumed) :-
    %% String: u64 length + bytes
    read_u64_le(Bytes, Offset, StrLen),
    StrOffset is Offset + 8,
    bytes_slice(Bytes, StrOffset, StrLen, StrSlice),
    (string(StrSlice) -> Value = StrSlice ; atom_codes(Value, StrSlice)),
    Consumed is 8 + StrLen.

read_kv_value(9, Bytes, Offset, array(ElemType, Count, Elements), Consumed) :-
    %% Array: u32 elem_type + u64 count + count × elem
    read_u32_le(Bytes, Offset, ElemType),
    read_u64_le(Bytes, Offset + 4, Count),
    ElemsOffset is Offset + 12,
    read_array_elements(ElemType, Count, Bytes, ElemsOffset, Elements, ElemsConsumed),
    Consumed is 12 + ElemsConsumed.

read_kv_value(10, Bytes, Offset, Value, 8) :-
    read_u64_le(Bytes, Offset, Value).

read_kv_value(11, Bytes, Offset, Value, 8) :-
    read_i64_le(Bytes, Offset, Value).

read_kv_value(12, Bytes, Offset, Value, 8) :-
    read_f64_le(Bytes, Offset, Value).


%% read_array_elements(+ElemType, +Count, +Bytes, +Offset, -Elements, -Consumed)
%%
%% Reads Count elements of ElemType starting at Offset.
%% Returns Elements as a list and the total bytes consumed.

read_array_elements(_ElemType, 0, _Bytes, _Offset, [], 0) :- !.

read_array_elements(ElemType, Count, Bytes, Offset, [Elem | Rest], Consumed) :-
    Count > 0,
    read_kv_value(ElemType, Bytes, Offset, Elem, ElemConsumed),
    NextOffset is Offset + ElemConsumed,
    Count1 is Count - 1,
    read_array_elements(ElemType, Count1, Bytes, NextOffset, Rest, RestConsumed),
    Consumed is ElemConsumed + RestConsumed.


% ═══════════════════════════════════════════════════════════════════
% SECTION: tensor_info_record (variable-width)
%
% Layout per GGUF v3 spec:
%   [u64 name_len] [name_bytes × name_len]
%   [u32 n_dimensions]
%   [u64 × n_dimensions]   — shape dimensions
%   [u32 type]             — ggml_type code
%   [u64 offset]           — relative to tensor_data_section start
% ═══════════════════════════════════════════════════════════════════

%% read_section_at(tensor_info_record, +Bytes, +Offset, -Pairs, -Consumed)

read_section_at(tensor_info_record, Bytes, Offset, Pairs, Consumed) :-
    %% Name: u64 length-prefixed string
    read_u64_le(Bytes, Offset, NameLen),
    NameBytesOffset is Offset + 8,
    bytes_slice(Bytes, NameBytesOffset, NameLen, NameSlice),
    (string(NameSlice) -> atom_string(Name, NameSlice) ; atom_codes(Name, NameSlice)),
    NameConsumed is 8 + NameLen,

    %% n_dimensions: u32
    NDimsOffset is Offset + NameConsumed,
    read_u32_le(Bytes, NDimsOffset, NDims),
    NDimsConsumed is NameConsumed + 4,

    %% dimensions: NDims × u64
    DimsOffset is Offset + NDimsConsumed,
    read_u64_array(NDims, Bytes, DimsOffset, Dims),
    DimsConsumed is NDimsConsumed + NDims * 8,

    %% type: u32
    TypeOffset is Offset + DimsConsumed,
    read_u32_le(Bytes, TypeOffset, Type),
    TypeConsumed is DimsConsumed + 4,

    %% offset: u64 (relative to tensor_data_section start)
    TOffsetOffset is Offset + TypeConsumed,
    read_u64_le(Bytes, TOffsetOffset, TensorOffset),

    Consumed is TypeConsumed + 8,
    Pairs = [field(name, Name), field(n_dimensions, NDims),
             field(dimensions, Dims), field(type, Type),
             field(offset, TensorOffset)].


%% read_u64_array(+Count, +Bytes, +Offset, -Values)
%%
%% Reads Count consecutive u64 LE values starting at Offset.

read_u64_array(0, _Bytes, _Offset, []) :- !.
read_u64_array(N, Bytes, Offset, [V | Rest]) :-
    N > 0,
    read_u64_le(Bytes, Offset, V),
    Next is Offset + 8,
    N1 is N - 1,
    read_u64_array(N1, Bytes, Next, Rest).


% ═══════════════════════════════════════════════════════════════════
% SECTION: tensor_data_section
%
% The tensor data section starts at the next 32-byte alignment
% boundary after the end of the tensor_info_section. Its absolute
% start offset is computed by the caller after parsing all tensor
% info records; individual tensor data is accessed by seeking to
% (tensor_data_start + tensor_info_record.offset).
%
% compute_tensor_data_start(+PostTensorInfoOffset, -AlignedOffset)
% ═══════════════════════════════════════════════════════════════════

%% compute_tensor_data_start(+RawOffset, -AlignedOffset)
%%
%% Rounds RawOffset up to the next 32-byte boundary.
%% Per GGUF v3 spec: alignment = 32 bytes (default; overridable via
%% general.alignment metadata key, but 32 is used here as the default).

compute_tensor_data_start(RawOffset, AlignedOffset) :-
    Alignment = 32,
    Rem is RawOffset mod Alignment,
    (Rem =:= 0
     -> AlignedOffset = RawOffset
     ;  AlignedOffset is RawOffset + (Alignment - Rem)
    ).


% ═══════════════════════════════════════════════════════════════════
% CONVENIENCE: parse a full GGUF file header + all metadata KVs
%
% parse_gguf_header_and_metadata(+Bytes, -Header, -KVPairs)
%
% Parses the 24-byte header and all metadata_kv_count KV pairs.
% Returns:
%   Header   = [field(magic,_), field(version,_), field(tensor_count,_),
%               field(metadata_kv_count,_)]
%   KVPairs  = list of [field(key,K), field(value_type,VT), field(value,V)]
% ═══════════════════════════════════════════════════════════════════

parse_gguf_header_and_metadata(Bytes, Header, KVPairs) :-
    read_section_at(header, Bytes, 0, Header, 24),
    member(field(metadata_kv_count, KVCount), Header),
    parse_kv_pairs(KVCount, Bytes, 24, KVPairs, _).

parse_kv_pairs(0, _Bytes, Offset, [], Offset) :- !.
parse_kv_pairs(N, Bytes, Offset, [Pairs | Rest], FinalOffset) :-
    N > 0,
    read_section_at(metadata_kv_pair, Bytes, Offset, Pairs, Consumed),
    NextOffset is Offset + Consumed,
    N1 is N - 1,
    parse_kv_pairs(N1, Bytes, NextOffset, Rest, FinalOffset).


% ═══════════════════════════════════════════════════════════════════
% CONVENIENCE: parse all tensor info records
%
% parse_tensor_info_records(+Bytes, +StartOffset, +Count,
%                           -Records, -EndOffset)
%
% Parses Count tensor_info_records starting at StartOffset.
% Returns Records as a list of Pairs lists and EndOffset after last.
% ═══════════════════════════════════════════════════════════════════

parse_tensor_info_records(0, _Bytes, Offset, [], Offset) :- !.
parse_tensor_info_records(N, Bytes, Offset, [Pairs | Rest], FinalOffset) :-
    N > 0,
    read_section_at(tensor_info_record, Bytes, Offset, Pairs, Consumed),
    NextOffset is Offset + Consumed,
    N1 is N - 1,
    parse_tensor_info_records(N1, Bytes, NextOffset, Rest, FinalOffset).
