#!/usr/bin/env python3
"""congruence_dashboard.py — real-time 0-ULP congruence dashboard for LlamaTov.

Serves a two-axis matrix of per-kernel bit-identity:
  RUNTIME axis  — does the kernel COMPUTE bit-identically to the oracle?
                  (Track A, bit_identical_universal.py)
  MIGRATION axis — does the kernel EMIT byte-identically swipl → swilgt?
                   (Track B, mavhir's emit_diff_matrix.py)

Reads congruence_status.json (produced by Track A -> A2 model, extended per
dashboard/CONGRUENCE_SCHEMA.md). Refreshes on each page load; JSON is
regenerated by gate runs (C3 real-time).

FORWARD-COMPAT RENDER (mavhir 2026-09-02, per Iyun's (b) call):
Renders the versioned schema (CONGRUENCE_SCHEMA.md at dca5d9e / 4d23761)
defensively — every new field uses .get(...) with a graceful "-" fallback,
so this app works with:
  * Old JSON (just `passed` + `kernel`/`shape`/`status`/`max_ulp`/`bit_identical`/`backend`)
  * New JSON with population fields (total_floats/diverged_count/oracle/dtype/device)
  * New JSON with verdict-honest counts (bit_identical/within_tolerance/failed)
  * New JSON with migration axis (migration_source_identical/swipl_sha/swilgt_sha/migration_unit)
  * Any mixture of the above during migration transitions.

If a field is missing, its cell renders "-" and the row is not counted as
present for that axis. THE VERDICT-CLASS RULE is honored: `passed` is never
emitted or consumed as green; only `bit_identical` count is the true 0-ULP
headline. THE EMPTY-POPULATION GUARD is honored: `total_floats` is surfaced;
rows below UNDER_EXERCISED_THRESHOLD are dimmed + marked with a warning.

Usage: python3 congruence_dashboard.py [--port 8477] [--status congruence_status.json]
"""
import json, os, argparse, html, datetime, re
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

STATUS_FILE = "congruence_status.json"

# Under-exercised threshold from CONGRUENCE_SCHEMA.md guidance ("< 1000 floats").
# Per schema doc: dashboard MAY dim/flag rows below this; boolean per-row, not
# a hard fail. If Mavdil's implementation surfaces a different threshold in
# the JSON, this local default can be overridden by json field `under_exercised_threshold`.
UNDER_EXERCISED_THRESHOLD = 1000

# Staleness threshold for the FRESHNESS STAMP (Iyun's proposal from mavchin's
# May-30 dashboard archaeology): if the JSON's `generated` timestamp is older
# than this, mark the freshness widget red so staleness is self-evident on
# the dashboard's own face. Default: 5 minutes for a live matrix. Overridable
# via json top-level `staleness_threshold_seconds` field. See substrate lesson:
# "a dashboard that can't prove its own liveness can silently show stale data
# as if fresh — same class as hollow-green (looks-current, might-not-be)."
STALENESS_THRESHOLD_SECONDS = 300

PAGE = """<!DOCTYPE html><html><head><meta charset="utf-8">
<title>LlamaTov · Bit-Perfect Dispatch</title>
<meta http-equiv="refresh" content="10">
<style>
 body{{background:#0b0e14;color:#c9d1d9;font-family:'JetBrains Mono',ui-monospace,monospace;margin:0;padding:2rem}}
 h1{{color:#e6edf3;font-weight:600;font-size:1.4rem;margin:0 0 .3rem}}
 .sub{{color:#8b949e;margin-bottom:1.5rem;font-size:.85rem}}
 .counts{{display:flex;gap:1.5rem;margin:1rem 0;font-size:.85rem;flex-wrap:wrap}}
 .count{{padding:.4rem .8rem;border:1px solid #21262d;border-radius:6px;background:#161b22}}
 .count b{{color:#e6edf3;font-size:1.05rem;margin-right:.4rem}}
 .count .lbl{{color:#8b949e}}
 .count.ok b{{color:#3fb950}}
 .count.warn b{{color:#d29922}}
 .count.fail b{{color:#f85149}}
 .bar{{height:34px;background:#161b22;border-radius:6px;overflow:hidden;margin:1rem 0;position:relative;border:1px solid #21262d}}
 .fill{{height:100%;background:linear-gradient(90deg,#238636,#2ea043);transition:width .6s}}
 .barlabel{{position:absolute;top:0;left:0;right:0;line-height:34px;text-align:center;font-weight:600;color:#fff;text-shadow:0 1px 2px #000}}
 table{{border-collapse:collapse;width:100%;margin-top:1rem;font-size:.82rem}}
 th{{text-align:left;color:#8b949e;font-weight:500;padding:.4rem .6rem;border-bottom:1px solid #21262d;font-size:.75rem;text-transform:uppercase;letter-spacing:.05em}}
 td{{padding:.35rem .6rem;border-bottom:1px solid #161b22;vertical-align:middle}}
 tr.under-exercised td{{opacity:.55}}
 .ok{{color:#3fb950}} .warn{{color:#d29922}} .fail{{color:#f85149}} .muted{{color:#484f58}}
 .dot{{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:.25rem;vertical-align:middle}}
 .dot.ok{{background:#3fb950}} .dot.warn{{background:#d29922}} .dot.fail{{background:#f85149}} .dot.muted{{background:#484f58}}
 .ulp0{{color:#3fb950;font-weight:600}}
 .num{{text-align:right;font-variant-numeric:tabular-nums}}
 .foot{{margin-top:2rem;color:#484f58;font-size:.75rem}}
 .k{{color:#79c0ff}}
 .oracle{{color:#a5d6ff;font-size:.75rem}}
 .diag{{color:#d29922;font-size:.72rem;font-style:italic}}
 .owner{{color:#8b949e;font-size:.72rem}}
 .under-flag{{color:#d29922;font-size:.7rem;margin-left:.3rem}}
 .fresh-stamp{{display:inline-block;padding:.15rem .5rem;border-radius:4px;font-size:.72rem;font-weight:600;margin-left:.5rem;letter-spacing:.02em}}
 .fresh-stamp.ok{{background:#0f2818;color:#3fb950;border:1px solid #1a3a24}}
 .fresh-stamp.warn{{background:#2b210a;color:#d29922;border:1px solid #3d2f11}}
 .fresh-stamp.fail{{background:#2b1114;color:#f85149;border:1px solid #3f1a1f}}
 .fresh-stamp.muted{{background:#161b22;color:#484f58;border:1px solid #21262d}}
</style></head><body>
<h1>🕯️ LlamaTov · Bit-Perfect Dispatch</h1>
<div class="sub">Two-axis 0-ULP congruence matrix — RUNTIME (compute vs oracle) × MIGRATION (source-preservation swipl→swilgt). Generated {generated} <span class="fresh-stamp {fresh_cls}">{fresh_label}</span> · auto-refresh 10s</div>

<div class="counts">
  {headline_count_html}
  {migration_count_html}
  {fully_count_html}
  {within_count_html}
  {failed_count_html}
  {under_count_html}
</div>

<div class="bar"><div class="fill" style="width:{pct}%"></div><div class="barlabel">{bar_label}</div></div>

<table>
  <thead><tr>
    <th></th>
    <th>Kernel</th>
    <th>Shape</th>
    <th>Runtime</th>
    <th class="num">max ULP</th>
    <th class="num">Floats</th>
    <th>Oracle</th>
    <th>Backend/Dev</th>
    <th>Migration</th>
    <th>Notes</th>
  </tr></thead>
  <tbody>
{rows}
  </tbody>
</table>

<div class="foot">
  {open_count} open cell(s) toward full bit-perfect · LlamaTov / bpd-substrate ·
  schema: dashboard/CONGRUENCE_SCHEMA.md
</div>
</body></html>"""


def _fmt_int(n):
    """Human-readable int formatting: 1234567 -> 1,234,567."""
    if n is None:
        return "-"
    try:
        return f"{int(n):,}"
    except (ValueError, TypeError):
        return "-"


def _parse_iso_utc(s):
    """Parse ISO-8601 UTC (e.g. '2026-09-02T14:42:49Z') as a naive datetime in
    UTC. Returns None on any parse failure — freshness stamp then shows
    '(unknown age)' rather than crashing.
    """
    if not s or not isinstance(s, str):
        return None
    # Normalize 'Z' -> '+00:00' so fromisoformat accepts it (pre-3.11 quirk)
    s2 = s.strip()
    if s2.endswith("Z"):
        s2 = s2[:-1] + "+00:00"
    try:
        dt = datetime.datetime.fromisoformat(s2)
        # If tz-aware, convert to UTC + strip tzinfo for compare against utcnow()
        if dt.tzinfo is not None:
            dt = dt.astimezone(datetime.timezone.utc).replace(tzinfo=None)
        return dt
    except (ValueError, TypeError):
        return None


def _freshness(generated_str, threshold_seconds):
    """Compute the freshness stamp for the FRESHNESS STAMP widget.

    Iyun's May-30-recovered pattern via mavchin's archaeology: the dashboard
    must prove its own liveness on its own face. A dashboard that renders a
    stale JSON as if fresh is the same class of failure as the hollow-green
    (looks-current, might-not-be).

    Returns (age_label, css_class):
        age_label: "12s ago", "3m ago", "2h 15m ago", or "(unknown age)"
        css_class: "ok" (< threshold), "warn" (< 3*threshold), "fail" (older)
                   or "muted" if we can't parse the timestamp
    """
    dt = _parse_iso_utc(generated_str)
    if dt is None:
        return "(unknown age)", "muted"
    # utcnow() is deprecated in Python 3.12+; use tz-aware now() then strip
    # for compare with our naive-UTC parsed dt. Backward-compat + no warning.
    now = datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None)
    delta = now - dt
    seconds = int(delta.total_seconds())
    if seconds < 0:
        # Future timestamp — clock skew or bad data. Show but don't panic.
        return "(from the future, %ds skew)" % (-seconds), "warn"
    if seconds < 60:
        label = "%ds ago" % seconds
    elif seconds < 3600:
        label = "%dm %ds ago" % (seconds // 60, seconds % 60)
    elif seconds < 86400:
        label = "%dh %dm ago" % (seconds // 3600, (seconds % 3600) // 60)
    else:
        label = "%dd %dh ago" % (seconds // 86400, (seconds % 86400) // 3600)
    if seconds <= threshold_seconds:
        cls = "ok"
    elif seconds <= threshold_seconds * 3:
        cls = "warn"
    else:
        cls = "fail"
    return label, cls


def _runtime_verdict(k):
    """Classify a row's RUNTIME axis into (css_class, dot_class, label).

    Honors THE VERDICT-CLASS RULE: only BIT_IDENTICAL is green. PASS_* classes
    are warn (not counted-green). FAIL is fail. Missing/unknown is muted.
    """
    status = k.get("status", "")
    bi = k.get("bit_identical", False)
    if status == "BIT_IDENTICAL" or (bi is True and status == ""):
        return "ok", "ok", status or "BIT_IDENTICAL"
    if status.startswith("PASS"):
        return "warn", "warn", status
    if status == "FAIL" or status.startswith("FAIL"):
        return "fail", "fail", status
    if not status:
        return "muted", "muted", "-"
    # Unknown status class — surface it as warn to catch our attention
    return "warn", "warn", status


def _migration_verdict(k):
    """Classify a row's MIGRATION axis. Returns (css_class, dot_class, label).

    Field is `migration_source_identical` (bool). Missing = axis-not-populated-yet
    (renders as muted "-", not a fail). True = byte-identical swipl→swilgt.
    False = source diverged.
    """
    if "migration_source_identical" not in k:
        return "muted", "muted", "-"
    if k["migration_source_identical"] is True:
        return "ok", "ok", "byte-identical"
    if k["migration_source_identical"] is False:
        return "fail", "fail", "DIVERGED"
    return "muted", "muted", "-"


def _under_exercised(k, threshold):
    """Boolean: is this row under the population threshold? Missing total_floats
    = we CAN'T tell, so we don't flag (render but don't dim)."""
    tf = k.get("total_floats")
    if tf is None:
        return False
    try:
        return int(tf) < threshold
    except (ValueError, TypeError):
        return False


def _count_html(css, label, value):
    return (
        '<div class="count %s"><b>%s</b><span class="lbl">%s</span></div>'
        % (css, html.escape(str(value)), html.escape(label))
    )


def render():
    try:
        data = json.load(open(STATUS_FILE))
    except Exception as e:
        return (
            "<html><body style='background:#0b0e14;color:#f85149;font-family:monospace;padding:2rem'>"
            "No congruence data yet: %s</body></html>"
        ) % html.escape(str(e))

    # THE VERDICT-CLASS RULE: bit_identical is the true 0-ULP count. The
    # deprecated `passed` field CONFLATED bit_identical with within_tolerance
    # (the whole point of the rule was to abolish that conflation). So the
    # fallback path must NOT silently substitute passed's value for
    # bit_identical — that would preserve the deprecated semantics under the
    # new name (Mavdil's catch, 2026-09-02: "a compatibility path is where
    # deprecated semantics survives — the name changed, the number didn't").
    #
    # Instead: if `bit_identical` is absent but `passed` is present, we mark
    # the count as unverified-legacy (bit_identical_legacy_conflated=True) so
    # the render dims it + shows an asterisk + a tooltip explaining. The
    # only fully-honest degradation is showing "-" for a legacy JSON that
    # can't distinguish 0-ULP from within-tolerance — but that loses the
    # panel entirely. Splitting the difference: display the number with an
    # explicit unverified marker so a reader knows THIS COUNT IS FROM THE
    # DEPRECATED CONFLATED FIELD, not the honest bit-identical field.
    total = data.get("total", 0)
    if "bit_identical" in data:
        bit_identical = data["bit_identical"]
        bit_identical_from_legacy = False
    elif "passed" in data:
        bit_identical = data["passed"]
        bit_identical_from_legacy = True
    else:
        bit_identical = 0
        bit_identical_from_legacy = False
    within_tolerance = data.get("within_tolerance")  # may be None on old JSON
    failed = data.get("failed")

    threshold = data.get("under_exercised_threshold", UNDER_EXERCISED_THRESHOLD)

    # Migration axis top-level counts (both from JSON if present, else derived)
    migration_identical = data.get("migration_identical")
    fully_bit_perfect = data.get("fully_bit_perfect")

    rows_html = []
    kernels = data.get("kernels", [])

    # Derive counts from per-row if top-level not present (forward-compat)
    derived_migration = 0
    derived_fully = 0
    derived_under = 0
    have_any_migration = False

    for k in kernels:
        rt_cls, rt_dot, rt_label = _runtime_verdict(k)
        mg_cls, mg_dot, mg_label = _migration_verdict(k)
        under = _under_exercised(k, threshold)
        if under:
            derived_under += 1
        if mg_cls != "muted":
            have_any_migration = True
        if k.get("migration_source_identical") is True:
            derived_migration += 1
        if (
            k.get("bit_identical") is True or k.get("status") == "BIT_IDENTICAL"
        ) and k.get("migration_source_identical") is True:
            derived_fully += 1

        max_ulp = k.get("max_ulp")
        if max_ulp == 0:
            ulp_html = '<span class="ulp0">0</span>'
        elif max_ulp is None:
            ulp_html = '<span class="muted">-</span>'
        else:
            ulp_html = str(max_ulp)

        tf_html = _fmt_int(k.get("total_floats"))
        under_flag = (
            '<span class="under-flag">under-exercised</span>' if under else ""
        )

        oracle = k.get("oracle") or "-"
        dtype = k.get("dtype") or ""
        backend = k.get("backend") or "-"
        device = k.get("device") or ""
        backend_dev = html.escape(backend)
        if dtype or device:
            extras = " ".join(x for x in [dtype, device] if x)
            backend_dev += (
                ' <span class="muted">%s</span>' % html.escape(extras)
            )

        # Notes column: diagnosis + owner (from open-cells enrichment)
        note_parts = []
        if k.get("diagnosis"):
            note_parts.append(
                '<span class="diag">%s</span>' % html.escape(k["diagnosis"])
            )
        if k.get("owner"):
            note_parts.append(
                '<span class="owner">@%s</span>' % html.escape(k["owner"])
            )
        note_html = " ".join(note_parts) if note_parts else ""

        tr_class = ' class="under-exercised"' if under else ""
        row = (
            "<tr%s>"
            '<td><span class="dot %s"></span></td>'
            '<td class="k">%s</td>'
            "<td>%s</td>"
            '<td class="%s">%s</td>'
            '<td class="num">%s</td>'
            '<td class="num">%s%s</td>'
            '<td class="oracle">%s</td>'
            "<td>%s</td>"
            '<td><span class="dot %s"></span><span class="%s">%s</span></td>'
            "<td>%s</td>"
            "</tr>"
        ) % (
            tr_class,
            rt_dot,
            html.escape(k.get("kernel", "-")),
            html.escape(k.get("shape", "-")),
            rt_cls,
            html.escape(rt_label),
            ulp_html,
            tf_html,
            under_flag,
            html.escape(oracle),
            backend_dev,
            mg_dot,
            mg_cls,
            html.escape(mg_label),
            note_html,
        )
        rows_html.append(row)

    # Prefer top-level counts if present; else use derived. Both come from JSON;
    # derived just protects against inconsistency + populates when JSON lacks them.
    if migration_identical is None:
        migration_identical = derived_migration if have_any_migration else None
    if fully_bit_perfect is None:
        fully_bit_perfect = (
            derived_fully if have_any_migration else None
        )

    pct = round(100 * bit_identical / total) if total else 0
    open_count = total - bit_identical

    # If bit_identical came from the deprecated `passed` fallback (Mavdil's
    # catch), decorate the count with an unverified marker and dim it. The
    # NUMBER is shown (panel not blank), but a reader immediately sees it's
    # from a legacy field that conflated the two classes — never trust it as
    # the honest 0-ULP count.
    if bit_identical_from_legacy:
        bit_identical_display = "%s*" % bit_identical
        headline_class = "count warn"
        headline_label = (
            "/ %s bit_identical* (unverified: from deprecated `passed`; "
            "may include within-tolerance)" % total
        )
        bar_label = (
            "%s* / %s runtime 0-ULP (%s%%, unverified: legacy `passed` fallback)"
            % (bit_identical, total, pct)
        )
    else:
        bit_identical_display = str(bit_identical)
        headline_class = "count ok"
        headline_label = "/ %s runtime 0-ULP bit-identical" % total
        bar_label = "%s / %s runtime 0-ULP (%s%%)" % (bit_identical, total, pct)

    headline_count_html = (
        '<div class="%s"><b>%s</b><span class="lbl">%s</span></div>'
        % (headline_class, html.escape(bit_identical_display), html.escape(headline_label))
    )

    # Conditional count widgets: only render if the axis has data
    migration_count_html = (
        _count_html(
            "ok" if migration_identical == total else "warn",
            "/ %s migration source-identical (swipl→swilgt)" % total,
            migration_identical,
        )
        if migration_identical is not None
        else ""
    )
    fully_count_html = (
        _count_html(
            "ok" if fully_bit_perfect == total else "warn",
            "/ %s fully bit-perfect (both axes green)" % total,
            fully_bit_perfect,
        )
        if fully_bit_perfect is not None
        else ""
    )
    within_count_html = (
        _count_html("warn", "within tolerance (open cells)", within_tolerance)
        if within_tolerance is not None
        else ""
    )
    failed_count_html = (
        _count_html("fail", "diverged beyond tolerance", failed)
        if failed is not None
        else ""
    )
    under_count_html = (
        _count_html("warn", "rows under-exercised (< %d floats)" % threshold, derived_under)
        if derived_under > 0
        else ""
    )

    # FRESHNESS STAMP (Iyun's proposal from mavchin's May-30 archaeology):
    # compute age from the JSON's `generated` timestamp vs now; render
    # inline with color-coded staleness. Staleness threshold overridable
    # via top-level `staleness_threshold_seconds` json field.
    staleness_threshold = data.get(
        "staleness_threshold_seconds", STALENESS_THRESHOLD_SECONDS
    )
    fresh_label, fresh_cls = _freshness(data.get("generated"), staleness_threshold)

    return PAGE.format(
        generated=html.escape(str(data.get("generated", "?"))),
        fresh_label=html.escape(fresh_label),
        fresh_cls=fresh_cls,
        pct=pct,
        bit_identical=bit_identical,
        total=total,
        open_count=open_count,
        headline_count_html=headline_count_html,
        bar_label=html.escape(bar_label),
        migration_count_html=migration_count_html,
        fully_count_html=fully_count_html,
        within_count_html=within_count_html,
        failed_count_html=failed_count_html,
        under_count_html=under_count_html,
        rows="\n".join(rows_html),
    )


class H(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path.rstrip("/") in ("", "/dashboard"):
            body = render().encode()
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        elif self.path == "/status.json":
            try:
                body = open(STATUS_FILE, "rb").read()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.end_headers()
                self.wfile.write(body)
            except Exception as e:
                self.send_response(500)
                self.end_headers()
                self.wfile.write(str(e).encode())
        else:
            self.send_response(404)
            self.end_headers()

    def log_message(self, *a):
        pass


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", type=int, default=8477)
    ap.add_argument("--status", default="congruence_status.json")
    a = ap.parse_args()
    STATUS_FILE = a.status
    print(
        "LlamaTov 0-ULP dashboard (two-axis, forward-compat) on :%d (status=%s)"
        % (a.port, STATUS_FILE)
    )
    ThreadingHTTPServer(("0.0.0.0", a.port), H).serve_forever()
