#!/usr/bin/env python3
"""congruence_dashboard.py — real-time 0-ULP congruence dashboard for LlamaTov.

Serves a two-axis matrix of per-kernel bit-identity:
  RUNTIME axis  — does the kernel COMPUTE bit-identically to the oracle?
                  (Track A, bit_identical_universal.py)
  MIGRATION axis — does the kernel EMIT byte-identically swipl → swilgt?
                   (Track B, mavhir's emit_diff_matrix.py)

Reads congruence_status.json (produced by Track A -> A2 model, extended per
dashboard/CONGRUENCE_SCHEMA.md). Refreshes on each page load; JSON is
regenerated by gate runs (C3 real-time).

FORWARD-COMPAT RENDER (mavhir 2026-09-02, per Iyun's (b) call):
Renders the versioned schema (CONGRUENCE_SCHEMA.md at dca5d9e / 4d23761)
defensively — every new field uses .get(...) with a graceful "-" fallback,
so this app works with:
  * Old JSON (just `passed` + `kernel`/`shape`/`status`/`max_ulp`/`bit_identical`/`backend`)
  * New JSON with population fields (total_floats/diverged_count/oracle/dtype/device)
  * New JSON with verdict-honest counts (bit_identical/within_tolerance/failed)
  * New JSON with migration axis (migration_source_identical/swipl_sha/swilgt_sha/migration_unit)
  * Any mixture of the above during migration transitions.

If a field is missing, its cell renders "-" and the row is not counted as
present for that axis. THE VERDICT-CLASS RULE is honored: `passed` is never
emitted or consumed as green; only `bit_identical` count is the true 0-ULP
headline. THE EMPTY-POPULATION GUARD is honored: `total_floats` is surfaced;
rows below UNDER_EXERCISED_THRESHOLD are dimmed + marked with a warning.

Usage: python3 congruence_dashboard.py [--port 8477] [--status congruence_status.json]

--status resolution (Mavdil's ef0d8dc3 catch): if the value is a relative
path, resolve it against the SCRIPT'S directory first (so `python3
dashboard/congruence_dashboard.py` from repo root finds the neighboring
congruence_status.json without needing CWD=dashboard/). If that doesn't
exist, fall back to CWD-relative for backward-compat with any existing
invocation. Absolute paths are used as-is. The systemd service on the
enclave sets WorkingDirectory=/home/dibbur-patch/step3-det-gemv/bpd and
passes --status congruence_status.json — that continues to work because
the CWD-relative fallback path resolves correctly there. No breaking
change; just removes the CWD-only quirk Mavdil hit.
"""
import json, os, argparse, html, datetime, re, sys
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

STATUS_FILE = "congruence_status.json"
MIGRATION_FILE = "migration_status.json"
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))


def _resolve_status_file(path):
    """Resolve --status to an absolute path robustly (Mavdil ef0d8dc3):
    - absolute path: used as-is
    - relative path: try SCRIPT_DIR/path first, then CWD/path.
      First-existing wins; if neither exists, return SCRIPT_DIR/path so
      the error message names the expected canonical location.
    """
    if os.path.isabs(path):
        return path
    script_relative = os.path.join(_SCRIPT_DIR, path)
    if os.path.exists(script_relative):
        return script_relative
    cwd_relative = os.path.abspath(path)
    if os.path.exists(cwd_relative):
        return cwd_relative
    # Neither exists — return script-relative so error messages name the
    # canonical expected location (dashboard/<file>) not an obscure CWD path.
    return script_relative

# Under-exercised threshold from CONGRUENCE_SCHEMA.md guidance ("< 1000 floats").
# Per schema doc: dashboard MAY dim/flag rows below this; boolean per-row, not
# a hard fail. If Mavdil's implementation surfaces a different threshold in
# the JSON, this local default can be overridden by json field `under_exercised_threshold`.
UNDER_EXERCISED_THRESHOLD = 1000

# Staleness threshold for the FRESHNESS STAMP (Iyun's proposal from mavchin's
# May-30 dashboard archaeology): if the JSON's `generated` timestamp is older
# than this, mark the freshness widget red so staleness is self-evident on
# the dashboard's own face. Default: 5 minutes for a live matrix. Overridable
# via json top-level `staleness_threshold_seconds` field. See substrate lesson:
# "a dashboard that can't prove its own liveness can silently show stale data
# as if fresh — same class as hollow-green (looks-current, might-not-be)."
STALENESS_THRESHOLD_SECONDS = 300

PAGE = """<!DOCTYPE html><html><head><meta charset="utf-8">
<title>LlamaTov · Bit-Perfect Dispatch</title>
<meta http-equiv="refresh" content="10">
<style>
 body{{background:#0b0e14;color:#c9d1d9;font-family:'JetBrains Mono',ui-monospace,monospace;margin:0;padding:2rem}}
 h1{{color:#e6edf3;font-weight:600;font-size:1.4rem;margin:0 0 .3rem}}
 .sub{{color:#8b949e;margin-bottom:1.5rem;font-size:.85rem}}
 .counts{{display:flex;gap:1.5rem;margin:1rem 0;font-size:.85rem;flex-wrap:wrap;align-items:flex-start}}
 .count-group{{display:flex;flex-direction:column;gap:.4rem;padding:.5rem .8rem;border-left:2px solid #21262d;background:transparent}}
 .count-group.axis-runtime{{border-left-color:#3fb950}}
 .count-group.axis-truth{{border-left-color:#79c0ff}}
 .count-group.axis-migration{{border-left-color:#d29922}}
 .count-group.axis-meta{{border-left-color:#484f58}}
 .count-group-title{{color:#8b949e;font-size:.68rem;text-transform:uppercase;letter-spacing:.08em;font-weight:500;margin-bottom:.15rem}}
 .count-group-widgets{{display:flex;gap:.6rem;flex-wrap:wrap}}
 /* Ratify Mavdil 70056acf: two partitions of the same 22 rows must NOT
    read as double-counting. Group widgets by axis (runtime vs stock,
    truth, migration, meta) with a colored left-border + subtitle, so a
    reader immediately sees "these numbers are different views of the
    same rows" not "these numbers are additive tallies." Preserves the
    substrate distinction: multiple honest partitions of one population. */
 .count{{padding:.4rem .8rem;border:1px solid #21262d;border-radius:6px;background:#161b22}}
 .count b{{color:#e6edf3;font-size:1.05rem;margin-right:.4rem}}
 .count .lbl{{color:#8b949e}}
 .count.ok b{{color:#3fb950}}
 .count.warn b{{color:#d29922}}
 .count.fail b{{color:#f85149}}
 .bar{{height:34px;background:#161b22;border-radius:6px;overflow:hidden;margin:1rem 0;position:relative;border:1px solid #21262d}}
 .fill{{height:100%;background:linear-gradient(90deg,#238636,#2ea043);transition:width .6s}}
 .barlabel{{position:absolute;top:0;left:0;right:0;line-height:34px;text-align:center;font-weight:600;color:#fff;text-shadow:0 1px 2px #000}}
 table{{border-collapse:collapse;width:100%;margin-top:1rem;font-size:.82rem}}
 th{{text-align:left;color:#8b949e;font-weight:500;padding:.4rem .6rem;border-bottom:1px solid #21262d;font-size:.75rem;text-transform:uppercase;letter-spacing:.05em}}
 td{{padding:.35rem .6rem;border-bottom:1px solid #161b22;vertical-align:middle}}
 tr.under-exercised td{{opacity:.55}}
 .ok{{color:#3fb950}} .warn{{color:#d29922}} .fail{{color:#f85149}} .muted{{color:#484f58}}
 .dot{{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:.25rem;vertical-align:middle}}
 .dot.ok{{background:#3fb950}} .dot.warn{{background:#d29922}} .dot.fail{{background:#f85149}} .dot.muted{{background:#484f58}}
 .ulp0{{color:#3fb950;font-weight:600}}
 .num{{text-align:right;font-variant-numeric:tabular-nums}}
 .foot{{margin-top:2rem;color:#484f58;font-size:.75rem}}
 .k{{color:#79c0ff}}
 .oracle{{color:#a5d6ff;font-size:.75rem}}
 .diag{{color:#d29922;font-size:.72rem;font-style:italic}}
 .owner{{color:#8b949e;font-size:.72rem}}
 .under-flag{{color:#d29922;font-size:.7rem;margin-left:.3rem}}
 .fresh-stamp{{display:inline-block;padding:.15rem .5rem;border-radius:4px;font-size:.72rem;font-weight:600;margin-left:.5rem;letter-spacing:.02em}}
 .fresh-stamp.ok{{background:#0f2818;color:#3fb950;border:1px solid #1a3a24}}
 .fresh-stamp.warn{{background:#2b210a;color:#d29922;border:1px solid #3d2f11}}
 .fresh-stamp.fail{{background:#2b1114;color:#f85149;border:1px solid #3f1a1f}}
 .fresh-stamp.muted{{background:#161b22;color:#484f58;border:1px solid #21262d}}
 h2{{color:#e6edf3;font-weight:500;font-size:1.05rem;margin:2.5rem 0 .3rem}}
 .h2-note{{color:#8b949e;font-size:.75rem;margin-bottom:1rem}}
 .op-table{{border-collapse:collapse;width:100%;margin-top:.5rem;font-size:.82rem}}
 .op-table th{{text-align:left;color:#8b949e;font-weight:500;padding:.4rem .6rem;border-bottom:1px solid #21262d;font-size:.72rem;text-transform:uppercase;letter-spacing:.05em}}
 .op-table td{{padding:.35rem .6rem;border-bottom:1px solid #161b22;vertical-align:top}}
 .op-name{{color:#79c0ff;font-weight:600}}
 .state-both{{color:#3fb950;font-weight:600;font-size:.7rem;letter-spacing:.05em}}
 .state-runtime-only{{color:#d29922;font-weight:600;font-size:.7rem;letter-spacing:.05em}}
 .state-emitted-only{{color:#a5d6ff;font-weight:600;font-size:.7rem;letter-spacing:.05em}}
 .kernel-list{{color:#c9d1d9;font-size:.78rem}}
 .absent-cell{{color:#484f58;font-style:italic;font-size:.78rem}}
 .improved{{color:#79c0ff;font-weight:600}}
 .dot.improved{{background:#79c0ff}}
 .count.improved b{{color:#79c0ff}}
 /* UNMEASURED (accuracy axis): visually distinct from both muted-absent
    (no data) and fail-inaccurate (measured-wrong). Mavdil's 79ef4702
    catch: "we have not checked" is a DIFFERENT FACT from "we checked and
    we are worse" — must not read as failure. Amber-ringed empty dot +
    italic label signals "known open slot, not yet measured." */
 .unmeasured{{color:#d29922;font-style:italic;font-weight:500}}
 .dot.unmeasured{{background:transparent;border:1.5px solid #d29922;box-sizing:border-box}}
 .count.unmeasured b{{color:#d29922}}
</style></head><body>
<h1>🕯️ LlamaTov · Bit-Perfect Dispatch</h1>
<div class="sub">Two-axis 0-ULP congruence matrix — RUNTIME (compute vs oracle) × MIGRATION (source-preservation swipl→swilgt). Generated {generated} <span class="fresh-stamp {fresh_cls}">{fresh_label}</span> · auto-refresh 10s</div>

<div class="counts">
  <!-- Runtime axis (vs stock): the classic 0-ULP metric — verdict-class-honest -->
  <div class="count-group axis-runtime">
    <div class="count-group-title">vs stock (runtime)</div>
    <div class="count-group-widgets">
      {headline_count_html}
      {within_count_html}
      {failed_count_html}
    </div>
  </div>
  <!-- Truth axis (vs oracle/measured truth): Mavdil's accuracy-class emitter -->
  {truth_group_html}
  <!-- Migration axis (swipl→swilgt source-preservation) -->
  {migration_group_html}
  <!-- Meta / measurement quality -->
  <div class="count-group axis-meta">
    <div class="count-group-title">measurement</div>
    <div class="count-group-widgets">
      {floats_compared_html}
      {under_count_html}
    </div>
  </div>
</div>

<div class="bar"><div class="fill" style="width:{pct}%"></div><div class="barlabel">{bar_label}</div></div>

<table>
  <thead><tr>
    <th></th>
    <th>Kernel</th>
    <th>Shape</th>
    <th>Runtime</th>
    <th class="num">max ULP</th>
    <th class="num">Floats</th>
    <th>Oracle</th>
    <th>Backend/Dev</th>
    <th>Accuracy (vs truth)</th>
    <th>Migration</th>
    <th>Notes</th>
  </tr></thead>
  <tbody>
{rows}
  </tbody>
</table>

{by_op_section}

<div class="foot">
  {open_count} open cell(s) toward full bit-perfect · LlamaTov / bpd-substrate ·
  schema: dashboard/CONGRUENCE_SCHEMA.md
</div>
</body></html>"""


def _fmt_int(n):
    """Human-readable int formatting: 1234567 -> 1,234,567."""
    if n is None:
        return "-"
    try:
        return f"{int(n):,}"
    except (ValueError, TypeError):
        return "-"


def _parse_iso_utc(s):
    """Parse ISO-8601 UTC (e.g. '2026-09-02T14:42:49Z') as a naive datetime in
    UTC. Returns None on any parse failure — freshness stamp then shows
    '(unknown age)' rather than crashing.
    """
    if not s or not isinstance(s, str):
        return None
    # Normalize 'Z' -> '+00:00' so fromisoformat accepts it (pre-3.11 quirk)
    s2 = s.strip()
    if s2.endswith("Z"):
        s2 = s2[:-1] + "+00:00"
    try:
        dt = datetime.datetime.fromisoformat(s2)
        # If tz-aware, convert to UTC + strip tzinfo for compare against utcnow()
        if dt.tzinfo is not None:
            dt = dt.astimezone(datetime.timezone.utc).replace(tzinfo=None)
        return dt
    except (ValueError, TypeError):
        return None


def _freshness(generated_str, threshold_seconds):
    """Compute the freshness stamp for the FRESHNESS STAMP widget.

    Iyun's May-30-recovered pattern via mavchin's archaeology: the dashboard
    must prove its own liveness on its own face. A dashboard that renders a
    stale JSON as if fresh is the same class of failure as the hollow-green
    (looks-current, might-not-be).

    Returns (age_label, css_class):
        age_label: "12s ago", "3m ago", "2h 15m ago", or "(unknown age)"
        css_class: "ok" (< threshold), "warn" (< 3*threshold), "fail" (older)
                   or "muted" if we can't parse the timestamp
    """
    dt = _parse_iso_utc(generated_str)
    if dt is None:
        return "(unknown age)", "muted"
    # utcnow() is deprecated in Python 3.12+; use tz-aware now() then strip
    # for compare with our naive-UTC parsed dt. Backward-compat + no warning.
    now = datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None)
    delta = now - dt
    seconds = int(delta.total_seconds())
    if seconds < 0:
        # Future timestamp — clock skew or bad data. Show but don't panic.
        return "(from the future, %ds skew)" % (-seconds), "warn"
    if seconds < 60:
        label = "%ds ago" % seconds
    elif seconds < 3600:
        label = "%dm %ds ago" % (seconds // 60, seconds % 60)
    elif seconds < 86400:
        label = "%dh %dm ago" % (seconds // 3600, (seconds % 3600) // 60)
    else:
        label = "%dd %dh ago" % (seconds // 86400, (seconds % 86400) // 3600)
    if seconds <= threshold_seconds:
        cls = "ok"
    elif seconds <= threshold_seconds * 3:
        cls = "warn"
    else:
        cls = "fail"
    return label, cls


def _runtime_verdict(k):
    """Classify a row's RUNTIME axis into (css_class, dot_class, label).

    Honors THE VERDICT-CLASS RULE: only BIT_IDENTICAL is green. PASS_* classes
    are warn (not counted-green). FAIL is fail. Missing/unknown is muted.
    """
    status = k.get("status", "")
    bi = k.get("bit_identical", False)
    if status == "BIT_IDENTICAL" or (bi is True and status == ""):
        return "ok", "ok", status or "BIT_IDENTICAL"
    if status.startswith("PASS"):
        return "warn", "warn", status
    if status == "FAIL" or status.startswith("FAIL"):
        return "fail", "fail", status
    if not status:
        return "muted", "muted", "-"
    # Unknown status class — surface it as warn to catch our attention
    return "warn", "warn", status


def _accuracy_verdict(k):
    """Classify a row's ACCURACY axis (vs TRUTH, per Mavdil c3bbf96 + ebd0cb4).

    accuracy_class field: MATCHED / IMPROVED / INACCURATE / UNMEASURED.
    Returns (css_class, dot_class, label, evidence_html) where evidence_html
    is the mean_abs_err ratio + correctly_rounded delta for IMPROVED/INACCURATE
    rows that carry evidence fields.

    PHYSICS CONSTRAINT (Mavdil's test): BIT_IDENTICAL forces MATCHED. If a
    row claims BIT_IDENTICAL + non-MATCHED accuracy_class, that's a broken
    measurement — render as fail with an explicit "IMPOSSIBLE COMBINATION"
    label so it can't be missed.
    """
    ac = k.get("accuracy_class")
    status = k.get("status", "")
    is_bit_identical = (status == "BIT_IDENTICAL" or k.get("bit_identical") is True)

    if ac is None:
        return "muted", "muted", "-", ""

    # Physics constraint check: BIT_IDENTICAL ENTAILS MATCHED. Any other
    # accuracy_class on a BIT_IDENTICAL row is broken.
    if is_bit_identical and ac != "MATCHED":
        return ("fail", "fail",
                f"IMPOSSIBLE ({ac} on BIT_IDENTICAL)",
                '<span class="fail" style="font-size:.7rem">broken measurement</span>')

    # Evidence rendering: for IMPROVED/INACCURATE, show the ratio + rounded delta
    evidence = ""
    ours = k.get("mean_abs_err_ours")
    stock = k.get("mean_abs_err_stock")
    cr_ours = k.get("correctly_rounded_ours")
    cr_stock = k.get("correctly_rounded_stock")
    if ours is not None and stock is not None and stock > 0:
        ratio = stock / ours
        ratio_str = f"{ratio:.2g}× better" if ratio > 1 else f"{1/ratio:.2g}× worse"
        cr_str = ""
        if cr_ours is not None and cr_stock is not None:
            cr_str = (
                f' · rounded {_fmt_int(cr_ours)}/{_fmt_int(cr_stock)}'
            )
        evidence = (
            f'<span class="muted" style="font-size:.7rem">'
            f'|err| {ours:.2e}/{stock:.2e} ({ratio_str}){cr_str}'
            f'</span>'
        )

    if ac == "MATCHED":
        return "ok", "ok", "MATCHED", evidence
    if ac == "IMPROVED":
        return "improved", "improved", "IMPROVED", evidence
    if ac == "INACCURATE":
        return "fail", "fail", "INACCURATE", evidence
    if ac == "UNMEASURED":
        # Per Mavdil 79ef4702: UNMEASURED must be visually distinct from
        # both INACCURATE (measured-wrong, red) and from muted-absent
        # (no data at all). "We have not checked" is a DIFFERENT FACT
        # from "we checked and are worse." Its own CSS class: amber-
        # outlined empty dot + italic label. Iyun ratified UNMEASURED
        # as its own class precisely to prevent this collapse.
        return "unmeasured", "unmeasured", "UNMEASURED", ""
    # Unknown accuracy_class — surface as warn to catch our attention
    return "warn", "warn", ac, evidence


def _migration_verdict(k):
    """Classify a row's MIGRATION axis. Returns (css_class, dot_class, label).

    Field is `migration_source_identical` (bool). Missing = axis-not-populated-yet
    (renders as muted "-", not a fail). True = byte-identical swipl→swilgt.
    False = source diverged.
    """
    if "migration_source_identical" not in k:
        return "muted", "muted", "-"
    if k["migration_source_identical"] is True:
        return "ok", "ok", "byte-identical"
    if k["migration_source_identical"] is False:
        return "fail", "fail", "DIVERGED"
    return "muted", "muted", "-"


def _under_exercised(k, threshold):
    """Boolean: is this row under the population threshold? Missing total_floats
    = we CAN'T tell, so we don't flag (render but don't dim)."""
    tf = k.get("total_floats")
    if tf is None:
        return False
    try:
        return int(tf) < threshold
    except (ValueError, TypeError):
        return False


def _count_html(css, label, value):
    return (
        '<div class="count %s"><b>%s</b><span class="lbl">%s</span></div>'
        % (css, html.escape(str(value)), html.escape(label))
    )


def _render_by_op_section(data):
    """Render the two-axis join-by-op section (three-state: both /
    runtime-only / emitted-only). Per Mavdil's OP_MAPPING.md contract
    (6106eb0, ratified by mavhir a6cb99c3): the two axes measure DIFFERENT
    POPULATIONS and overlap by OPERATION, not by kernel name. Join key is
    canonical `op` string. Ops present on both sides show BOTH; on one side
    only show the honest asymmetry (not silently dropped, not falsely joined).

    Parses OP_MAPPING.md at render-time via op_mapping_parser (doc-as-truth
    per Mavdil's 23e7b241 (C) endorsement). Reads migration axis from
    data.get("migration") if present; renders "-" for absent migration data
    per the graceful-fallback pattern.

    Returns HTML string. Empty string if no ops parseable (dashboard degrades
    to just the runtime table without the by-op section — same discipline as
    all other absent-field-renders-nothing surfaces).
    """
    try:
        # Substrate — import lazily so the dashboard still boots if the parser
        # file is missing or the OP_MAPPING.md doesn't exist.
        import op_mapping_parser
        mapping = op_mapping_parser.parse()
    except Exception as e:
        return (
            '<h2 class="muted">By Op (two-axis join)</h2>'
            '<div class="h2-note">Could not parse OP_MAPPING.md: %s</div>'
        ) % html.escape(str(e))

    if not mapping:
        return ""

    # Substrate — build indices of runtime-kernel-name -> row status
    runtime_status = {}  # kernel_name -> (status_class, max_ulp, total_floats)
    for k in data.get("kernels", []):
        name = k.get("kernel")
        if not name:
            continue
        # Runtime rows can appear multiple times per kernel (different shapes).
        # For the by-op summary, keep the WORST-status row per kernel (so a
        # PASS_ABS_TOLERANCE on one shape doesn't hide behind BIT_IDENTICAL
        # on another). Ordering: FAIL > PASS_* > BIT_IDENTICAL.
        status = k.get("status", "")
        current = runtime_status.get(name)
        # Simple worst-priority: FAIL > PASS > BIT_IDENTICAL > empty
        prio = 0
        if status.startswith("FAIL"):
            prio = 3
        elif status.startswith("PASS"):
            prio = 2
        elif status == "BIT_IDENTICAL":
            prio = 1
        if current is None or prio > current[0]:
            runtime_status[name] = (prio, status, k.get("max_ulp"),
                                     k.get("total_floats"))

    # Substrate — migration axis: from data["migration"]["units"] if present
    migration_status = {}  # kernel_name -> True/False (byte-identical)
    migration_data = data.get("migration", {})
    for u in migration_data.get("units", []):
        name = u.get("name")
        if not name:
            continue
        migration_status[name] = u.get("migration_source_identical", None)

    # Substrate — render one row per op, grouped by state
    rows_by_state = {"both": [], "runtime-only": [], "emitted-only": []}
    for op in sorted(mapping.keys()):
        state = op_mapping_parser.join_state(op, mapping)
        if state not in rows_by_state:
            continue
        cells = mapping[op]
        # Runtime cell HTML: list of runtime kernels + status per kernel
        if cells["runtime"]:
            r_html_parts = []
            for kname in cells["runtime"]:
                if kname in runtime_status:
                    _prio, status, max_ulp, _tf = runtime_status[kname]
                    status_class = "ok" if status == "BIT_IDENTICAL" else (
                        "warn" if status.startswith("PASS") else (
                            "fail" if status.startswith("FAIL") else "muted"
                        )
                    )
                    ulp_str = ""
                    if max_ulp is not None and max_ulp != 0:
                        ulp_str = f" ({max_ulp} ULP)"
                    r_html_parts.append(
                        f'<div><span class="dot {status_class}"></span>'
                        f'<span class="k">{html.escape(kname)}</span>'
                        f'<span class="muted"> {html.escape(status)}{html.escape(ulp_str)}</span></div>'
                    )
                else:
                    # Cited in mapping but not in JSON — could be the polarity
                    # false-positive class Mavdil named (e.g. gelu_tanh_cpu
                    # cited as absent). But if we're here, the parser DIDN'T
                    # skip it, so it's genuinely-cited-but-not-yet-measured.
                    r_html_parts.append(
                        f'<div><span class="dot muted"></span>'
                        f'<span class="k">{html.escape(kname)}</span>'
                        f'<span class="muted"> (not measured)</span></div>'
                    )
            r_html = "".join(r_html_parts)
        else:
            r_html = '<span class="absent-cell">(no runtime cell)</span>'
        # Emitted cell HTML: list of emitted kernels + migration status
        if cells["emitted"]:
            e_html_parts = []
            for kname in cells["emitted"]:
                mig = migration_status.get(kname)
                if mig is True:
                    e_html_parts.append(
                        f'<div><span class="dot ok"></span>'
                        f'<span class="k">{html.escape(kname)}</span>'
                        f'<span class="muted"> byte-identical</span></div>'
                    )
                elif mig is False:
                    e_html_parts.append(
                        f'<div><span class="dot fail"></span>'
                        f'<span class="k">{html.escape(kname)}</span>'
                        f'<span class="fail"> DIVERGED</span></div>'
                    )
                else:
                    e_html_parts.append(
                        f'<div><span class="dot muted"></span>'
                        f'<span class="k">{html.escape(kname)}</span>'
                        f'<span class="muted"> -</span></div>'
                    )
            e_html = "".join(e_html_parts)
        else:
            e_html = '<span class="absent-cell">(no emitted counterpart)</span>'
        state_label_class = f"state-{state}"
        state_label = state.upper().replace("-", " ")
        row = (
            f'<tr><td><span class="op-name">{html.escape(op)}</span></td>'
            f'<td><span class="{state_label_class}">{html.escape(state_label)}</span></td>'
            f'<td>{r_html}</td>'
            f'<td>{e_html}</td></tr>'
        )
        rows_by_state[state].append(row)

    counts = {s: len(rows_by_state[s]) for s in rows_by_state}
    total_ops = sum(counts.values())
    all_rows = (rows_by_state["both"] + rows_by_state["runtime-only"]
                + rows_by_state["emitted-only"])

    header = (
        '<h2>By Op — Two-Axis Join</h2>'
        '<div class="h2-note">'
        'Runtime axis × Migration axis, joined by canonical <code>op</code> per '
        '<code>dashboard/OP_MAPPING.md</code>. '
        f'<span class="state-both">{counts["both"]} both</span> · '
        f'<span class="state-runtime-only">{counts["runtime-only"]} runtime-only</span> · '
        f'<span class="state-emitted-only">{counts["emitted-only"]} emitted-only</span> · '
        f'{total_ops} ops total. '
        'Different populations, overlap by operation.'
        '</div>'
    )
    table = (
        '<table class="op-table">'
        '<thead><tr>'
        '<th>Op</th><th>State</th><th>Runtime axis (vs oracle)</th>'
        '<th>Migration axis (swipl→swilgt)</th>'
        '</tr></thead>'
        f'<tbody>{"".join(all_rows)}</tbody>'
        '</table>'
    )
    return header + table


def render():
    try:
        data = json.load(open(STATUS_FILE))
    except Exception as e:
        return (
            "<html><body style='background:#0b0e14;color:#f85149;font-family:monospace;padding:2rem'>"
            "No congruence data yet: %s</body></html>"
        ) % html.escape(str(e))

    # TWO-FILE READ (Mavdil 23e7b241 (β) integration, Iyun 8f2ceb84 GO):
    # runtime axis from cs.json (already loaded); migration axis from a
    # sibling migration_status.json emitted by mavhir's emit_diff_matrix.py
    # --production. Merged into data["migration"] so downstream render
    # (top-level counts, by-op section) sees a unified view. Absent file
    # renders empty migration axis gracefully (forward-compat).
    #
    # Preserve any data["migration"] the JSON already carries (unlikely
    # today but supports Mavdil-merges-migration-into-cs.json workflow if
    # anyone chooses (α)-integration in the future).
    try:
        migration_path = _resolve_status_file(MIGRATION_FILE)
        if os.path.exists(migration_path):
            migration_data = json.load(open(migration_path))
            # Overlay migration data. If cs.json didn't carry it, populate
            # from migration_status.json. If it DID, cs.json wins (author's
            # explicit merge takes precedence over auto-merge from separate
            # file — same discipline as env-var precedence over defaults).
            if "migration" not in data:
                data["migration"] = migration_data
                # Lift top-level count fields from migration_status.json into
                # data's top-level so existing count widgets (migration_count_html,
                # fully_count_html) fire without needing to know the merge shape.
                # Only lift if not already present (cs.json's explicit fields
                # win — same precedence as the merge itself).
                for key in ("migration_identical", "migration_diverged",
                             "total_kernels"):
                    if key not in data and key in migration_data:
                        data[key] = migration_data[key]
                # fully_bit_perfect requires joining runtime BIT_IDENTICAL
                # with migration_source_identical per-op — derived at row-loop
                # time (not liftable), let existing derived logic compute.
    except Exception:
        # Any parse/read failure — silently degrade to no-migration.
        # Same defensive-fallback discipline as the rest of the render:
        # absent field != crash, absent field == muted "-".
        pass

    # THE VERDICT-CLASS RULE: bit_identical is the true 0-ULP count. The
    # deprecated `passed` field CONFLATED bit_identical with within_tolerance
    # (the whole point of the rule was to abolish that conflation). So the
    # fallback path must NOT silently substitute passed's value for
    # bit_identical — that would preserve the deprecated semantics under the
    # new name (Mavdil's catch, 2026-09-02: "a compatibility path is where
    # deprecated semantics survives — the name changed, the number didn't").
    #
    # Instead: if `bit_identical` is absent but `passed` is present, we mark
    # the count as unverified-legacy (bit_identical_legacy_conflated=True) so
    # the render dims it + shows an asterisk + a tooltip explaining. The
    # only fully-honest degradation is showing "-" for a legacy JSON that
    # can't distinguish 0-ULP from within-tolerance — but that loses the
    # panel entirely. Splitting the difference: display the number with an
    # explicit unverified marker so a reader knows THIS COUNT IS FROM THE
    # DEPRECATED CONFLATED FIELD, not the honest bit-identical field.
    total = data.get("total", 0)
    if "bit_identical" in data:
        bit_identical = data["bit_identical"]
        bit_identical_from_legacy = False
    elif "passed" in data:
        bit_identical = data["passed"]
        bit_identical_from_legacy = True
    else:
        bit_identical = 0
        bit_identical_from_legacy = False
    within_tolerance = data.get("within_tolerance")  # may be None on old JSON
    failed = data.get("failed")

    threshold = data.get("under_exercised_threshold", UNDER_EXERCISED_THRESHOLD)

    # Migration axis top-level counts (both from JSON if present, else derived)
    migration_identical = data.get("migration_identical")
    fully_bit_perfect = data.get("fully_bit_perfect")

    rows_html = []
    kernels = data.get("kernels", [])

    # Derive counts from per-row if top-level not present (forward-compat)
    derived_migration = 0
    derived_fully = 0
    derived_under = 0
    have_any_migration = False

    # Substrate — derived per-row counters for accuracy axis too (Mavdil ebd0cb4).
    derived_matched = 0
    derived_improved = 0
    derived_inaccurate = 0
    derived_unmeasured = 0
    have_any_accuracy = False

    for k in kernels:
        rt_cls, rt_dot, rt_label = _runtime_verdict(k)
        mg_cls, mg_dot, mg_label = _migration_verdict(k)
        ac_cls, ac_dot, ac_label, ac_evidence = _accuracy_verdict(k)
        under = _under_exercised(k, threshold)
        if under:
            derived_under += 1
        if mg_cls != "muted":
            have_any_migration = True
        if k.get("migration_source_identical") is True:
            derived_migration += 1
        if (
            k.get("bit_identical") is True or k.get("status") == "BIT_IDENTICAL"
        ) and k.get("migration_source_identical") is True:
            derived_fully += 1
        # Accuracy-axis counters
        ac_val = k.get("accuracy_class")
        if ac_val is not None:
            have_any_accuracy = True
            if ac_val == "MATCHED":
                derived_matched += 1
            elif ac_val == "IMPROVED":
                derived_improved += 1
            elif ac_val == "INACCURATE":
                derived_inaccurate += 1
            elif ac_val == "UNMEASURED":
                derived_unmeasured += 1

        max_ulp = k.get("max_ulp")
        if max_ulp == 0:
            ulp_html = '<span class="ulp0">0</span>'
        elif max_ulp is None:
            ulp_html = '<span class="muted">-</span>'
        else:
            ulp_html = str(max_ulp)

        # Floats column: total_floats + diverged_count if any diverged
        # (Mavdil's ask 74c40611: "the population is not displayed" —
        # total_floats was rendering but diverged_count wasn't surfaced.
        # For divergent rows, show "N diverged / M" so a reader sees both
        # the population AND how much of it diverged, not just population).
        tf_val = k.get("total_floats")
        dc_val = k.get("diverged_count")
        if tf_val is None:
            tf_html = "-"
        elif dc_val is not None and dc_val > 0:
            tf_html = (
                f'<span class="warn">{_fmt_int(dc_val)}</span>'
                f'<span class="muted"> / {_fmt_int(tf_val)}</span>'
            )
        else:
            tf_html = _fmt_int(tf_val)
        under_flag = (
            '<span class="under-flag">under-exercised</span>' if under else ""
        )

        oracle = k.get("oracle") or "-"
        dtype = k.get("dtype") or ""
        backend = k.get("backend") or "-"
        device = k.get("device") or ""
        backend_dev = html.escape(backend)
        if dtype or device:
            extras = " ".join(x for x in [dtype, device] if x)
            backend_dev += (
                ' <span class="muted">%s</span>' % html.escape(extras)
            )

        # Notes column: diagnosis + owner (from open-cells enrichment)
        note_parts = []
        if k.get("diagnosis"):
            note_parts.append(
                '<span class="diag">%s</span>' % html.escape(k["diagnosis"])
            )
        if k.get("owner"):
            note_parts.append(
                '<span class="owner">@%s</span>' % html.escape(k["owner"])
            )
        note_html = " ".join(note_parts) if note_parts else ""

        tr_class = ' class="under-exercised"' if under else ""
        # Accuracy column: dot + class label + optional evidence subtext
        ac_html = (
            f'<span class="dot {ac_dot}"></span>'
            f'<span class="{ac_cls}">{html.escape(ac_label)}</span>'
        )
        if ac_evidence:
            ac_html += f'<br>{ac_evidence}'
        row = (
            "<tr%s>"
            '<td><span class="dot %s"></span></td>'
            '<td class="k">%s</td>'
            "<td>%s</td>"
            '<td class="%s">%s</td>'
            '<td class="num">%s</td>'
            '<td class="num">%s%s</td>'
            '<td class="oracle">%s</td>'
            "<td>%s</td>"
            "<td>%s</td>"
            '<td><span class="dot %s"></span><span class="%s">%s</span></td>'
            "<td>%s</td>"
            "</tr>"
        ) % (
            tr_class,
            rt_dot,
            html.escape(k.get("kernel", "-")),
            html.escape(k.get("shape", "-")),
            rt_cls,
            html.escape(rt_label),
            ulp_html,
            tf_html,
            under_flag,
            html.escape(oracle),
            backend_dev,
            ac_html,
            mg_dot,
            mg_cls,
            html.escape(mg_label),
            note_html,
        )
        rows_html.append(row)

    # Prefer top-level counts if present; else use derived. Both come from JSON;
    # derived just protects against inconsistency + populates when JSON lacks them.
    if migration_identical is None:
        migration_identical = derived_migration if have_any_migration else None
    if fully_bit_perfect is None:
        fully_bit_perfect = (
            derived_fully if have_any_migration else None
        )

    pct = round(100 * bit_identical / total) if total else 0
    open_count = total - bit_identical

    # If bit_identical came from the deprecated `passed` fallback (Mavdil's
    # catch), decorate the count with an unverified marker and dim it. The
    # NUMBER is shown (panel not blank), but a reader immediately sees it's
    # from a legacy field that conflated the two classes — never trust it as
    # the honest 0-ULP count.
    if bit_identical_from_legacy:
        bit_identical_display = "%s*" % bit_identical
        headline_class = "count warn"
        headline_label = (
            "/ %s bit_identical* (unverified: from deprecated `passed`; "
            "may include within-tolerance)" % total
        )
        bar_label = (
            "%s* / %s runtime 0-ULP (%s%%, unverified: legacy `passed` fallback)"
            % (bit_identical, total, pct)
        )
    else:
        bit_identical_display = str(bit_identical)
        headline_class = "count ok"
        headline_label = "/ %s runtime 0-ULP bit-identical" % total
        bar_label = "%s / %s runtime 0-ULP (%s%%)" % (bit_identical, total, pct)

    headline_count_html = (
        '<div class="%s"><b>%s</b><span class="lbl">%s</span></div>'
        % (headline_class, html.escape(bit_identical_display), html.escape(headline_label))
    )

    # Conditional count widgets: only render if the axis has data.
    #
    # Migration axis has its OWN population (emitted kernels — 21 per current
    # OP_MAPPING.md), DISTINCT from runtime population (rows in cs.json — 22
    # today). Comparing migration_identical to runtime `total` is a CROSS-AXIS
    # POPULATION COLLAPSE — same trap as gelu_erf vs gelu_tanh being conflated.
    # Each axis's percentage must be against its OWN denominator. Read from
    # data.migration.total_kernels (populated by mavhir's --production emit).
    # Falls back to migration_identical itself (so denominator == numerator
    # renders 100% if migration_total absent) — never uses runtime total for
    # a migration comparison.
    migration_total = (data.get("migration", {}).get("total_kernels")
                        or data.get("total_kernels"))
    if migration_total is None and migration_identical is not None:
        migration_total = migration_identical  # 100% of unknown-total-but-all-passed
    migration_count_html = (
        _count_html(
            "ok" if migration_identical == migration_total else "warn",
            "/ %s migration source-identical (swipl→swilgt)" % migration_total,
            migration_identical,
        )
        if migration_identical is not None
        else ""
    )
    # fully_bit_perfect intentionally compares to runtime `total` because it
    # asks "of the runtime rows, how many are ALSO migration-clean?" —
    # runtime-population question, not migration-population question. Different
    # denominator semantic. Left unchanged.
    fully_count_html = (
        _count_html(
            "ok" if fully_bit_perfect == total else "warn",
            "/ %s fully bit-perfect (both axes green)" % total,
            fully_bit_perfect,
        )
        if fully_bit_perfect is not None
        else ""
    )
    within_count_html = (
        _count_html("warn", "within tolerance (open cells)", within_tolerance)
        if within_tolerance is not None
        else ""
    )
    failed_count_html = (
        _count_html("fail", "diverged beyond tolerance", failed)
        if failed is not None
        else ""
    )
    under_count_html = (
        _count_html("warn", "rows under-exercised (< %d floats)" % threshold, derived_under)
        if derived_under > 0
        else ""
    )
    # Accuracy-axis top-level widgets (Mavdil's ebd0cb4 emitter):
    # MATCHED / IMPROVED / INACCURATE / UNMEASURED counts. Prefer json top-level;
    # fall back to derived from per-row.
    matched = data.get("matched")
    if matched is None and have_any_accuracy:
        matched = derived_matched
    improved = data.get("improved")
    if improved is None and have_any_accuracy:
        improved = derived_improved
    inaccurate = data.get("inaccurate")
    if inaccurate is None and have_any_accuracy:
        inaccurate = derived_inaccurate
    unmeasured = data.get("unmeasured")
    if unmeasured is None and have_any_accuracy:
        unmeasured = derived_unmeasured

    matched_count_html = (
        _count_html("ok", "matched (vs truth, entailed by bit-identity)", matched)
        if matched is not None and matched > 0 else ""
    )
    improved_count_html = (
        _count_html("improved", "IMPROVED vs truth (measured, better than stock)", improved)
        if improved is not None and improved > 0 else ""
    )
    inaccurate_count_html = (
        _count_html("fail", "INACCURATE vs truth (measured, worse than stock)", inaccurate)
        if inaccurate is not None and inaccurate > 0 else ""
    )
    unmeasured_count_html = (
        _count_html("unmeasured",
                     "UNMEASURED vs truth (no oracle checked yet; NOT worse-than-stock)",
                     unmeasured)
        if unmeasured is not None and unmeasured > 0 else ""
    )

    # Truth-axis group: build a group wrapper if any truth-axis widget has content.
    # (Mavdil 70056acf: two-axis partitions must not read as double-count. Group
    # by axis with title + colored border, so a reader immediately sees "these
    # are different views of the same rows" not "these are additive tallies.")
    truth_widgets = [w for w in [matched_count_html, improved_count_html,
                                  inaccurate_count_html, unmeasured_count_html] if w]
    if truth_widgets:
        truth_group_html = (
            '<div class="count-group axis-truth">'
            '<div class="count-group-title">vs truth (accuracy)</div>'
            '<div class="count-group-widgets">' + "".join(truth_widgets) + '</div>'
            '</div>'
        )
    else:
        truth_group_html = ""

    migration_widgets = [w for w in [migration_count_html, fully_count_html] if w]
    if migration_widgets:
        migration_group_html = (
            '<div class="count-group axis-migration">'
            '<div class="count-group-title">migration (swipl→swilgt)</div>'
            '<div class="count-group-widgets">' + "".join(migration_widgets) + '</div>'
            '</div>'
        )
    else:
        migration_group_html = ""

    # floats_compared top-level widget (Mavdil's ask 74c40611): surface the
    # total-population-actually-tested number in the headline area. Complements
    # the per-row total_floats: readers see BOTH per-kernel population AND
    # total population across the whole matrix. Absent = no widget (forward-
    # compat with older JSONs that don't carry this field).
    floats_compared = data.get("floats_compared")
    floats_compared_html = (
        _count_html("ok", "floats compared (population across all kernels)", _fmt_int(floats_compared))
        if floats_compared is not None
        else ""
    )

    # FRESHNESS STAMP (Iyun's proposal from mavchin's May-30 archaeology):
    # compute age from the JSON's `generated` timestamp vs now; render
    # inline with color-coded staleness. Staleness threshold overridable
    # via top-level `staleness_threshold_seconds` json field.
    staleness_threshold = data.get(
        "staleness_threshold_seconds", STALENESS_THRESHOLD_SECONDS
    )
    fresh_label, fresh_cls = _freshness(data.get("generated"), staleness_threshold)

    # BY-OP SECTION (Mavdil OP_MAPPING.md contract 6106eb0, mavhir C+(i)
    # implementation): three-state join view (both / runtime-only /
    # emitted-only). Renders empty string if OP_MAPPING.md can't be parsed
    # (dashboard degrades to just the runtime table — graceful fallback).
    by_op_section = _render_by_op_section(data)

    return PAGE.format(
        generated=html.escape(str(data.get("generated", "?"))),
        fresh_label=html.escape(fresh_label),
        fresh_cls=fresh_cls,
        pct=pct,
        bit_identical=bit_identical,
        total=total,
        open_count=open_count,
        headline_count_html=headline_count_html,
        bar_label=html.escape(bar_label),
        floats_compared_html=floats_compared_html,
        matched_count_html=matched_count_html,
        improved_count_html=improved_count_html,
        inaccurate_count_html=inaccurate_count_html,
        unmeasured_count_html=unmeasured_count_html,
        truth_group_html=truth_group_html,
        migration_group_html=migration_group_html,
        migration_count_html=migration_count_html,
        fully_count_html=fully_count_html,
        within_count_html=within_count_html,
        failed_count_html=failed_count_html,
        under_count_html=under_count_html,
        rows="\n".join(rows_html),
        by_op_section=by_op_section,
    )


class H(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path.rstrip("/") in ("", "/dashboard"):
            body = render().encode()
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        elif self.path == "/status.json":
            try:
                body = open(STATUS_FILE, "rb").read()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.end_headers()
                self.wfile.write(body)
            except Exception as e:
                self.send_response(500)
                self.end_headers()
                self.wfile.write(str(e).encode())
        else:
            self.send_response(404)
            self.end_headers()

    def log_message(self, *a):
        pass


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", type=int, default=8477)
    ap.add_argument("--status", default="congruence_status.json")
    a = ap.parse_args()
    STATUS_FILE = _resolve_status_file(a.status)
    print(
        "LlamaTov 0-ULP dashboard (two-axis, forward-compat) on :%d (status=%s)"
        % (a.port, STATUS_FILE)
    )
    ThreadingHTTPServer(("0.0.0.0", a.port), H).serve_forever()
