#!/usr/bin/env python3
"""congruence_dashboard.py — real-time 0-ULP congruence dashboard for LlamaTov.
Serves a live matrix of per-kernel bit-identity status against the oracle.
Reads congruence_status.json (produced by bit_identical_universal.py -> A2 model).
Refreshes on each page load; the JSON is regenerated by gate runs (C3 real-time).
Usage: python3 congruence_dashboard.py [--port 8477] [--status congruence_status.json]
"""
import json, os, argparse, html
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

STATUS_FILE = "congruence_status.json"

PAGE = """<!DOCTYPE html><html><head><meta charset="utf-8">
<title>LlamaTov · 0-ULP Congruence</title>
<meta http-equiv="refresh" content="10">
<style>
 body{{background:#0b0e14;color:#c9d1d9;font-family:'JetBrains Mono',ui-monospace,monospace;margin:0;padding:2rem}}
 h1{{color:#e6edf3;font-weight:600;font-size:1.4rem;margin:0 0 .3rem}}
 .sub{{color:#8b949e;margin-bottom:1.5rem;font-size:.85rem}}
 .bar{{height:34px;background:#161b22;border-radius:6px;overflow:hidden;margin:1rem 0;position:relative;border:1px solid #21262d}}
 .fill{{height:100%;background:linear-gradient(90deg,#238636,#2ea043);transition:width .6s}}
 .barlabel{{position:absolute;top:0;left:0;right:0;line-height:34px;text-align:center;font-weight:600;color:#fff;text-shadow:0 1px 2px #000}}
 table{{border-collapse:collapse;width:100%;margin-top:1rem}}
 th{{text-align:left;color:#8b949e;font-weight:500;padding:.4rem .8rem;border-bottom:1px solid #21262d;font-size:.8rem}}
 td{{padding:.35rem .8rem;border-bottom:1px solid #161b22;font-size:.85rem}}
 .ok{{color:#3fb950}} .warn{{color:#d29922}} .fail{{color:#f85149}}
 .dot{{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:.5rem}}
 .dot.ok{{background:#3fb950}} .dot.warn{{background:#d29922}} .dot.fail{{background:#f85149}}
 .ulp0{{color:#3fb950;font-weight:600}}
 .foot{{margin-top:2rem;color:#484f58;font-size:.75rem}}
 .k{{color:#79c0ff}}
</style></head><body>
<h1>🕯️ LlamaTov · Bit-Perfect Dispatch</h1>
<div class="sub">0-ULP congruence matrix — every kernel verified bit-identical against the oracle. Generated {generated} · auto-refresh 10s</div>
<div class="bar"><div class="fill" style="width:{pct}%"></div><div class="barlabel">{bit_identical} / {total} kernels 0-ULP bit-identical ({pct}%)</div></div>
<table><thead><tr><th></th><th>Kernel</th><th>Shape</th><th>Status</th><th>max ULP</th><th>Backend</th></tr></thead><tbody>
{rows}
</tbody></table>
<div class="foot">{passed}/{total} pass · {open_count} open cell(s) toward full 0-ULP congruence · LlamaTov / bpd-substrate</div>
</body></html>"""

def render():
    try:
        data = json.load(open(STATUS_FILE))
    except Exception as e:
        return "<html><body style='background:#0b0e14;color:#f85149;font-family:monospace;padding:2rem'>No congruence data yet: %s</body></html>" % html.escape(str(e))
    rows = []
    for k in data["kernels"]:
        bi = k["bit_identical"]
        cls = "ok" if bi else ("warn" if k["status"].startswith("PASS") else "fail")
        ulp = '<span class="ulp0">0</span>' if k["max_ulp"] == 0 else str(k["max_ulp"])
        rows.append('<tr><td><span class="dot {c}"></span></td><td class="k">{n}</td><td>{s}</td><td class="{c}">{st}</td><td>{u}</td><td>{b}</td></tr>'.format(
            c=cls, n=html.escape(k["kernel"]), s=html.escape(k["shape"]), st=html.escape(k["status"]), u=ulp, b=k.get("backend","-")))
    total = data["total"]; bi = data["bit_identical"]
    pct = round(100*bi/total) if total else 0
    return PAGE.format(generated=data.get("generated","?"), pct=pct, bit_identical=bi, total=total,
                       passed=data.get("passed",total), open_count=total-bi, rows="\n".join(rows))

class H(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path.rstrip("/") in ("", "/dashboard"):
            body = render().encode()
            self.send_response(200); self.send_header("Content-Type","text/html; charset=utf-8")
            self.send_header("Content-Length",str(len(body))); self.end_headers(); self.wfile.write(body)
        elif self.path == "/status.json":
            body = open(STATUS_FILE,"rb").read()
            self.send_response(200); self.send_header("Content-Type","application/json"); self.end_headers(); self.wfile.write(body)
        else:
            self.send_response(404); self.end_headers()
    def log_message(self,*a): pass

if __name__ == "__main__":
    ap = argparse.ArgumentParser(); ap.add_argument("--port",type=int,default=8477); ap.add_argument("--status",default="congruence_status.json")
    a = ap.parse_args(); STATUS_FILE = a.status
    print("LlamaTov 0-ULP dashboard on :%d (status=%s)" % (a.port, STATUS_FILE))
    ThreadingHTTPServer(("0.0.0.0", a.port), H).serve_forever()
