%% gelu_ondnn_emitter.pl — Generate VECTORIZED LLVM IR matching oneDNN's JIT.
%%
%% Uses <8 x float> vector types (AVX-256) to match the JIT's ymm operations.
%% LLVM has much less freedom to reorder vector operations, so the f32
%% evaluation order matches the JIT binary.
%%
%% Author: mavchin (2026-06-01)

:- module(gelu_ondnn_emitter, [emit_gelu_ir/1]).

:- use_module(llvm_emit).

emit_gelu_ir(OutFile) :-
    open(OutFile, write, S),
    emit_header(S, "x86_64-unknown-linux-gnu"),
    format(S, '; GELU matching oneDNN JIT — vectorized <8 x float> AVX operations~n', []),
    format(S, '; Generated by gelu_ondnn_emitter.pl~n~n', []),
    %% Intrinsic declares
    format(S, 'declare <8 x float> @llvm.floor.v8f32(<8 x float>)~n', []),
    format(S, 'declare <8 x float> @llvm.minnum.v8f32(<8 x float>, <8 x float>)~n', []),
    format(S, 'declare <8 x float> @llvm.maxnum.v8f32(<8 x float>, <8 x float>)~n', []),
    format(S, 'declare float @erff(float)~n', []),
    format(S, '~n', []),
    emit_gelu_vector(S),
    emit_gelu_entry(S),
    close(S),
    format("Emitted vectorized GELU IR to ~w~n", [OutFile]).

%% ============================================================
%% Helper: broadcast a float constant to <8 x float>
%% ============================================================

emit_splat(S, Name, HexVal) :-
    format(S, '  %~w = insertelement <8 x float> undef, float ~w, i32 0~n', [Name, HexVal]),
    format(atom(Bcast), '~w_bc', [Name]),
    format(S, '  %~w = shufflevector <8 x float> %~w, <8 x float> undef, <8 x i32> zeroinitializer~n', [Bcast, Name]).

%% Return the broadcast name
splat_name(Name, Bcast) :-
    format(atom(Bcast), '~w_bc', [Name]).

%% ============================================================
%% Vectorized GELU: processes 8 floats at a time
%% ============================================================

emit_gelu_vector(S) :-
    format(S, '; Process 8 floats matching JIT ymm register operations~n', []),
    format(S, 'define void @gelu_ondnn_vec8(ptr %in, ptr %out) #0 {~n', []),
    format(S, 'entry:~n', []),
    %% Load 8 floats
    format(S, '  %x = load <8 x float>, ptr %in, align 4~n', []),
    format(S, '~n', []),
    %% Broadcast all constants
    format(S, '  ; --- broadcast constants ---~n', []),
    %% CORRECTED f64 hex for exact f32 constants (f32 widened to f64)
    emit_splat(S, c_sqrt2inv, '0x3FE6A09E60000000'),   % 0.7071067691
    emit_splat(S, c_half,     '0x3FE0000000000000'),   % 0.5
    emit_splat(S, c_one,      '0x3FF0000000000000'),   % 1.0
    emit_splat(S, c_two,      '0x4000000000000000'),   % 2.0
    emit_splat(S, c_erf_p,    '0x3FD4F740A0000000'),   % 0.3275910914
    emit_splat(S, c_erf_a1,   '0x3FD04F20C0000000'),   % 0.2548295856
    emit_splat(S, c_erf_a2,   '0xBFD23531C0000000'),   % -0.2844967246
    emit_splat(S, c_erf_a3,   '0x3FF6BE1C60000000'),   % 1.4214137793
    emit_splat(S, c_erf_a4,   '0xBFF7401C60000000'),   % -1.4531520605
    emit_splat(S, c_erf_a5,   '0x3FF0FB8440000000'),   % 1.0614054203
    emit_splat(S, c_log2e,    '0x3FF7154760000000'),   % 1.4426950216
    emit_splat(S, c_ln2,      '0x3FE62E4300000000'),   % 0.6931471825
    emit_splat(S, c_exp_c1,   '0x3FEFFFFF60000000'),   % 0.9999997020
    emit_splat(S, c_exp_c2,   '0x3FDFFFDC60000000'),   % 0.4999915063
    emit_splat(S, c_exp_c3,   '0x3FC555A800000000'),   % 0.1666765213
    emit_splat(S, c_exp_c4,   '0x3FA573A1A0000000'),   % 0.0418978222
    emit_splat(S, c_exp_c5,   '0x3F80F9F9C0000000'),   % 0.0082892906
    emit_splat(S, c_exp_hi,   '0x40562E4300000000'),   % 88.7228393555
    emit_splat(S, c_exp_lo,   '0xC055D58A00000000'),   % -87.3365478516
    %% Sign/abs masks
    format(S, '  %sign_mask = bitcast <8 x i32> <i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648> to <8 x float>~n', []),
    format(S, '  %abs_mask = bitcast <8 x i32> <i32 2147483647, i32 2147483647, i32 2147483647, i32 2147483647, i32 2147483647, i32 2147483647, i32 2147483647, i32 2147483647> to <8 x float>~n', []),
    format(S, '~n', []),
    %% === JIT offset 0x40: v = x * sqrt2_inv ===
    format(S, '  ; --- JIT 0x40: v = x * sqrt2_inv ---~n', []),
    format(S, '  %v = fmul <8 x float> %x, %c_sqrt2inv_bc~n', []),
    %% |v| and sign(v) — JIT 0x49-0x4d
    format(S, '  %av = call <8 x float> @llvm.maxnum.v8f32(<8 x float> %v, <8 x float> %v)~n', []),
    format(S, '  %av2 = bitcast <8 x float> %v to <8 x i32>~n', []),
    format(S, '  %abs_i = and <8 x i32> %av2, <i32 2147483647, i32 2147483647, i32 2147483647, i32 2147483647, i32 2147483647, i32 2147483647, i32 2147483647, i32 2147483647>~n', []),
    format(S, '  %av_clean = bitcast <8 x i32> %abs_i to <8 x float>~n', []),
    format(S, '  %sign_i = and <8 x i32> %av2, <i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648>~n', []),
    format(S, '  %v_sign = bitcast <8 x i32> %sign_i to <8 x float>~n', []),
    format(S, '~n', []),
    %% === JIT 0x56-0x75: t = 1/(1+p*|v|) ===
    format(S, '  ; --- JIT 0x56-0x75: t = 1/(1+p*|v|) ---~n', []),
    format(S, '  %pav = fmul <8 x float> %c_erf_p_bc, %av_clean~n', []),
    format(S, '  %denom = fadd <8 x float> %pav, %c_one_bc~n', []),
    format(S, '  %t = fdiv <8 x float> %c_one_bc, %denom~n', []),
    format(S, '~n', []),
    %% === JIT 0x79-0x7d: -v² ===
    format(S, '  ; --- JIT 0x79-0x7d: -v² ---~n', []),
    format(S, '  %v2 = fmul <8 x float> %v, %v~n', []),
    format(S, '  %v2_i = bitcast <8 x float> %v2 to <8 x i32>~n', []),
    format(S, '  %neg_v2_i = xor <8 x i32> %v2_i, <i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648>~n', []),
    format(S, '  %neg_v2 = bitcast <8 x i32> %neg_v2_i to <8 x float>~n', []),
    format(S, '~n', []),
    %% === EXP: JIT 0x94-0x170 ===
    format(S, '  ; --- EXP: JIT 0x94-0x170 ---~n', []),
    format(S, '  %xc1 = call <8 x float> @llvm.minnum.v8f32(<8 x float> %neg_v2, <8 x float> %c_exp_hi_bc)~n', []),
    format(S, '  %xc = call <8 x float> @llvm.maxnum.v8f32(<8 x float> %xc1, <8 x float> %c_exp_lo_bc)~n', []),
    format(S, '  %xlog2e = fmul <8 x float> %xc, %c_log2e_bc~n', []),
    format(S, '  %z = fadd <8 x float> %xlog2e, %c_half_bc~n', []),
    format(S, '  %n = call <8 x float> @llvm.floor.v8f32(<8 x float> %z)~n', []),
    format(S, '  %nln2 = fmul <8 x float> %n, %c_ln2_bc~n', []),
    format(S, '  %f = fsub <8 x float> %xc, %nln2~n', []),
    format(S, '  %n_adj = fsub <8 x float> %n, %c_one_bc~n', []),
    %% Horner for exp poly
    format(S, '  %ep0 = fmul <8 x float> %c_exp_c5_bc, %f~n', []),
    format(S, '  %ep1 = fadd <8 x float> %ep0, %c_exp_c4_bc~n', []),
    format(S, '  %ep2 = fmul <8 x float> %ep1, %f~n', []),
    format(S, '  %ep3 = fadd <8 x float> %ep2, %c_exp_c3_bc~n', []),
    format(S, '  %ep4 = fmul <8 x float> %ep3, %f~n', []),
    format(S, '  %ep5 = fadd <8 x float> %ep4, %c_exp_c2_bc~n', []),
    format(S, '  %ep6 = fmul <8 x float> %ep5, %f~n', []),
    format(S, '  %ep7 = fadd <8 x float> %ep6, %c_exp_c1_bc~n', []),
    format(S, '  %ep8 = fmul <8 x float> %ep7, %f~n', []),
    format(S, '  %poly = fadd <8 x float> %ep8, %c_one_bc~n', []),
    %% 2^n_adj
    format(S, '  %ni = fptosi <8 x float> %n_adj to <8 x i32>~n', []),
    format(S, '  %biased = add <8 x i32> %ni, <i32 127, i32 127, i32 127, i32 127, i32 127, i32 127, i32 127, i32 127>~n', []),
    format(S, '  %shifted = shl <8 x i32> %biased, <i32 23, i32 23, i32 23, i32 23, i32 23, i32 23, i32 23, i32 23>~n', []),
    format(S, '  %scale = bitcast <8 x i32> %shifted to <8 x float>~n', []),
    format(S, '  %ps = fmul <8 x float> %poly, %scale~n', []),
    format(S, '  %exp_val = fmul <8 x float> %ps, %c_two_bc~n', []),
    format(S, '~n', []),
    %% === ERF: JIT 0x186-0x1cb ===
    format(S, '  ; --- ERF: JIT 0x170-0x1cb ---~n', []),
    %% JIT 0x170: negate exp FIRST (xor with sign mask)
    format(S, '  %exp_i = bitcast <8 x float> %exp_val to <8 x i32>~n', []),
    format(S, '  %neg_exp_i = xor <8 x i32> %exp_i, <i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648>~n', []),
    format(S, '  %neg_exp = bitcast <8 x i32> %neg_exp_i to <8 x float>~n', []),
    %% JIT 0x186: (-exp) * t
    format(S, '  %et = fmul <8 x float> %neg_exp, %t~n', []),
    format(S, '  %h0 = fmul <8 x float> %c_erf_a5_bc, %t~n', []),
    format(S, '  %h1 = fadd <8 x float> %h0, %c_erf_a4_bc~n', []),
    format(S, '  %h2 = fmul <8 x float> %h1, %t~n', []),
    format(S, '  %h3 = fadd <8 x float> %h2, %c_erf_a3_bc~n', []),
    format(S, '  %h4 = fmul <8 x float> %h3, %t~n', []),
    format(S, '  %h5 = fadd <8 x float> %h4, %c_erf_a2_bc~n', []),
    format(S, '  %h6 = fmul <8 x float> %h5, %t~n', []),
    format(S, '  %h7 = fadd <8 x float> %h6, %c_erf_a1_bc~n', []),
    format(S, '  %eth = fmul <8 x float> %et, %h7~n', []),
    %% eth is negative (since exp was negated), so eth + 1 = 1 - |exp*t*h| = erf_abs
    format(S, '  %erf_abs = fadd <8 x float> %eth, %c_one_bc~n', []),
    format(S, '~n', []),
    %% === SIGN + GELU ===
    format(S, '  ; --- JIT 0x179-0x1e5: sign + gelu assembly ---~n', []),
    %% JIT 0x179-0x17d: extract sign of ORIGINAL x (not v)
    format(S, '  %x_i = bitcast <8 x float> %x to <8 x i32>~n', []),
    format(S, '  %x_sign_i = and <8 x i32> %x_i, <i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648>~n', []),
    %% JIT 0x1d4: XOR erf_abs with sign of x
    format(S, '  %erf_abs_i = bitcast <8 x float> %erf_abs to <8 x i32>~n', []),
    format(S, '  %erf_signed_i = xor <8 x i32> %erf_abs_i, %x_sign_i~n', []),
    format(S, '  %erf_signed = bitcast <8 x i32> %erf_signed_i to <8 x float>~n', []),
    %% JIT 0x1d8: x_half = x * 0.5
    format(S, '  %x_half = fmul <8 x float> %x, %c_half_bc~n', []),
    %% JIT 0x1e1: prod = erf_signed * x_half
    format(S, '  %prod = fmul <8 x float> %erf_signed, %x_half~n', []),
    %% JIT 0x1e5: result = prod + x_half
    format(S, '  %result = fadd <8 x float> %prod, %x_half~n', []),
    format(S, '~n', []),
    format(S, '  store <8 x float> %result, ptr %out, align 4~n', []),
    format(S, '  ret void~n', []),
    format(S, '}~n~n', []),
    format(S, 'attributes #0 = { "target-features"="+avx" }~n~n', []).

%% ============================================================
%% Entry point: loop + scalar tail
%% ============================================================

emit_gelu_entry(S) :-
    format(S, 'define void @bpd_gelu_ondnn_cpu(ptr %input, ptr %output, i32 %n) {~n', []),
    format(S, 'entry:~n', []),
    format(S, '  br label %check~n~n', []),
    format(S, 'check:~n', []),
    format(S, '  %i = phi i32 [ 0, %entry ], [ %i8, %vec_body ]~n', []),
    format(S, '  %remaining = sub i32 %n, %i~n', []),
    format(S, '  %can_vec = icmp sge i32 %remaining, 8~n', []),
    format(S, '  br i1 %can_vec, label %vec_body, label %scalar_check~n~n', []),
    format(S, 'vec_body:~n', []),
    format(S, '  %in_ptr = getelementptr float, ptr %input, i32 %i~n', []),
    format(S, '  %out_ptr = getelementptr float, ptr %output, i32 %i~n', []),
    format(S, '  call void @gelu_ondnn_vec8(ptr %in_ptr, ptr %out_ptr)~n', []),
    format(S, '  %i8 = add i32 %i, 8~n', []),
    format(S, '  br label %check~n~n', []),
    %% Scalar tail using erff
    format(S, 'scalar_check:~n', []),
    format(S, '  %j = phi i32 [ %i, %check ], [ %j_next, %scalar_body ]~n', []),
    format(S, '  %scalar_done = icmp sge i32 %j, %n~n', []),
    format(S, '  br i1 %scalar_done, label %done, label %scalar_body~n~n', []),
    format(S, 'scalar_body:~n', []),
    format(S, '  %sin_ptr = getelementptr float, ptr %input, i32 %j~n', []),
    format(S, '  %sx = load float, ptr %sin_ptr~n', []),
    format(S, '  %sv = fmul float %sx, 0x3FE6A09E60000000~n', []),  % sqrt2_inv
    format(S, '  %serf = call float @erff(float %sv)~n', []),
    format(S, '  %sone_plus = fadd float 1.0, %serf~n', []),
    format(S, '  %stimes = fmul float %sx, %sone_plus~n', []),
    format(S, '  %sresult = fmul float %stimes, 0.5~n', []),
    format(S, '  %sout_ptr = getelementptr float, ptr %output, i32 %j~n', []),
    format(S, '  store float %sresult, ptr %sout_ptr~n', []),
    format(S, '  %j_next = add i32 %j, 1~n', []),
    format(S, '  br label %scalar_check~n~n', []),
    format(S, 'done:~n', []),
    format(S, '  ret void~n', []),
    format(S, '}~n', []).
