%% ggml_cuda_bridge_emitter.pl — Emit LLVM IR to call ggml-CUDA from Prolog.
%%
%% Generates FLI predicates that:
%%   1. Initialize the CUDA backend (once)
%%   2. Create ggml tensors (Q8_0 weights, f32 input)
%%   3. Build a single-op compute graph
%%   4. Dispatch via ggml_backend_graph_compute (launches REAL GPU kernel)
%%   5. Return timing + results to Prolog
%%
%% Combined with the existing CUPTI predicates in full_bridge.so:
%%   cupti_start_profiling → ggml_matmul(...) → cupti_flush → cupti_stall_report
%%
%% This is the SAME pattern as nvml_bridge_v2.pl:
%%   Prolog facts → LLVM IR → llc → .so → SWI-PL FLI
%%
%% Author: mavchin (2026-06-03)

:- module(ggml_cuda_bridge_emitter, [emit_ggml_cuda_bridge/1]).

%% ============================================================
%% Bridge specification as Prolog facts
%% ============================================================

%% External ggml functions we need to call
ggml_extern(ggml_init, ptr, ['ptr noundef nonnull byval({i64, ptr, i8}) align 8']). % struct by value!
ggml_extern(ggml_free, void, [ptr]).                   % ggml_free(ctx)
ggml_extern(ggml_new_tensor_2d, ptr, [ptr,i32,i64,i64]). % (ctx, type, ne0, ne1)
ggml_extern(ggml_mul_mat, ptr, [ptr,ptr,ptr]).         % (ctx, a, b) -> c
ggml_extern(ggml_new_graph, ptr, [ptr]).               % (ctx) -> graph
ggml_extern(ggml_build_forward_expand, void, [ptr,ptr]). % (graph, tensor)
ggml_extern(ggml_nbytes, i64, [ptr]).                  % (tensor) -> bytes
ggml_extern(ggml_backend_cuda_init, ptr, [i32]).       % (device) -> backend
ggml_extern(ggml_backend_free, void, [ptr]).           % (backend)
ggml_extern(ggml_backend_alloc_ctx_tensors, ptr, [ptr,ptr]). % (ctx, backend) -> buf
ggml_extern(ggml_backend_buffer_free, void, [ptr]).    % (buf)
ggml_extern(ggml_backend_tensor_set, void, [ptr,ptr,i64,i64]). % (tensor, data, off, size)
ggml_extern(ggml_backend_graph_compute, i32, [ptr,ptr]). % (backend, graph) -> status

%% CUDA timing functions
cuda_extern(cudaDeviceSynchronize, i32, []).
cuda_extern(cudaEventCreate, i32, [ptr]).
cuda_extern(cudaEventRecord, i32, [ptr]).
cuda_extern(cudaEventSynchronize, i32, [ptr]).
cuda_extern(cudaEventElapsedTime, i32, [ptr,ptr,ptr]).
cuda_extern(cudaEventDestroy, i32, [ptr]).

%% ============================================================
%% Emitter
%% ============================================================

emit_ggml_cuda_bridge(OutFile) :-
    open(OutFile, write, S),
    format(S, '; ggml-CUDA bridge for SWI-Prolog~n', []),
    format(S, '; Generated by ggml_cuda_bridge_emitter.pl~n', []),
    format(S, '; Launches REAL ggml GPU kernels from Prolog predicates~n~n', []),
    
    %% Declare external functions
    emit_declares(S),
    
    %% Emit the SWI-PL FLI includes
    emit_fli_includes(S),
    
    %% Global state (initialized once)
    emit_globals(S),
    
    %% The init predicate
    emit_init_predicate(S),
    
    %% The matmul predicate: ggml_matmul_q8_0(M, K, N, Ms)
    emit_matmul_predicate(S),
    
    %% The cleanup predicate
    emit_cleanup_predicate(S),
    
    %% Install predicates
    emit_install(S),
    
    close(S),
    format("Emitted ggml-CUDA bridge to ~w~n", [OutFile]).

%% ============================================================
%% Emit external declarations
%% ============================================================

emit_declares(S) :-
    format(S, '; External ggml functions~n', []),
    forall(ggml_extern(Name, Ret, Args),
        (   format_args(Args, ArgsStr),
            format(S, 'declare ~w @~w(~w)~n', [Ret, Name, ArgsStr])
        )),
    format(S, '~n; CUDA functions~n', []),
    forall(cuda_extern(Name, Ret, Args),
        (   format_args(Args, ArgsStr),
            format(S, 'declare ~w @~w(~w)~n', [Ret, Name, ArgsStr])
        )),
    format(S, '~n; C stdlib~n', []),
    format(S, 'declare ptr @malloc(i64)~n', []),
    format(S, 'declare ptr @aligned_alloc(i64, i64)~n', []),
    format(S, 'declare ptr @memset(ptr, i32, i64)~n', []),
    format(S, 'declare void @free(ptr)~n~n', []).

format_args([], '').
format_args([T], S) :- atom_string(T, S).
format_args([T|Ts], S) :- 
    Ts \= [],
    atom_string(T, TS),
    format_args(Ts, Rest),
    format(string(S), "~w, ~w", [TS, Rest]).

%% ============================================================
%% FLI type declarations
%% ============================================================

emit_fli_includes(S) :-
    format(S, '; SWI-Prolog FLI types~n', []),
    format(S, '%struct.PL_term_ref = type opaque~n', []),
    format(S, 'declare i32 @PL_get_integer(i64, ptr)~n', []),
    format(S, 'declare i32 @PL_unify_float(i64, double)~n', []),
    format(S, 'declare i64 @PL_new_term_ref()~n', []),
    format(S, 'declare i32 @PL_get_arg(i32, i64, i64)~n', []),
    format(S, 'declare i32 @PL_register_foreign(ptr, i32, ptr, i32)~n~n', []).

%% ============================================================
%% Global state
%% ============================================================

emit_globals(S) :-
    format(S, '; Global state (lazy-initialized)~n', []),
    format(S, '@g_cuda_backend = global ptr null~n', []),
    format(S, '@g_initialized = global i1 false~n~n', []).

%% ============================================================
%% Init predicate: ggml_cuda_init
%% ============================================================

emit_init_predicate(S) :-
    format(S, '; ggml_cuda_bridge_init/0 — initialize CUDA backend~n', []),
    format(S, 'define i32 @pl_cuda_init(i64 %t0, i32 %arity, ptr %control) {~n', []),
    format(S, 'entry:~n', []),
    format(S, '  %already = load i1, ptr @g_initialized~n', []),
    format(S, '  br i1 %already, label %done, label %do_init~n', []),
    format(S, 'do_init:~n', []),
    format(S, '  %backend = call ptr @ggml_backend_cuda_init(i32 0)~n', []),
    format(S, '  store ptr %backend, ptr @g_cuda_backend~n', []),
    format(S, '  store i1 true, ptr @g_initialized~n', []),
    format(S, '  br label %done~n', []),
    format(S, 'done:~n', []),
    format(S, '  ret i32 1~n', []),
    format(S, '}~n~n', []).

%% ============================================================
%% Matmul predicate: ggml_matmul_q8_0(+M, +K, +N, -TimeMs)
%% ============================================================

emit_matmul_predicate(S) :-
    format(S, '; ggml_matmul_q8_0(M, K, N, TimeMs) — dispatch one matmul on GPU~n', []),
    format(S, '; Returns wall time in milliseconds~n', []),
    format(S, 'define i32 @pl_matmul_q8_0(i64 %t0, i32 %arity, ptr %control) {~n', []),
    format(S, 'entry:~n', []),
    %% Get integer arguments M, K, N
    format(S, '  %m_ptr = alloca i32~n', []),
    format(S, '  %k_ptr = alloca i32~n', []),
    format(S, '  %n_ptr = alloca i32~n', []),
    format(S, '  %t1 = add i64 %t0, 1~n', []),
    format(S, '  %t2 = add i64 %t0, 2~n', []),
    format(S, '  %t3 = add i64 %t0, 3~n', []),
    format(S, '  call i32 @PL_get_integer(i64 %t0, ptr %m_ptr)~n', []),
    format(S, '  call i32 @PL_get_integer(i64 %t1, ptr %k_ptr)~n', []),
    format(S, '  call i32 @PL_get_integer(i64 %t2, ptr %n_ptr)~n', []),
    format(S, '  %M = load i32, ptr %m_ptr~n', []),
    format(S, '  %K = load i32, ptr %k_ptr~n', []),
    format(S, '  %N = load i32, ptr %n_ptr~n', []),
    format(S, '  %M64 = sext i32 %M to i64~n', []),
    format(S, '  %K64 = sext i32 %K to i64~n', []),
    format(S, '  %N64 = sext i32 %N to i64~n', []),
    format(S, '~n', []),
    %% Create ggml context — struct passed via byval (clang's pattern)
    format(S, '  ; Create ggml context (16MB, no_alloc=true)~n', []),
    format(S, '  %params = alloca { i64, ptr, i8 }, align 8~n', []),
    format(S, '  %raw_buf = call ptr @aligned_alloc(i64 64, i64 16777216)~n', []),
    format(S, '  store i64 16777216, ptr %params, align 8~n', []),
    format(S, '  %p_membuf = getelementptr inbounds i8, ptr %params, i64 8~n', []),
    format(S, '  store ptr %raw_buf, ptr %p_membuf, align 8~n', []),
    format(S, '  %p_noalloc = getelementptr inbounds i8, ptr %params, i64 16~n', []),
    format(S, '  store i8 1, ptr %p_noalloc, align 8~n', []),
    format(S, '  %ctx = call ptr @ggml_init(ptr noundef nonnull byval({i64, ptr, i8}) align 8 %params)~n', []),
    format(S, '~n', []),
    %% Create tensors
    format(S, '  ; Create Q8_0 weight [K, M] and F32 input [K, N]~n', []),
    format(S, '  %a = call ptr @ggml_new_tensor_2d(ptr %ctx, i32 8, i64 %K64, i64 %M64)~n', []),
    format(S, '  %b = call ptr @ggml_new_tensor_2d(ptr %ctx, i32 0, i64 %K64, i64 %N64)~n', []),
    format(S, '  %c = call ptr @ggml_mul_mat(ptr %ctx, ptr %a, ptr %b)~n', []),
    format(S, '~n', []),
    %% Allocate on GPU
    format(S, '  %backend = load ptr, ptr @g_cuda_backend~n', []),
    format(S, '  %buf = call ptr @ggml_backend_alloc_ctx_tensors(ptr %ctx, ptr %backend)~n', []),
    format(S, '~n', []),
    %% Fill with data
    format(S, '  ; Fill tensors with test data~n', []),
    format(S, '  %a_sz = call i64 @ggml_nbytes(ptr %a)~n', []),
    format(S, '  %b_sz = call i64 @ggml_nbytes(ptr %b)~n', []),
    format(S, '  %h_a = call ptr @malloc(i64 %a_sz)~n', []),
    format(S, '  %h_b = call ptr @malloc(i64 %b_sz)~n', []),
    format(S, '  call ptr @memset(ptr %h_a, i32 66, i64 %a_sz)~n', []),
    format(S, '  call ptr @memset(ptr %h_b, i32 0, i64 %b_sz)~n', []),
    format(S, '  call void @ggml_backend_tensor_set(ptr %a, ptr %h_a, i64 0, i64 %a_sz)~n', []),
    format(S, '  call void @ggml_backend_tensor_set(ptr %b, ptr %h_b, i64 0, i64 %b_sz)~n', []),
    format(S, '~n', []),
    %% Build graph + compute
    format(S, '  ; Build graph and compute~n', []),
    format(S, '  %graph = call ptr @ggml_new_graph(ptr %ctx)~n', []),
    format(S, '  call void @ggml_build_forward_expand(ptr %graph, ptr %c)~n', []),
    format(S, '  call i32 @ggml_backend_graph_compute(ptr %backend, ptr %graph)~n', []),
    format(S, '  call i32 @cudaDeviceSynchronize()~n', []),
    format(S, '~n', []),
    %% Time it
    format(S, '  ; Time n iterations~n', []),
    format(S, '  %ev_start = alloca ptr~n', []),
    format(S, '  %ev_stop = alloca ptr~n', []),
    format(S, '  %ms_ptr = alloca float~n', []),
    format(S, '  call i32 @cudaEventCreate(ptr %ev_start)~n', []),
    format(S, '  call i32 @cudaEventCreate(ptr %ev_stop)~n', []),
    format(S, '  %estart = load ptr, ptr %ev_start~n', []),
    format(S, '  %estop = load ptr, ptr %ev_stop~n', []),
    format(S, '  call i32 @cudaEventRecord(ptr %estart)~n', []),
    format(S, '  call i32 @ggml_backend_graph_compute(ptr %backend, ptr %graph)~n', []),
    format(S, '  call i32 @cudaEventRecord(ptr %estop)~n', []),
    format(S, '  call i32 @cudaEventSynchronize(ptr %estop)~n', []),
    format(S, '  call i32 @cudaEventElapsedTime(ptr %ms_ptr, ptr %estart, ptr %estop)~n', []),
    format(S, '  %ms_f32 = load float, ptr %ms_ptr~n', []),
    format(S, '  %ms_f64 = fpext float %ms_f32 to double~n', []),
    format(S, '~n', []),
    %% Unify result
    format(S, '  ; Return time to Prolog~n', []),
    format(S, '  call i32 @PL_unify_float(i64 %t3, double %ms_f64)~n', []),
    format(S, '~n', []),
    %% Cleanup
    format(S, '  call void @free(ptr %h_a)~n', []),
    format(S, '  call void @free(ptr %h_b)~n', []),
    format(S, '  call i32 @cudaEventDestroy(ptr %estart)~n', []),
    format(S, '  call i32 @cudaEventDestroy(ptr %estop)~n', []),
    format(S, '  call void @ggml_backend_buffer_free(ptr %buf)~n', []),
    format(S, '  call void @ggml_free(ptr %ctx)~n', []),
    format(S, '  ret i32 1~n', []),
    format(S, '}~n~n', []).

%% ============================================================
%% Cleanup predicate
%% ============================================================

emit_cleanup_predicate(S) :-
    format(S, 'define i32 @pl_cuda_cleanup(i64 %t0, i32 %arity, ptr %control) {~n', []),
    format(S, '  %backend = load ptr, ptr @g_cuda_backend~n', []),
    format(S, '  call void @ggml_backend_free(ptr %backend)~n', []),
    format(S, '  store ptr null, ptr @g_cuda_backend~n', []),
    format(S, '  store i1 false, ptr @g_initialized~n', []),
    format(S, '  ret i32 1~n', []),
    format(S, '}~n~n', []).

%% ============================================================
%% Install predicates (called by SWI-PL on load)
%% ============================================================

emit_install(S) :-
    format(S, '@.str_init = private constant [15 x i8] c"ggml_cuda_init\\00"~n', []),
    format(S, '@.str_matmul = private constant [17 x i8] c"ggml_matmul_q8_0\\00"~n', []),
    format(S, '@.str_cleanup = private constant [18 x i8] c"ggml_cuda_cleanup\\00"~n', []),
    format(S, '~n', []),
    format(S, 'define void @install() {~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @.str_init, i32 0, ptr @pl_cuda_init, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @.str_matmul, i32 4, ptr @pl_matmul_q8_0, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @.str_cleanup, i32 0, ptr @pl_cuda_cleanup, i32 0)~n', []),
    format(S, '  ret void~n', []),
    format(S, '}~n', []).
