%% nvml_bridge_v2.pl — NVML bridge using declarative llvm_emit infrastructure.
%%
%% The bridge specification is FACTS. The emission is RULES from llvm_emit.pl.
%% Compare to nvml_bridge_emitter.pl where everything was format strings.
%%
%% Usage:
%%   swipl -g 'emit_bridge("nvml_bridge.ll"), halt' nvml_bridge_v2.pl
%%   llc -relocation-model=pic -filetype=obj nvml_bridge.ll -o nvml_bridge.o
%%   gcc -shared -o nvml_bridge.so nvml_bridge.o -ldl
%%
%% Author: mavchin (2026-06-01)

:- module(nvml_bridge_v2, [emit_bridge/1]).

:- use_module(llvm_emit).

%% ============================================================
%% Bridge specification — PURE FACTS
%% ============================================================

%% The library we bridge to
bridge_library('libnvidia-ml.so.1').

%% NVML functions we need (resolved via dlsym at runtime)
%% nvml_func(PrologName, NvmlSymbol, RetType, ArgTypes, FnPtrGlobal)
nvml_func(init,       'nvmlInit_v2',                         i32, [],                fn_init).
nvml_func(shutdown,   'nvmlShutdown',                        i32, [],                fn_shutdown).
nvml_func(gethandle,  'nvmlDeviceGetHandleByIndex_v2',       i32, [i32, ptr],         fn_gethandle).
nvml_func(getname,    'nvmlDeviceGetName',                   i32, [ptr, ptr, i32],    fn_getname).
nvml_func(gettemp,    'nvmlDeviceGetTemperature',            i32, [ptr, i32, ptr],    fn_gettemp).
nvml_func(getpower,   'nvmlDeviceGetPowerUsage',             i32, [ptr, ptr],         fn_getpower).
nvml_func(getclock,   'nvmlDeviceGetClockInfo',              i32, [ptr, i32, ptr],    fn_getclock).
nvml_func(getmeminfo, 'nvmlDeviceGetMemoryInfo',             i32, [ptr, ptr],         fn_getmeminfo).
nvml_func(getutil,    'nvmlDeviceGetUtilizationRates',       i32, [ptr, ptr],         fn_getutil).
nvml_func(getpciegen, 'nvmlDeviceGetCurrPcieLinkGeneration', i32, [ptr, ptr],         fn_getpciegen).
nvml_func(getpciewid, 'nvmlDeviceGetCurrPcieLinkWidth',      i32, [ptr, ptr],         fn_getpciewid).

%% Prolog predicates exposed by this bridge
%% plf_pred(PrologName, Arity, ImplFunction)
%% Derived automatically from plf_impl/2:
plf_pred(Name, Arity, ImplFunc) :-
    plf_impl(Name, Shape),
    shape_arity(Shape, Arity),
    format(atom(ImplFunc), 'pl_~w', [Name]).

%% Shape → arity mapping
shape_arity(read_one_i32(_, _), 1).
shape_arity(read_two_i32(_, _, _, _), 2).
shape_arity(read_struct_2xi32(_), 2).
shape_arity(read_struct_3xi64_as_mb(_), 3).
shape_arity(read_string(_, _), 1).

%% ============================================================
%% Predicate implementations — PURE DECLARATIONS
%% ============================================================
%%
%% Each plf_impl/2 maps a Prolog predicate name to its shape:
%%   read_one_i32(FnPtr, ExtraArgs)       — call fn(dev, extras..., &val), unify val
%%   read_two_i32(Fn1, Ex1, Fn2, Ex2)     — two i32 reads, unify both
%%   read_struct_2xi32(FnPtr)             — call fn(dev, &struct{i32,i32}), unify both
%%   read_struct_3xi64_as_mb(FnPtr)       — call fn(dev, &struct{i64,i64,i64}), div by 1MB, unify three
%%   read_string(FnPtr, ExtraArgs)        — call fn(dev, buf, extras...), unify as atom
%%
%% The LLVM IR emission is generated by shape-dispatch rules below.

plf_impl(gpu_temperature, read_one_i32(fn_gettemp, [i32(0)])).
plf_impl(gpu_power,       read_one_i32(fn_getpower, [])).
plf_impl(gpu_clock,       read_two_i32(fn_getclock, [i32(0)], fn_getclock, [i32(1)])).
plf_impl(gpu_pcie,        read_two_i32(fn_getpciegen, [], fn_getpciewid, [])).
plf_impl(gpu_name,        read_string(fn_getname, [i32(256)])).
plf_impl(gpu_memory,      read_struct_3xi64_as_mb(fn_getmeminfo)).
plf_impl(gpu_utilization,  read_struct_2xi32(fn_getutil)).

%% ============================================================
%% Bridge emission — uses llvm_emit rules
%% ============================================================

emit_bridge(OutFile) :-
    open(OutFile, write, S),
    %% Header
    emit_header(S, "x86_64-unknown-linux-gnu"),
    %% External function declarations (from llvm_emit facts)
    format(S, '; --- External functions (from llvm_extern/3 facts) ---~n', []),
    emit_declares(S),
    format(S, '~n', []),
    %% Global state
    emit_bridge_globals(S),
    %% Helper: resolve_sym
    emit_resolve_sym(S),
    %% Lazy init
    emit_nvml_lazy_init(S),
    %% Predicate implementations — generated from plf_impl/2 facts
    forall(plf_impl(Name, Shape),
           (format(atom(ImplFunc), 'pl_~w', [Name]),
            format(S, '; --- ~w → ~w ---~n', [Name, Shape]),
            emit_plf_shape(S, ImplFunc, Shape))),
    %% Install
    emit_bridge_install(S),
    close(S),
    format("Emitted NVML bridge v2 to ~w~n", [OutFile]).

%% ============================================================
%% Globals — generated from nvml_func/5 and plf_pred/3 facts
%% ============================================================

emit_bridge_globals(S) :-
    format(S, '; --- Global state (generated from nvml_func/5 facts) ---~n', []),
    format(S, '@lib_handle = internal global ptr null~n', []),
    format(S, '@nvml_dev = internal global ptr null~n', []),
    format(S, '@lib_initialized = internal global i32 0~n', []),
    format(S, '~n', []),
    %% Function pointer globals — one per nvml_func
    forall(nvml_func(_, _, _, _, FnPtr),
           format(S, '@~w = internal global ptr null~n', [FnPtr])),
    format(S, '~n', []),
    %% String constants for NVML symbol names
    bridge_library(LibName),
    llvm_emit:emit_string(S, str_libname, LibName),
    forall(nvml_func(_, NvmlSym, _, _, FnPtr),
           (format(atom(StrName), 'str_~w', [FnPtr]),
            llvm_emit:emit_string(S, StrName, NvmlSym))),
    format(S, '~n', []),
    %% String constants for Prolog predicate names
    forall(plf_pred(PrologName, _, _),
           (format(atom(StrName), 'str_pred_~w', [PrologName]),
            llvm_emit:emit_string(S, StrName, PrologName))),
    format(S, '~n', []).

%% ============================================================
%% resolve_sym helper
%% ============================================================

emit_resolve_sym(S) :-
    format(S, 'define internal ptr @resolve_sym(ptr %lib, ptr %name) {~n', []),
    format(S, '  %fn = call ptr @dlsym(ptr %lib, ptr %name)~n', []),
    format(S, '  ret ptr %fn~n', []),
    format(S, '}~n~n', []).

%% ============================================================
%% Lazy init — generated from nvml_func/5 facts
%% ============================================================

emit_nvml_lazy_init(S) :-
    format(S, '; --- ensure_nvml_init (generated from nvml_func/5 facts) ---~n', []),
    format(S, 'define internal i32 @ensure_nvml_init() {~n', []),
    format(S, 'entry:~n', []),
    format(S, '  %already = load i32, ptr @lib_initialized~n', []),
    format(S, '  %done = icmp ne i32 %already, 0~n', []),
    format(S, '  br i1 %done, label %ret_ok, label %do_init~n~n', []),
    format(S, 'do_init:~n', []),
    format(S, '  %lib = call ptr @dlopen(ptr @str_libname, i32 2)~n', []),
    format(S, '  %lib_null = icmp eq ptr %lib, null~n', []),
    format(S, '  br i1 %lib_null, label %ret_fail, label %resolve~n~n', []),
    format(S, 'resolve:~n', []),
    format(S, '  store ptr %lib, ptr @lib_handle~n', []),
    %% Resolve each function pointer — GENERATED from facts
    forall(nvml_func(_, _, _, _, FnPtr),
           (format(atom(StrName), 'str_~w', [FnPtr]),
            format(S, '  %~w_p = call ptr @resolve_sym(ptr %lib, ptr @~w)~n', [FnPtr, StrName]),
            format(S, '  store ptr %~w_p, ptr @~w~n', [FnPtr, FnPtr]))),
    format(S, '~n', []),
    %% Call nvmlInit
    format(S, '  %init_fn = load ptr, ptr @fn_init~n', []),
    format(S, '  %init_ret = call i32 %init_fn()~n', []),
    format(S, '  %init_fail = icmp ne i32 %init_ret, 0~n', []),
    format(S, '  br i1 %init_fail, label %ret_fail, label %get_device~n~n', []),
    %% Get device handle
    format(S, 'get_device:~n', []),
    format(S, '  %devptr = alloca ptr~n', []),
    format(S, '  %gh_fn = load ptr, ptr @fn_gethandle~n', []),
    format(S, '  %gh_ret = call i32 %gh_fn(i32 0, ptr %devptr)~n', []),
    format(S, '  %dev = load ptr, ptr %devptr~n', []),
    format(S, '  store ptr %dev, ptr @nvml_dev~n', []),
    format(S, '  store i32 1, ptr @lib_initialized~n', []),
    format(S, '  br label %ret_ok~n~n', []),
    format(S, 'ret_ok:~n  ret i32 0~n~n', []),
    format(S, 'ret_fail:~n  ret i32 1~n', []),
    format(S, '}~n~n', []).

%% ============================================================
%% Shape-dispatched LLVM IR emission
%% ============================================================
%%
%% Each shape in plf_impl/2 has a corresponding emit_plf_shape/3 rule.
%% The rule generates the LLVM IR function body from the shape declaration.
%% Adding a new shape = adding one new rule here.

%% Common preamble: init check → err/read branch
emit_plf_preamble(S, FuncName) :-
    format(S, 'define i32 @~w(i64 %t0, i32 %arity, ptr %control) {~n', [FuncName]),
    format(S, 'entry:~n', []),
    format(S, '  %ir = call i32 @ensure_nvml_init()~n', []),
    format(S, '  %fail = icmp ne i32 %ir, 0~n', []),
    format(S, '  br i1 %fail, label %err, label %read~n~n', []),
    format(S, 'read:~n', []),
    format(S, '  %dev = load ptr, ptr @nvml_dev~n', []).

emit_plf_epilogue(S) :-
    format(S, '~nerr:~n  ret i32 0~n}~n~n', []).

%% --- read_one_i32: call fn(dev, extras..., &val), unify val ---
emit_plf_shape(S, FuncName, read_one_i32(FnPtr, Extras)) :-
    emit_plf_preamble(S, FuncName),
    format(S, '  %val_ptr = alloca i32~n', []),
    format(S, '  %fn = load ptr, ptr @~w~n', [FnPtr]),
    emit_extra_args(Extras, ExtraStr),
    format(S, '  call i32 %fn(ptr %dev~w, ptr %val_ptr)~n', [ExtraStr]),
    format(S, '  %val = load i32, ptr %val_ptr~n', []),
    format(S, '  %val64 = sext i32 %val to i64~n', []),
    format(S, '  %ok = call i32 @PL_unify_integer(i64 %t0, i64 %val64)~n', []),
    format(S, '  ret i32 %ok~n', []),
    emit_plf_epilogue(S).

%% --- read_two_i32: two separate calls, unify both ---
emit_plf_shape(S, FuncName, read_two_i32(Fn1, Ex1, Fn2, Ex2)) :-
    emit_plf_preamble(S, FuncName),
    format(S, '  %t1 = add i64 %t0, 1~n', []),
    format(S, '  %a_ptr = alloca i32~n  %b_ptr = alloca i32~n', []),
    format(S, '  %fn1 = load ptr, ptr @~w~n', [Fn1]),
    format(S, '  %fn2 = load ptr, ptr @~w~n', [Fn2]),
    emit_extra_args(Ex1, ExStr1),
    emit_extra_args(Ex2, ExStr2),
    format(S, '  call i32 %fn1(ptr %dev~w, ptr %a_ptr)~n', [ExStr1]),
    format(S, '  call i32 %fn2(ptr %dev~w, ptr %b_ptr)~n', [ExStr2]),
    format(S, '  %a = load i32, ptr %a_ptr~n  %b = load i32, ptr %b_ptr~n', []),
    format(S, '  %a64 = sext i32 %a to i64~n  %b64 = sext i32 %b to i64~n', []),
    format(S, '  %ok1 = call i32 @PL_unify_integer(i64 %t0, i64 %a64)~n', []),
    format(S, '  %ok2 = call i32 @PL_unify_integer(i64 %t1, i64 %b64)~n', []),
    format(S, '  %ok = and i32 %ok1, %ok2~n  ret i32 %ok~n', []),
    emit_plf_epilogue(S).

%% --- read_struct_2xi32: one call returning struct {i32, i32} ---
emit_plf_shape(S, FuncName, read_struct_2xi32(FnPtr)) :-
    emit_plf_preamble(S, FuncName),
    format(S, '  %t1 = add i64 %t0, 1~n', []),
    format(S, '  %st = alloca [2 x i32]~n', []),
    format(S, '  %fn = load ptr, ptr @~w~n', [FnPtr]),
    format(S, '  call i32 %fn(ptr %dev, ptr %st)~n', []),
    format(S, '  %gp = getelementptr [2 x i32], ptr %st, i32 0, i32 0~n', []),
    format(S, '  %mp = getelementptr [2 x i32], ptr %st, i32 0, i32 1~n', []),
    format(S, '  %g = load i32, ptr %gp~n  %m = load i32, ptr %mp~n', []),
    format(S, '  %g64 = sext i32 %g to i64~n  %m64 = sext i32 %m to i64~n', []),
    format(S, '  %ok1 = call i32 @PL_unify_integer(i64 %t0, i64 %g64)~n', []),
    format(S, '  %ok2 = call i32 @PL_unify_integer(i64 %t1, i64 %m64)~n', []),
    format(S, '  %ok = and i32 %ok1, %ok2~n  ret i32 %ok~n', []),
    emit_plf_epilogue(S).

%% --- read_struct_3xi64_as_mb: struct {i64,i64,i64}, divide by 1MB ---
emit_plf_shape(S, FuncName, read_struct_3xi64_as_mb(FnPtr)) :-
    emit_plf_preamble(S, FuncName),
    format(S, '  %t1 = add i64 %t0, 1~n  %t2 = add i64 %t0, 2~n', []),
    format(S, '  %mi = alloca [3 x i64]~n', []),
    format(S, '  %fn = load ptr, ptr @~w~n', [FnPtr]),
    format(S, '  call i32 %fn(ptr %dev, ptr %mi)~n', []),
    format(S, '  %tp = getelementptr [3 x i64], ptr %mi, i32 0, i32 0~n', []),
    format(S, '  %fp = getelementptr [3 x i64], ptr %mi, i32 0, i32 1~n', []),
    format(S, '  %up = getelementptr [3 x i64], ptr %mi, i32 0, i32 2~n', []),
    format(S, '  %t = load i64, ptr %tp~n  %f = load i64, ptr %fp~n  %u = load i64, ptr %up~n', []),
    format(S, '  %mb = add i64 1048576, 0~n', []),
    format(S, '  %tm = udiv i64 %t, %mb~n  %um = udiv i64 %u, %mb~n  %fm = udiv i64 %f, %mb~n', []),
    format(S, '  %ok1 = call i32 @PL_unify_integer(i64 %t0, i64 %tm)~n', []),
    format(S, '  %ok2 = call i32 @PL_unify_integer(i64 %t1, i64 %um)~n', []),
    format(S, '  %ok3 = call i32 @PL_unify_integer(i64 %t2, i64 %fm)~n', []),
    format(S, '  %a = and i32 %ok1, %ok2~n  %ok = and i32 %a, %ok3~n  ret i32 %ok~n', []),
    emit_plf_epilogue(S).

%% --- read_string: call fn(dev, buf, extras...), unify as atom ---
emit_plf_shape(S, FuncName, read_string(FnPtr, Extras)) :-
    emit_plf_preamble(S, FuncName),
    format(S, '  %buf = alloca [256 x i8]~n', []),
    format(S, '  %fn = load ptr, ptr @~w~n', [FnPtr]),
    emit_extra_args(Extras, ExtraStr),
    format(S, '  call i32 %fn(ptr %dev, ptr %buf~w)~n', [ExtraStr]),
    format(S, '  %ok = call i32 @PL_unify_atom_chars(i64 %t0, ptr %buf)~n', []),
    format(S, '  ret i32 %ok~n', []),
    emit_plf_epilogue(S).

%% --- Extra args formatting ---
emit_extra_args([], '').
emit_extra_args([i32(V)|Rest], Str) :-
    emit_extra_args(Rest, RestStr),
    format(atom(Str), ', i32 ~w~w', [V, RestStr]).
emit_extra_args([i64(V)|Rest], Str) :-
    emit_extra_args(Rest, RestStr),
    format(atom(Str), ', i64 ~w~w', [V, RestStr]).

%% ============================================================
%% Install — generated from plf_pred/3 facts
%% ============================================================

emit_bridge_install(S) :-
    format(S, '; --- install (generated from plf_pred/3 facts) ---~n', []),
    format(S, 'define void @install() {~n', []),
    forall(plf_pred(PrologName, Arity, ImplFunc),
           (format(atom(StrName), 'str_pred_~w', [PrologName]),
            format(S, '  call i32 @PL_register_foreign(ptr @~w, i32 ~w, ptr @~w, i32 0)~n',
                   [StrName, Arity, ImplFunc]))),
    format(S, '  ret void~n}~n', []).
