%% nvml_bridge_emitter.pl — Generate LLVM IR for the NVML-to-SWI-Prolog bridge.
%%
%% Emits a .ll file that, when compiled with llc + clang, produces a .so
%% that bridges SWI-Prolog's FLI to NVML ioctls.
%%
%% The generated code calls NVML functions (dlopen/dlsym at runtime)
%% and exposes them as Prolog predicates:
%%
%%   gpu_temperature(-Temp)     — reads PTHERM register
%%   gpu_power(-MilliWatts)     — reads power sensor
%%   gpu_clock(-SmMHz, -MemMHz) — reads PCLOCK registers
%%   gpu_memory(-TotalMB, -UsedMB, -FreeMB) — reads PFB
%%   gpu_utilization(-GpuPct, -MemPct) — reads PCOUNTER activity
%%   gpu_pcie(-Gen, -Width)     — reads PBUS config
%%   gpu_name(-Name)            — reads PMC identification
%%
%% Usage:
%%   swipl -g 'emit_nvml_bridge("nvml_bridge.ll"), halt' nvml_bridge_emitter.pl
%%   llc -relocation-model=pic -filetype=obj nvml_bridge.ll -o nvml_bridge.o
%%   clang -shared -o nvml_bridge.so nvml_bridge.o -ldl
%%   swipl -g 'use_foreign_library(nvml_bridge), gpu_temperature(T), write(T), nl, halt'
%%
%% Author: mavchin (2026-06-01)

:- module(nvml_bridge_emitter, [emit_nvml_bridge/1, emit_gpu_bridge/1, emit_full_bridge/1]).

emit_nvml_bridge(OutFile) :-
    open(OutFile, write, S),
    emit_header(S),
    emit_types(S),
    emit_global_state(S),
    emit_helper_functions(S),
    emit_nvml_init(S),
    emit_gpu_temperature(S),
    emit_gpu_power(S),
    emit_gpu_clock(S),
    emit_gpu_memory(S),
    emit_gpu_utilization(S),
    emit_gpu_pcie(S),
    emit_gpu_name(S),
    emit_install_function(S),
    close(S),
    format("Emitted NVML bridge IR to ~w~n", [OutFile]).

%% ============================================================
%% LLVM IR header
%% ============================================================

emit_header(S) :-
    format(S, '; nvml_bridge.ll — Generated by nvml_bridge_emitter.pl~n', []),
    format(S, '; Bridges SWI-Prolog FLI to NVML ioctls for GPU register access.~n', []),
    format(S, '; Path: Prolog query → FLI → this .so → NVML → ioctl → kernel → MMIO → hardware~n', []),
    format(S, '~n', []),
    format(S, 'target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"~n', []),
    format(S, 'target triple = "x86_64-unknown-linux-gnu"~n', []),
    format(S, '~n', []).

%% ============================================================
%% Type declarations
%% ============================================================

emit_types(S) :-
    format(S, '; --- External function declarations ---~n', []),
    format(S, 'declare ptr @dlopen(ptr, i32)~n', []),
    format(S, 'declare ptr @dlsym(ptr, ptr)~n', []),
    format(S, 'declare i32 @printf(ptr, ...)~n', []),
    format(S, '~n', []),
    %% SWI-Prolog FLI functions
    format(S, '; SWI-Prolog FLI~n', []),
    format(S, 'declare i64 @PL_new_term_ref()~n', []),
    format(S, 'declare i32 @PL_unify_integer(i64, i64)~n', []),
    format(S, 'declare i32 @PL_unify_atom_chars(i64, ptr)~n', []),
    format(S, 'declare i32 @PL_get_integer(i64, ptr)~n', []),
    format(S, 'declare i32 @PL_register_foreign(ptr, i32, ptr, i32)~n', []),
    format(S, '~n', []).

%% ============================================================
%% Global state (NVML handle, device handle, function pointers)
%% ============================================================

emit_global_state(S) :-
    format(S, '; --- Global state ---~n', []),
    format(S, '@nvml_lib = internal global ptr null~n', []),
    format(S, '@nvml_dev = internal global ptr null~n', []),
    format(S, '@nvml_initialized = internal global i32 0~n', []),
    format(S, '~n', []),
    %% Function pointer globals for each NVML function we use
    format(S, '@fn_init = internal global ptr null~n', []),
    format(S, '@fn_shutdown = internal global ptr null~n', []),
    format(S, '@fn_gethandle = internal global ptr null~n', []),
    format(S, '@fn_getname = internal global ptr null~n', []),
    format(S, '@fn_gettemp = internal global ptr null~n', []),
    format(S, '@fn_getpower = internal global ptr null~n', []),
    format(S, '@fn_getclock = internal global ptr null~n', []),
    format(S, '@fn_getmeminfo = internal global ptr null~n', []),
    format(S, '@fn_getutil = internal global ptr null~n', []),
    format(S, '@fn_getpciegeneration = internal global ptr null~n', []),
    format(S, '@fn_getpciewidth = internal global ptr null~n', []),
    format(S, '~n', []),
    %% String constants
    emit_string_constant(S, 'str_libname', 'libnvidia-ml.so.1'),
    emit_string_constant(S, 'str_init', 'nvmlInit_v2'),
    emit_string_constant(S, 'str_shutdown', 'nvmlShutdown'),
    emit_string_constant(S, 'str_gethandle', 'nvmlDeviceGetHandleByIndex_v2'),
    emit_string_constant(S, 'str_getname', 'nvmlDeviceGetName'),
    emit_string_constant(S, 'str_gettemp', 'nvmlDeviceGetTemperature'),
    emit_string_constant(S, 'str_getpower', 'nvmlDeviceGetPowerUsage'),
    emit_string_constant(S, 'str_getclock', 'nvmlDeviceGetClockInfo'),
    emit_string_constant(S, 'str_getmeminfo', 'nvmlDeviceGetMemoryInfo'),
    emit_string_constant(S, 'str_getutil', 'nvmlDeviceGetUtilizationRates'),
    emit_string_constant(S, 'str_getpciegeneration', 'nvmlDeviceGetCurrPcieLinkGeneration'),
    emit_string_constant(S, 'str_getpciewidth', 'nvmlDeviceGetCurrPcieLinkWidth'),
    emit_string_constant(S, 'str_pred_temp', 'gpu_temperature'),
    emit_string_constant(S, 'str_pred_power', 'gpu_power'),
    emit_string_constant(S, 'str_pred_clock', 'gpu_clock'),
    emit_string_constant(S, 'str_pred_memory', 'gpu_memory'),
    emit_string_constant(S, 'str_pred_util', 'gpu_utilization'),
    emit_string_constant(S, 'str_pred_pcie', 'gpu_pcie'),
    emit_string_constant(S, 'str_pred_name', 'gpu_name'),
    format(S, '~n', []).

emit_string_constant(S, Name, Value) :-
    atom_length(Value, Len),
    Len1 is Len + 1,
    format(S, '@~w = private constant [~w x i8] c"~w\\00"~n', [Name, Len1, Value]).

%% ============================================================
%% Helper: ensure_nvml_init — lazy init on first call
%% ============================================================

emit_helper_functions(S) :-
    format(S, '; --- resolve_sym: dlsym wrapper ---~n', []),
    format(S, 'define internal ptr @resolve_sym(ptr %lib, ptr %name) {~n', []),
    format(S, '  %fn = call ptr @dlsym(ptr %lib, ptr %name)~n', []),
    format(S, '  ret ptr %fn~n', []),
    format(S, '}~n~n', []).

emit_nvml_init(S) :-
    format(S, '; --- ensure_nvml_init: lazy dlopen + dlsym + nvmlInit ---~n', []),
    format(S, 'define internal i32 @ensure_nvml_init() {~n', []),
    format(S, 'entry:~n', []),
    format(S, '  %already = load i32, ptr @nvml_initialized~n', []),
    format(S, '  %done = icmp ne i32 %already, 0~n', []),
    format(S, '  br i1 %done, label %ret_ok, label %do_init~n', []),
    format(S, '~n', []),
    format(S, 'do_init:~n', []),
    %% dlopen
    format(S, '  %lib = call ptr @dlopen(ptr @str_libname, i32 2)~n', []),
    format(S, '  %lib_null = icmp eq ptr %lib, null~n', []),
    format(S, '  br i1 %lib_null, label %ret_fail, label %resolve~n', []),
    format(S, '~n', []),
    format(S, 'resolve:~n', []),
    format(S, '  store ptr %lib, ptr @nvml_lib~n', []),
    %% Resolve all function pointers
    emit_resolve_fn(S, 'fn_init', 'str_init'),
    emit_resolve_fn(S, 'fn_shutdown', 'str_shutdown'),
    emit_resolve_fn(S, 'fn_gethandle', 'str_gethandle'),
    emit_resolve_fn(S, 'fn_getname', 'str_getname'),
    emit_resolve_fn(S, 'fn_gettemp', 'str_gettemp'),
    emit_resolve_fn(S, 'fn_getpower', 'str_getpower'),
    emit_resolve_fn(S, 'fn_getclock', 'str_getclock'),
    emit_resolve_fn(S, 'fn_getmeminfo', 'str_getmeminfo'),
    emit_resolve_fn(S, 'fn_getutil', 'str_getutil'),
    emit_resolve_fn(S, 'fn_getpciegeneration', 'str_getpciegeneration'),
    emit_resolve_fn(S, 'fn_getpciewidth', 'str_getpciewidth'),
    format(S, '~n', []),
    %% Call nvmlInit
    format(S, '  %init_fn = load ptr, ptr @fn_init~n', []),
    format(S, '  %init_ret = call i32 %init_fn()~n', []),
    format(S, '  %init_fail = icmp ne i32 %init_ret, 0~n', []),
    format(S, '  br i1 %init_fail, label %ret_fail, label %get_device~n', []),
    format(S, '~n', []),
    %% Get device handle
    format(S, 'get_device:~n', []),
    format(S, '  %devptr = alloca ptr~n', []),
    format(S, '  %gh_fn = load ptr, ptr @fn_gethandle~n', []),
    format(S, '  %gh_ret = call i32 %gh_fn(i32 0, ptr %devptr)~n', []),
    format(S, '  %dev = load ptr, ptr %devptr~n', []),
    format(S, '  store ptr %dev, ptr @nvml_dev~n', []),
    format(S, '  store i32 1, ptr @nvml_initialized~n', []),
    format(S, '  br label %ret_ok~n', []),
    format(S, '~n', []),
    format(S, 'ret_ok:~n', []),
    format(S, '  ret i32 0~n', []),
    format(S, '~n', []),
    format(S, 'ret_fail:~n', []),
    format(S, '  ret i32 1~n', []),
    format(S, '}~n~n', []).

emit_resolve_fn(S, Global, StrName) :-
    format(S, '  %~w_ptr = call ptr @resolve_sym(ptr %lib, ptr @~w)~n', [Global, StrName]),
    format(S, '  store ptr %~w_ptr, ptr @~w~n', [Global, Global]).

%% ============================================================
%% gpu_temperature(-Temp) — reads PTHERM register
%% ============================================================

emit_gpu_temperature(S) :-
    format(S, '; --- gpu_temperature(Temp) → PTHERM register ---~n', []),
    format(S, 'define i32 @pl_gpu_temperature(i64 %t0, i32 %arity, ptr %control) {~n', []),
    format(S, 'entry:~n', []),
    format(S, '  %ir = call i32 @ensure_nvml_init()~n', []),
    format(S, '  %init_fail = icmp ne i32 %ir, 0~n', []),
    format(S, '  br i1 %init_fail, label %fail, label %read~n', []),
    format(S, '~n', []),
    format(S, 'read:~n', []),
    format(S, '  %dev = load ptr, ptr @nvml_dev~n', []),
    format(S, '  %temp_ptr = alloca i32~n', []),
    format(S, '  %fn = load ptr, ptr @fn_gettemp~n', []),
    format(S, '  %ret = call i32 %fn(ptr %dev, i32 0, ptr %temp_ptr)~n', []),
    format(S, '  %temp = load i32, ptr %temp_ptr~n', []),
    format(S, '  %temp64 = sext i32 %temp to i64~n', []),
    format(S, '  %ok = call i32 @PL_unify_integer(i64 %t0, i64 %temp64)~n', []),
    format(S, '  ret i32 %ok~n', []),
    format(S, '~n', []),
    format(S, 'fail:~n', []),
    format(S, '  ret i32 0~n', []),
    format(S, '}~n~n', []).

%% ============================================================
%% gpu_power(-MilliWatts)
%% ============================================================

emit_gpu_power(S) :-
    format(S, '; --- gpu_power(MilliWatts) → power sensor ---~n', []),
    format(S, 'define i32 @pl_gpu_power(i64 %t0, i32 %arity, ptr %control) {~n', []),
    format(S, 'entry:~n', []),
    format(S, '  %ir = call i32 @ensure_nvml_init()~n', []),
    format(S, '  %init_fail = icmp ne i32 %ir, 0~n', []),
    format(S, '  br i1 %init_fail, label %fail, label %read~n', []),
    format(S, '~n', []),
    format(S, 'read:~n', []),
    format(S, '  %dev = load ptr, ptr @nvml_dev~n', []),
    format(S, '  %val_ptr = alloca i32~n', []),
    format(S, '  %fn = load ptr, ptr @fn_getpower~n', []),
    format(S, '  %ret = call i32 %fn(ptr %dev, ptr %val_ptr)~n', []),
    format(S, '  %val = load i32, ptr %val_ptr~n', []),
    format(S, '  %val64 = sext i32 %val to i64~n', []),
    format(S, '  %ok = call i32 @PL_unify_integer(i64 %t0, i64 %val64)~n', []),
    format(S, '  ret i32 %ok~n', []),
    format(S, '~n', []),
    format(S, 'fail:~n', []),
    format(S, '  ret i32 0~n', []),
    format(S, '}~n~n', []).

%% ============================================================
%% gpu_clock(-SmMHz, -MemMHz)
%% ============================================================

emit_gpu_clock(S) :-
    format(S, '; --- gpu_clock(SmMHz, MemMHz) → PCLOCK registers ---~n', []),
    format(S, 'define i32 @pl_gpu_clock(i64 %t0, i32 %arity, ptr %control) {~n', []),
    format(S, 'entry:~n', []),
    format(S, '  %ir = call i32 @ensure_nvml_init()~n', []),
    format(S, '  %init_fail = icmp ne i32 %ir, 0~n', []),
    format(S, '  br i1 %init_fail, label %fail, label %read~n', []),
    format(S, '~n', []),
    format(S, 'read:~n', []),
    format(S, '  %t1 = add i64 %t0, 1~n', []),
    format(S, '  %dev = load ptr, ptr @nvml_dev~n', []),
    format(S, '  %sm_ptr = alloca i32~n', []),
    format(S, '  %mem_ptr = alloca i32~n', []),
    format(S, '  %fn = load ptr, ptr @fn_getclock~n', []),
    format(S, '  call i32 %fn(ptr %dev, i32 0, ptr %sm_ptr)~n', []),
    format(S, '  call i32 %fn(ptr %dev, i32 1, ptr %mem_ptr)~n', []),
    format(S, '  %sm = load i32, ptr %sm_ptr~n', []),
    format(S, '  %mem = load i32, ptr %mem_ptr~n', []),
    format(S, '  %sm64 = sext i32 %sm to i64~n', []),
    format(S, '  %mem64 = sext i32 %mem to i64~n', []),
    format(S, '  %ok1 = call i32 @PL_unify_integer(i64 %t0, i64 %sm64)~n', []),
    format(S, '  %ok2 = call i32 @PL_unify_integer(i64 %t1, i64 %mem64)~n', []),
    format(S, '  %ok = and i32 %ok1, %ok2~n', []),
    format(S, '  ret i32 %ok~n', []),
    format(S, '~n', []),
    format(S, 'fail:~n', []),
    format(S, '  ret i32 0~n', []),
    format(S, '}~n~n', []).

%% ============================================================
%% gpu_memory(-TotalMB, -UsedMB, -FreeMB)
%% ============================================================

emit_gpu_memory(S) :-
    format(S, '; --- gpu_memory(TotalMB, UsedMB, FreeMB) → PFB registers ---~n', []),
    format(S, 'define i32 @pl_gpu_memory(i64 %t0, i32 %arity, ptr %control) {~n', []),
    format(S, 'entry:~n', []),
    format(S, '  %ir = call i32 @ensure_nvml_init()~n', []),
    format(S, '  %init_fail = icmp ne i32 %ir, 0~n', []),
    format(S, '  br i1 %init_fail, label %fail, label %read~n', []),
    format(S, '~n', []),
    format(S, 'read:~n', []),
    format(S, '  %t1 = add i64 %t0, 1~n', []),
    format(S, '  %t2 = add i64 %t0, 2~n', []),
    format(S, '  %dev = load ptr, ptr @nvml_dev~n', []),
    %% meminfo struct: {total:i64, free:i64, used:i64}
    format(S, '  %mi = alloca [3 x i64]~n', []),
    format(S, '  %fn = load ptr, ptr @fn_getmeminfo~n', []),
    format(S, '  call i32 %fn(ptr %dev, ptr %mi)~n', []),
    format(S, '  %total_ptr = getelementptr [3 x i64], ptr %mi, i32 0, i32 0~n', []),
    format(S, '  %free_ptr = getelementptr [3 x i64], ptr %mi, i32 0, i32 1~n', []),
    format(S, '  %used_ptr = getelementptr [3 x i64], ptr %mi, i32 0, i32 2~n', []),
    format(S, '  %total = load i64, ptr %total_ptr~n', []),
    format(S, '  %free = load i64, ptr %free_ptr~n', []),
    format(S, '  %used = load i64, ptr %used_ptr~n', []),
    format(S, '  %mb = add i64 1048576, 0~n', []),
    format(S, '  %total_mb = udiv i64 %total, %mb~n', []),
    format(S, '  %used_mb = udiv i64 %used, %mb~n', []),
    format(S, '  %free_mb = udiv i64 %free, %mb~n', []),
    format(S, '  %ok1 = call i32 @PL_unify_integer(i64 %t0, i64 %total_mb)~n', []),
    format(S, '  %ok2 = call i32 @PL_unify_integer(i64 %t1, i64 %used_mb)~n', []),
    format(S, '  %ok3 = call i32 @PL_unify_integer(i64 %t2, i64 %free_mb)~n', []),
    format(S, '  %a = and i32 %ok1, %ok2~n', []),
    format(S, '  %ok = and i32 %a, %ok3~n', []),
    format(S, '  ret i32 %ok~n', []),
    format(S, '~n', []),
    format(S, 'fail:~n', []),
    format(S, '  ret i32 0~n', []),
    format(S, '}~n~n', []).

%% ============================================================
%% gpu_utilization(-GpuPct, -MemPct)
%% ============================================================

emit_gpu_utilization(S) :-
    format(S, '; --- gpu_utilization(GpuPct, MemPct) → PCOUNTER activity ---~n', []),
    format(S, 'define i32 @pl_gpu_utilization(i64 %t0, i32 %arity, ptr %control) {~n', []),
    format(S, 'entry:~n', []),
    format(S, '  %ir = call i32 @ensure_nvml_init()~n', []),
    format(S, '  %init_fail = icmp ne i32 %ir, 0~n', []),
    format(S, '  br i1 %init_fail, label %fail, label %read~n', []),
    format(S, '~n', []),
    format(S, 'read:~n', []),
    format(S, '  %t1 = add i64 %t0, 1~n', []),
    format(S, '  %dev = load ptr, ptr @nvml_dev~n', []),
    format(S, '  %util = alloca [2 x i32]~n', []),
    format(S, '  %fn = load ptr, ptr @fn_getutil~n', []),
    format(S, '  call i32 %fn(ptr %dev, ptr %util)~n', []),
    format(S, '  %gpu_ptr = getelementptr [2 x i32], ptr %util, i32 0, i32 0~n', []),
    format(S, '  %mem_ptr = getelementptr [2 x i32], ptr %util, i32 0, i32 1~n', []),
    format(S, '  %gpu = load i32, ptr %gpu_ptr~n', []),
    format(S, '  %mem = load i32, ptr %mem_ptr~n', []),
    format(S, '  %gpu64 = sext i32 %gpu to i64~n', []),
    format(S, '  %mem64 = sext i32 %mem to i64~n', []),
    format(S, '  %ok1 = call i32 @PL_unify_integer(i64 %t0, i64 %gpu64)~n', []),
    format(S, '  %ok2 = call i32 @PL_unify_integer(i64 %t1, i64 %mem64)~n', []),
    format(S, '  %ok = and i32 %ok1, %ok2~n', []),
    format(S, '  ret i32 %ok~n', []),
    format(S, '~n', []),
    format(S, 'fail:~n', []),
    format(S, '  ret i32 0~n', []),
    format(S, '}~n~n', []).

%% ============================================================
%% gpu_pcie(-Gen, -Width)
%% ============================================================

emit_gpu_pcie(S) :-
    format(S, '; --- gpu_pcie(Gen, Width) → PBUS config ---~n', []),
    format(S, 'define i32 @pl_gpu_pcie(i64 %t0, i32 %arity, ptr %control) {~n', []),
    format(S, 'entry:~n', []),
    format(S, '  %ir = call i32 @ensure_nvml_init()~n', []),
    format(S, '  %init_fail = icmp ne i32 %ir, 0~n', []),
    format(S, '  br i1 %init_fail, label %fail, label %read~n', []),
    format(S, '~n', []),
    format(S, 'read:~n', []),
    format(S, '  %t1 = add i64 %t0, 1~n', []),
    format(S, '  %dev = load ptr, ptr @nvml_dev~n', []),
    format(S, '  %gen_ptr = alloca i32~n', []),
    format(S, '  %width_ptr = alloca i32~n', []),
    format(S, '  %fn_gen = load ptr, ptr @fn_getpciegeneration~n', []),
    format(S, '  %fn_wid = load ptr, ptr @fn_getpciewidth~n', []),
    format(S, '  call i32 %fn_gen(ptr %dev, ptr %gen_ptr)~n', []),
    format(S, '  call i32 %fn_wid(ptr %dev, ptr %width_ptr)~n', []),
    format(S, '  %gen = load i32, ptr %gen_ptr~n', []),
    format(S, '  %wid = load i32, ptr %width_ptr~n', []),
    format(S, '  %gen64 = sext i32 %gen to i64~n', []),
    format(S, '  %wid64 = sext i32 %wid to i64~n', []),
    format(S, '  %ok1 = call i32 @PL_unify_integer(i64 %t0, i64 %gen64)~n', []),
    format(S, '  %ok2 = call i32 @PL_unify_integer(i64 %t1, i64 %wid64)~n', []),
    format(S, '  %ok = and i32 %ok1, %ok2~n', []),
    format(S, '  ret i32 %ok~n', []),
    format(S, '~n', []),
    format(S, 'fail:~n', []),
    format(S, '  ret i32 0~n', []),
    format(S, '}~n~n', []).

%% ============================================================
%% gpu_name(-Name)
%% ============================================================

emit_gpu_name(S) :-
    format(S, '; --- gpu_name(Name) → PMC identification ---~n', []),
    format(S, 'define i32 @pl_gpu_name(i64 %t0, i32 %arity, ptr %control) {~n', []),
    format(S, 'entry:~n', []),
    format(S, '  %ir = call i32 @ensure_nvml_init()~n', []),
    format(S, '  %init_fail = icmp ne i32 %ir, 0~n', []),
    format(S, '  br i1 %init_fail, label %fail, label %read~n', []),
    format(S, '~n', []),
    format(S, 'read:~n', []),
    format(S, '  %dev = load ptr, ptr @nvml_dev~n', []),
    format(S, '  %buf = alloca [256 x i8]~n', []),
    format(S, '  %fn = load ptr, ptr @fn_getname~n', []),
    format(S, '  call i32 %fn(ptr %dev, ptr %buf, i32 256)~n', []),
    format(S, '  %ok = call i32 @PL_unify_atom_chars(i64 %t0, ptr %buf)~n', []),
    format(S, '  ret i32 %ok~n', []),
    format(S, '~n', []),
    format(S, 'fail:~n', []),
    format(S, '  ret i32 0~n', []),
    format(S, '}~n~n', []).

%% ============================================================
%% install_nvml_bridge — register all predicates with SWI-Prolog
%% ============================================================

emit_install_function(S) :-
    format(S, '; --- install function (called by SWI-Prolog on load) ---~n', []),
    format(S, 'define void @install() {~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_temp, i32 1, ptr @pl_gpu_temperature, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_power, i32 1, ptr @pl_gpu_power, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_clock, i32 2, ptr @pl_gpu_clock, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_memory, i32 3, ptr @pl_gpu_memory, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_util, i32 2, ptr @pl_gpu_utilization, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_pcie, i32 2, ptr @pl_gpu_pcie, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_name, i32 1, ptr @pl_gpu_name, i32 0)~n', []),
    format(S, '  ret void~n', []),
    format(S, '}~n', []).

%% ============================================================
%% FULL GPU BRIDGE: NVML + CUPTI in one .so
%% ============================================================
%%
%% emit_gpu_bridge/1 generates LLVM IR for BOTH NVML monitoring
%% AND CUPTI warp stall profiling, unified in one shared library.
%%
%% CUPTI predicates:
%%   cupti_start_profiling/0  — enable PC sampling
%%   cupti_stop_profiling/0   — disable PC sampling
%%   cupti_flush/0            — flush activity buffers
%%   cupti_stall_report/1     — get stall percentages as Key-Pct pairs
%%
%% The CUPTI path uses activity callbacks for async buffer management.
%% The callbacks are defined as named LLVM functions that CUPTI invokes.

emit_gpu_bridge(OutFile) :-
    open(OutFile, write, S),
    emit_header(S),
    emit_bridge_types(S),
    emit_bridge_globals(S),
    emit_helper_functions(S),
    emit_nvml_init(S),
    %% NVML predicates
    emit_gpu_temperature(S),
    emit_gpu_power(S),
    emit_gpu_clock(S),
    emit_gpu_memory(S),
    emit_gpu_utilization(S),
    emit_gpu_pcie(S),
    emit_gpu_name(S),
    %% CUPTI predicates
    emit_cupti_globals(S),
    emit_cupti_callbacks(S),
    emit_cupti_init(S),
    emit_cupti_flush(S),
    emit_cupti_shutdown(S),
    emit_cupti_stall_report(S),
    %% Unified install
    emit_bridge_install(S),
    close(S),
    format("Emitted GPU bridge IR (NVML+CUPTI) to ~w~n", [OutFile]).

%% Extended type declarations (adds CUPTI + CUDA functions)
emit_bridge_types(S) :-
    emit_types(S),
    format(S, '; CUPTI Activity API~n', []),
    format(S, 'declare i32 @cuptiActivityRegisterCallbacks(ptr, ptr)~n', []),
    format(S, 'declare i32 @cuptiActivityEnable(i32)~n', []),
    format(S, 'declare i32 @cuptiActivityDisable(i32)~n', []),
    format(S, 'declare i32 @cuptiActivityFlushAll(i32)~n', []),
    format(S, 'declare i32 @cuptiActivityGetNextRecord(ptr, i64, ptr)~n', []),
    format(S, 'declare void @cuptiGetResultString(i32, ptr)~n', []),
    format(S, '~n', []),
    format(S, '; CUDA driver~n', []),
    format(S, 'declare i32 @cuInit(i32)~n', []),
    format(S, 'declare i32 @cuCtxGetCurrent(ptr)~n', []),
    format(S, '~n', []),
    format(S, '; C stdlib~n', []),
    format(S, 'declare ptr @malloc(i64)~n', []),
    format(S, 'declare void @free(ptr)~n', []),
    format(S, 'declare ptr @memset(ptr, i32, i64)~n', []),
    format(S, '~n', []),
    format(S, '; SWI-Prolog list building~n', []),
    format(S, 'declare i32 @PL_unify_nil(i64)~n', []),
    format(S, 'declare i32 @PL_unify_list(i64, i64, i64)~n', []),
    format(S, 'declare i32 @PL_unify_float(i64, double)~n', []),
    format(S, 'declare i32 @PL_put_atom_chars(i64, ptr)~n', []),
    format(S, 'declare i32 @PL_put_float(i64, double)~n', []),
    format(S, 'declare i32 @PL_cons_functor(i64, i64, i64, i64)~n', []),
    format(S, 'declare i64 @PL_new_functor(i64, i32)~n', []),
    format(S, 'declare i64 @PL_new_atom(ptr)~n', []),
    format(S, 'declare i64 @PL_copy_term_ref(i64)~n', []),
    format(S, 'declare i32 @PL_unify(i64, i64)~n', []),
    format(S, '~n', []).

%% Extended globals (adds CUPTI state)
emit_bridge_globals(S) :-
    emit_global_state(S).

emit_cupti_globals(S) :-
    format(S, '; --- CUPTI global state ---~n', []),
    format(S, '; Stall counters: 13 x i64 (12 stall reasons + total)~n', []),
    format(S, '@cupti_stalls = internal global [13 x i64] zeroinitializer~n', []),
    format(S, '@cupti_enabled = internal global i32 0~n', []),
    format(S, '~n', []),
    %% Stall reason names (for building the Prolog list)
    StallNames = [none, inst_fetch, exec_dependency, memory_dependency,
                  texture, sync, constant_memory, pipe_busy,
                  memory_throttle, not_selected, sleeping, other],
    emit_stall_name_strings(S, StallNames, 0),
    format(S, '~n', []),
    %% CUPTI predicate name strings
    emit_string_constant(S, 'str_pred_cupti_start', 'cupti_start_profiling'),
    emit_string_constant(S, 'str_pred_cupti_stop', 'cupti_stop_profiling'),
    emit_string_constant(S, 'str_pred_cupti_flush', 'cupti_flush'),
    emit_string_constant(S, 'str_pred_cupti_stalls', 'cupti_stall_report'),
    emit_string_constant(S, 'str_dash', '-'),
    format(S, '~n', []).

emit_stall_name_strings(_, [], _).
emit_stall_name_strings(S, [Name|Rest], Idx) :-
    format(atom(GlobalName), 'str_stall_~w', [Idx]),
    emit_string_constant(S, GlobalName, Name),
    Idx1 is Idx + 1,
    emit_stall_name_strings(S, Rest, Idx1).

%% CUPTI activity buffer callbacks (called by CUPTI runtime)
emit_cupti_callbacks(S) :-
    format(S, '; --- CUPTI buffer callbacks (called by CUPTI runtime) ---~n', []),
    %% bufferRequested: allocate 32KB buffer
    format(S, 'define void @cupti_buffer_requested(ptr %buf_out, ptr %size_out, ptr %max_out) {~n', []),
    format(S, '  %buf = call ptr @malloc(i64 32768)~n', []),
    format(S, '  store ptr %buf, ptr %buf_out~n', []),
    format(S, '  store i64 32768, ptr %size_out~n', []),
    format(S, '  store i64 0, ptr %max_out~n', []),
    format(S, '  ret void~n', []),
    format(S, '}~n~n', []),
    %% bufferCompleted: walk records, accumulate stalls
    format(S, 'define void @cupti_buffer_completed(ptr %ctx, i32 %streamId, ptr %buffer, i64 %size, i64 %validSize) {~n', []),
    format(S, 'entry:~n', []),
    format(S, '  %record_ptr = alloca ptr~n', []),
    format(S, '  store ptr null, ptr %record_ptr~n', []),
    format(S, '  br label %loop~n', []),
    format(S, '~n', []),
    format(S, 'loop:~n', []),
    format(S, '  %status = call i32 @cuptiActivityGetNextRecord(ptr %buffer, i64 %validSize, ptr %record_ptr)~n', []),
    format(S, '  %done = icmp ne i32 %status, 0~n', []),
    format(S, '  br i1 %done, label %cleanup, label %process~n', []),
    format(S, '~n', []),
    format(S, 'process:~n', []),
    format(S, '  %record = load ptr, ptr %record_ptr~n', []),
    %% Check activity kind: offset 0 is the kind field (i32)
    %% CUPTI_ACTIVITY_KIND_PC_SAMPLING = 51
    format(S, '  %kind_ptr = getelementptr i8, ptr %record, i32 0~n', []),
    format(S, '  %kind = load i32, ptr %kind_ptr~n', []),
    format(S, '  %is_pc = icmp eq i32 %kind, 51~n', []),
    format(S, '  br i1 %is_pc, label %accumulate, label %loop~n', []),
    format(S, '~n', []),
    format(S, 'accumulate:~n', []),
    %% CUpti_ActivityPCSampling3 layout:
    %%   offset 0: kind (i32), offset 4: flags (i32)
    %%   offset 8: sourceLocatorId (i32), offset 12: correlationId (i32)
    %%   offset 16: functionId (i32), offset 20: pcOffset (i32)
    %%   offset 24: stallReason (i32), offset 28: samples (i32)
    format(S, '  %stall_ptr = getelementptr i8, ptr %record, i32 24~n', []),
    format(S, '  %stall_reason = load i32, ptr %stall_ptr~n', []),
    format(S, '  %samples_ptr = getelementptr i8, ptr %record, i32 28~n', []),
    format(S, '  %samples = load i32, ptr %samples_ptr~n', []),
    format(S, '  %samples64 = zext i32 %samples to i64~n', []),
    %% Clamp stall_reason to 0..11
    format(S, '  %in_range = icmp ult i32 %stall_reason, 12~n', []),
    format(S, '  %idx = select i1 %in_range, i32 %stall_reason, i32 11~n', []),
    %% Accumulate into @cupti_stalls[idx]
    format(S, '  %slot_ptr = getelementptr [13 x i64], ptr @cupti_stalls, i32 0, i32 %idx~n', []),
    format(S, '  %old = load i64, ptr %slot_ptr~n', []),
    format(S, '  %new = add i64 %old, %samples64~n', []),
    format(S, '  store i64 %new, ptr %slot_ptr~n', []),
    %% Also accumulate total (slot 12)
    format(S, '  %total_ptr = getelementptr [13 x i64], ptr @cupti_stalls, i32 0, i32 12~n', []),
    format(S, '  %old_total = load i64, ptr %total_ptr~n', []),
    format(S, '  %new_total = add i64 %old_total, %samples64~n', []),
    format(S, '  store i64 %new_total, ptr %total_ptr~n', []),
    format(S, '  br label %loop~n', []),
    format(S, '~n', []),
    format(S, 'cleanup:~n', []),
    format(S, '  call void @free(ptr %buffer)~n', []),
    format(S, '  ret void~n', []),
    format(S, '}~n~n', []).

%% cupti_start_profiling/0
emit_cupti_init(S) :-
    format(S, '; --- cupti_start_profiling/0 ---~n', []),
    format(S, 'define i32 @pl_cupti_start(i64 %t0, i32 %arity, ptr %control) {~n', []),
    format(S, 'entry:~n', []),
    %% Zero the counters
    format(S, '  call ptr @memset(ptr @cupti_stalls, i32 0, i64 104)~n', []),
    %% Register callbacks
    format(S, '  %rc1 = call i32 @cuptiActivityRegisterCallbacks(ptr @cupti_buffer_requested, ptr @cupti_buffer_completed)~n', []),
    %% Enable PC sampling (kind=51)
    format(S, '  %rc2 = call i32 @cuptiActivityEnable(i32 51)~n', []),
    format(S, '  store i32 1, ptr @cupti_enabled~n', []),
    format(S, '  ret i32 1~n', []),
    format(S, '}~n~n', []).

%% cupti_flush/0
emit_cupti_flush(S) :-
    format(S, '; --- cupti_flush/0 ---~n', []),
    format(S, 'define i32 @pl_cupti_flush(i64 %t0, i32 %arity, ptr %control) {~n', []),
    format(S, '  call i32 @cuptiActivityFlushAll(i32 0)~n', []),
    format(S, '  ret i32 1~n', []),
    format(S, '}~n~n', []).

%% cupti_stop_profiling/0
emit_cupti_shutdown(S) :-
    format(S, '; --- cupti_stop_profiling/0 ---~n', []),
    format(S, 'define i32 @pl_cupti_stop(i64 %t0, i32 %arity, ptr %control) {~n', []),
    format(S, '  call i32 @cuptiActivityDisable(i32 51)~n', []),
    format(S, '  store i32 0, ptr @cupti_enabled~n', []),
    format(S, '  ret i32 1~n', []),
    format(S, '}~n~n', []).

%% cupti_stall_report(-List)
%% Returns a Prolog list of StallName-Percentage pairs
emit_cupti_stall_report(S) :-
    format(S, '; --- cupti_stall_report(List) → warp stall percentages ---~n', []),
    format(S, 'define i32 @pl_cupti_stall_report(i64 %t0, i32 %arity, ptr %control) {~n', []),
    format(S, 'entry:~n', []),
    %% Get total samples
    format(S, '  %total_ptr = getelementptr [13 x i64], ptr @cupti_stalls, i32 0, i32 12~n', []),
    format(S, '  %total = load i64, ptr %total_ptr~n', []),
    format(S, '  %no_data = icmp eq i64 %total, 0~n', []),
    format(S, '  br i1 %no_data, label %empty, label %build_list~n', []),
    format(S, '~n', []),
    format(S, 'empty:~n', []),
    format(S, '  %ok_empty = call i32 @PL_unify_nil(i64 %t0)~n', []),
    format(S, '  ret i32 %ok_empty~n', []),
    format(S, '~n', []),
    format(S, 'build_list:~n', []),
    format(S, '  %total_f = uitofp i64 %total to double~n', []),
    format(S, '  %list = call i64 @PL_copy_term_ref(i64 %t0)~n', []),
    format(S, '  %head = call i64 @PL_new_term_ref()~n', []),
    format(S, '  %dash_atom = call i64 @PL_new_atom(ptr @str_dash)~n', []),
    format(S, '  %dash_fn = call i64 @PL_new_functor(i64 %dash_atom, i32 2)~n', []),
    format(S, '~n', []),
    %% Emit each stall reason as a list entry
    StallNames = [none, inst_fetch, exec_dependency, memory_dependency,
                  texture, sync, constant_memory, pipe_busy,
                  memory_throttle, not_selected, sleeping, other],
    emit_stall_list_entries(S, StallNames, 0),
    format(S, '~n', []),
    format(S, '  %ok_nil = call i32 @PL_unify_nil(i64 %list)~n', []),
    format(S, '  ret i32 %ok_nil~n', []),
    format(S, '}~n~n', []).

emit_stall_list_entries(_, [], _).
emit_stall_list_entries(S, [_Name|Rest], Idx) :-
    format(atom(SlotLabel), 'slot~w', [Idx]),
    format(atom(ValLabel), 'val~w', [Idx]),
    format(atom(PctLabel), 'pct~w', [Idx]),
    format(atom(NonZeroLabel), 'nz~w', [Idx]),
    format(atom(SkipLabel), 'skip~w', [Idx]),
    format(atom(AddLabel), 'add~w', [Idx]),
    format(atom(KeyLabel), 'key~w', [Idx]),
    format(atom(FloatLabel), 'flt~w', [Idx]),
    format(atom(PairLabel), 'pair~w', [Idx]),
    Idx1 is Idx + 1,
    format(atom(NextLabel), 'stall~w', [Idx1]),
    format(S, '  ; stall reason ~w~n', [Idx]),
    format(S, '  %~w = getelementptr [13 x i64], ptr @cupti_stalls, i32 0, i32 ~w~n', [SlotLabel, Idx]),
    format(S, '  %~w = load i64, ptr %~w~n', [ValLabel, SlotLabel]),
    format(S, '  %~w = icmp ugt i64 %~w, 0~n', [NonZeroLabel, ValLabel]),
    format(S, '  br i1 %~w, label %~w, label %~w~n', [NonZeroLabel, AddLabel, SkipLabel]),
    format(S, '~n', []),
    format(S, '~w:~n', [AddLabel]),
    format(S, '  %~w_f = uitofp i64 %~w to double~n', [ValLabel, ValLabel]),
    format(S, '  %~w_raw = fdiv double %~w_f, %total_f~n', [PctLabel, ValLabel]),
    format(S, '  %~w = fmul double %~w_raw, 100.0~n', [PctLabel, PctLabel]),
    format(S, '  %~w = call i64 @PL_new_term_ref()~n', [KeyLabel]),
    format(S, '  %~w = call i64 @PL_new_term_ref()~n', [FloatLabel]),
    format(S, '  %~w = call i64 @PL_new_term_ref()~n', [PairLabel]),
    format(S, '  call i32 @PL_put_atom_chars(i64 %~w, ptr @str_stall_~w)~n', [KeyLabel, Idx]),
    format(S, '  call i32 @PL_put_float(i64 %~w, double %~w)~n', [FloatLabel, PctLabel]),
    format(S, '  call i32 @PL_cons_functor(i64 %~w, i64 %dash_fn, i64 %~w, i64 %~w)~n', [PairLabel, KeyLabel, FloatLabel]),
    format(S, '  call i32 @PL_unify_list(i64 %list, i64 %head, i64 %list)~n', []),
    format(S, '  call i32 @PL_unify(i64 %head, i64 %~w)~n', [PairLabel]),
    format(S, '  br label %~w~n', [SkipLabel]),
    format(S, '~n', []),
    format(S, '~w:~n', [SkipLabel]),
    emit_stall_list_entries(S, Rest, Idx1).

%% Unified install for NVML + CUPTI
emit_bridge_install(S) :-
    format(S, '; --- unified install (NVML + CUPTI) ---~n', []),
    format(S, 'define void @install() {~n', []),
    %% NVML predicates
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_temp, i32 1, ptr @pl_gpu_temperature, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_power, i32 1, ptr @pl_gpu_power, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_clock, i32 2, ptr @pl_gpu_clock, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_memory, i32 3, ptr @pl_gpu_memory, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_util, i32 2, ptr @pl_gpu_utilization, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_pcie, i32 2, ptr @pl_gpu_pcie, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_name, i32 1, ptr @pl_gpu_name, i32 0)~n', []),
    %% CUPTI predicates
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_cupti_start, i32 0, ptr @pl_cupti_start, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_cupti_stop, i32 0, ptr @pl_cupti_stop, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_cupti_flush, i32 0, ptr @pl_cupti_flush, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_cupti_stalls, i32 1, ptr @pl_cupti_stall_report, i32 0)~n', []),
    format(S, '  ret void~n', []),
    format(S, '}~n', []).

%% ============================================================
%% FULL BRIDGE: NVML + CUPTI + CPU PMU in one .so
%% ============================================================
%%
%% CPU PMU predicates (via perf_event_open syscall):
%%   cpu_pmu_start/0          — open and enable counters
%%   cpu_pmu_stop/0           — disable and close counters
%%   cpu_pmu_read/1           — read all counters as Key-Value list
%%
%% Counters read from Ivy Bridge PMU:
%%   cycles, instructions, cache_misses, branch_misses,
%%   sse_packed_single, sse_scalar_single, avx_256_packed_single,
%%   l1d_load_misses, llc_load_misses
%%
%% Uses raw syscall (no libperf dependency). Generated as LLVM IR.

emit_full_bridge(OutFile) :-
    open(OutFile, write, S),
    emit_header(S),
    emit_full_types(S),
    emit_bridge_globals(S),
    emit_helper_functions(S),
    emit_nvml_init(S),
    %% NVML predicates
    emit_gpu_temperature(S),
    emit_gpu_power(S),
    emit_gpu_clock(S),
    emit_gpu_memory(S),
    emit_gpu_utilization(S),
    emit_gpu_pcie(S),
    emit_gpu_name(S),
    %% CUPTI predicates
    emit_cupti_globals(S),
    emit_cupti_callbacks(S),
    emit_cupti_init(S),
    emit_cupti_flush(S),
    emit_cupti_shutdown(S),
    emit_cupti_stall_report(S),
    %% CPU PMU predicates
    emit_pmu_globals(S),
    emit_pmu_start(S),
    emit_pmu_stop(S),
    emit_pmu_read(S),
    %% Unified install
    emit_full_install(S),
    close(S),
    format("Emitted full bridge IR (NVML+CUPTI+PMU) to ~w~n", [OutFile]).

emit_full_types(S) :-
    emit_bridge_types(S),
    format(S, '; Linux syscall~n', []),
    format(S, 'declare i64 @syscall(i64, ...)~n', []),
    format(S, 'declare i32 @ioctl(i32, i64, ...)~n', []),
    format(S, 'declare i64 @read(i32, ptr, i64)~n', []),
    format(S, 'declare i32 @close(i32)~n', []),
    format(S, '~n', []).

%% CPU PMU counter definitions
%% Each counter: {name, perf_type, config, fd_global}
pmu_counter(cycles,              0, 0,      'fd_cycles').       % PERF_TYPE_HARDWARE, PERF_COUNT_HW_CPU_CYCLES
pmu_counter(instructions,        0, 1,      'fd_insns').        % PERF_COUNT_HW_INSTRUCTIONS
pmu_counter(cache_misses,        0, 3,      'fd_cache_miss').   % PERF_COUNT_HW_CACHE_MISSES
pmu_counter(branch_misses,       0, 5,      'fd_branch_miss').  % PERF_COUNT_HW_BRANCH_MISSES
pmu_counter(sse_packed_single,   4, 16400,  'fd_sse_ps').       % PERF_TYPE_RAW, 0x4010
pmu_counter(sse_scalar_single,   4, 8208,   'fd_sse_ss').       % PERF_TYPE_RAW, 0x2010
pmu_counter(avx_256_packed,      4, 273,    'fd_avx_ps').       % PERF_TYPE_RAW, 0x0111

emit_pmu_globals(S) :-
    format(S, '; --- CPU PMU globals ---~n', []),
    forall(pmu_counter(_, _, _, FdGlobal),
           format(S, '@~w = internal global i32 -1~n', [FdGlobal])),
    format(S, '@pmu_started = internal global i32 0~n', []),
    format(S, '~n', []),
    %% perf_event_attr struct: 112 bytes on x86_64
    %% We only need: type(offset 0, i32), size(offset 4, i32), config(offset 8, i64),
    %%               disabled(offset 40 bit 0), exclude_kernel(offset 40 bit 1), exclude_hv(offset 40 bit 2)
    %% String constants for counter names
    forall(pmu_counter(Name, _, _, _),
           (format(atom(StrGlobal), 'str_pmu_~w', [Name]),
            emit_string_constant(S, StrGlobal, Name))),
    emit_string_constant(S, 'str_pred_pmu_start', 'cpu_pmu_start'),
    emit_string_constant(S, 'str_pred_pmu_stop', 'cpu_pmu_stop'),
    emit_string_constant(S, 'str_pred_pmu_read', 'cpu_pmu_read'),
    format(S, '~n', []).

%% cpu_pmu_start/0 — open perf_event_open for each counter, enable them
emit_pmu_start(S) :-
    format(S, '; --- cpu_pmu_start/0: open + enable PMU counters ---~n', []),
    format(S, 'define i32 @pl_pmu_start(i64 %t0, i32 %arity, ptr %control) {~n', []),
    format(S, 'entry:~n', []),
    %% Allocate perf_event_attr (112 bytes, zeroed)
    format(S, '  %attr = alloca [112 x i8]~n', []),
    format(S, '  call ptr @memset(ptr %attr, i32 0, i64 112)~n', []),
    %% Set size field (offset 4) = 112
    format(S, '  %size_ptr = getelementptr i8, ptr %attr, i32 4~n', []),
    format(S, '  store i32 112, ptr %size_ptr~n', []),
    %% Set disabled=1, exclude_kernel=1, exclude_hv=1 (offset 40, bits 0,1,2 = 0x7)
    format(S, '  %flags_ptr = getelementptr i8, ptr %attr, i32 40~n', []),
    format(S, '  store i64 7, ptr %flags_ptr~n', []),
    format(S, '~n', []),
    %% Open each counter via syscall 298 (perf_event_open)
    findall(counter(Name, Type, Config, FdGlobal), pmu_counter(Name, Type, Config, FdGlobal), Counters),
    emit_pmu_open_counters(S, Counters, 0),
    format(S, '~n', []),
    %% Enable all counters (ioctl fd, PERF_EVENT_IOC_ENABLE=0x2400, 0)
    emit_pmu_enable_all(S, Counters),
    format(S, '  store i32 1, ptr @pmu_started~n', []),
    format(S, '  ret i32 1~n', []),
    format(S, '}~n~n', []).

emit_pmu_open_counters(_, [], _).
emit_pmu_open_counters(S, [counter(_Name, Type, Config, FdGlobal)|Rest], Idx) :-
    format(atom(TypeLabel), 'type~w', [Idx]),
    format(atom(CfgLabel), 'cfg~w', [Idx]),
    format(atom(FdLabel), 'fd~w', [Idx]),
    %% Set type (offset 0)
    format(S, '  ; counter ~w~n', [_Name]),
    format(S, '  %~w_p = getelementptr i8, ptr %attr, i32 0~n', [TypeLabel]),
    format(S, '  store i32 ~w, ptr %~w_p~n', [Type, TypeLabel]),
    %% Set config (offset 8)
    format(S, '  %~w_p = getelementptr i8, ptr %attr, i32 8~n', [CfgLabel]),
    format(S, '  store i64 ~w, ptr %~w_p~n', [Config, CfgLabel]),
    %% syscall 298 = perf_event_open(attr, pid=0, cpu=-1, group=-1, flags=0)
    format(S, '  %~w_64 = call i64 (i64, ...) @syscall(i64 298, ptr %attr, i32 0, i32 -1, i32 -1, i64 0)~n', [FdLabel]),
    format(S, '  %~w = trunc i64 %~w_64 to i32~n', [FdLabel, FdLabel]),
    format(S, '  store i32 %~w, ptr @~w~n', [FdLabel, FdGlobal]),
    Idx1 is Idx + 1,
    emit_pmu_open_counters(S, Rest, Idx1).

emit_pmu_enable_all(_, []).
emit_pmu_enable_all(S, [counter(_, _, _, FdGlobal)|Rest]) :-
    format(atom(FdLoad), 'en_~w', [FdGlobal]),
    format(S, '  %~w = load i32, ptr @~w~n', [FdLoad, FdGlobal]),
    %% PERF_EVENT_IOC_RESET = 0x2403, PERF_EVENT_IOC_ENABLE = 0x2400
    format(S, '  call i32 (i32, i64, ...) @ioctl(i32 %~w, i64 9219, i32 0)~n', [FdLoad]),  % 0x2403 = reset
    format(S, '  call i32 (i32, i64, ...) @ioctl(i32 %~w, i64 9216, i32 0)~n', [FdLoad]),  % 0x2400 = enable
    emit_pmu_enable_all(S, Rest).

%% cpu_pmu_stop/0 — disable and close all counters
emit_pmu_stop(S) :-
    format(S, '; --- cpu_pmu_stop/0: disable + close PMU counters ---~n', []),
    format(S, 'define i32 @pl_pmu_stop(i64 %t0, i32 %arity, ptr %control) {~n', []),
    format(S, 'entry:~n', []),
    findall(FdGlobal, pmu_counter(_, _, _, FdGlobal), Fds),
    emit_pmu_close_all(S, Fds),
    format(S, '  store i32 0, ptr @pmu_started~n', []),
    format(S, '  ret i32 1~n', []),
    format(S, '}~n~n', []).

emit_pmu_close_all(_, []).
emit_pmu_close_all(S, [FdGlobal|Rest]) :-
    format(atom(FdLoad), 'cl_~w', [FdGlobal]),
    format(S, '  %~w = load i32, ptr @~w~n', [FdLoad, FdGlobal]),
    format(S, '  call i32 (i32, i64, ...) @ioctl(i32 %~w, i64 9217, i32 0)~n', [FdLoad]),  % 0x2401 = disable
    format(S, '  call i32 @close(i32 %~w)~n', [FdLoad]),
    emit_pmu_close_all(S, Rest).

%% cpu_pmu_read(-List) — read all counters, return as Name-Value pairs
emit_pmu_read(S) :-
    format(S, '; --- cpu_pmu_read(List): read all PMU counters ---~n', []),
    format(S, 'define i32 @pl_pmu_read(i64 %t0, i32 %arity, ptr %control) {~n', []),
    format(S, 'entry:~n', []),
    format(S, '  %list = call i64 @PL_copy_term_ref(i64 %t0)~n', []),
    format(S, '  %head = call i64 @PL_new_term_ref()~n', []),
    format(S, '  %dash_atom = call i64 @PL_new_atom(ptr @str_dash)~n', []),
    format(S, '  %dash_fn = call i64 @PL_new_functor(i64 %dash_atom, i32 2)~n', []),
    format(S, '  %val_buf = alloca i64~n', []),
    format(S, '~n', []),
    findall(counter(Name, _, _, FdGlobal), pmu_counter(Name, _, _, FdGlobal), Counters),
    emit_pmu_read_counters(S, Counters, 0),
    format(S, '  %ok_nil = call i32 @PL_unify_nil(i64 %list)~n', []),
    format(S, '  ret i32 %ok_nil~n', []),
    format(S, '}~n~n', []).

emit_pmu_read_counters(_, [], _).
emit_pmu_read_counters(S, [counter(Name, _, _, FdGlobal)|Rest], Idx) :-
    format(atom(FdLoad), 'rfd~w', [Idx]),
    format(atom(KeyRef), 'rkey~w', [Idx]),
    format(atom(ValRef), 'rval~w', [Idx]),
    format(atom(PairRef), 'rpair~w', [Idx]),
    format(atom(StrGlobal), 'str_pmu_~w', [Name]),
    format(S, '  ; read ~w~n', [Name]),
    format(S, '  %~w = load i32, ptr @~w~n', [FdLoad, FdGlobal]),
    format(S, '  call i64 @read(i32 %~w, ptr %val_buf, i64 8)~n', [FdLoad]),
    format(S, '  %~w_raw = load i64, ptr %val_buf~n', [ValRef]),
    format(S, '  %~w = call i64 @PL_new_term_ref()~n', [KeyRef]),
    format(S, '  %~w = call i64 @PL_new_term_ref()~n', [ValRef]),
    format(S, '  %~w = call i64 @PL_new_term_ref()~n', [PairRef]),
    format(S, '  call i32 @PL_put_atom_chars(i64 %~w, ptr @~w)~n', [KeyRef, StrGlobal]),
    format(S, '  call i32 @PL_unify_integer(i64 %~w, i64 %~w_raw)~n', [ValRef, ValRef]),
    format(S, '  call i32 @PL_cons_functor(i64 %~w, i64 %dash_fn, i64 %~w, i64 %~w)~n', [PairRef, KeyRef, ValRef]),
    format(S, '  call i32 @PL_unify_list(i64 %list, i64 %head, i64 %list)~n', []),
    format(S, '  call i32 @PL_unify(i64 %head, i64 %~w)~n', [PairRef]),
    format(S, '~n', []),
    Idx1 is Idx + 1,
    emit_pmu_read_counters(S, Rest, Idx1).

%% Unified install for NVML + CUPTI + CPU PMU
emit_full_install(S) :-
    format(S, '; --- unified install (NVML + CUPTI + CPU PMU) ---~n', []),
    format(S, 'define void @install() {~n', []),
    %% NVML predicates
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_temp, i32 1, ptr @pl_gpu_temperature, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_power, i32 1, ptr @pl_gpu_power, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_clock, i32 2, ptr @pl_gpu_clock, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_memory, i32 3, ptr @pl_gpu_memory, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_util, i32 2, ptr @pl_gpu_utilization, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_pcie, i32 2, ptr @pl_gpu_pcie, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_name, i32 1, ptr @pl_gpu_name, i32 0)~n', []),
    %% CUPTI predicates
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_cupti_start, i32 0, ptr @pl_cupti_start, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_cupti_stop, i32 0, ptr @pl_cupti_stop, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_cupti_flush, i32 0, ptr @pl_cupti_flush, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_cupti_stalls, i32 1, ptr @pl_cupti_stall_report, i32 0)~n', []),
    %% CPU PMU predicates
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_pmu_start, i32 0, ptr @pl_pmu_start, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_pmu_stop, i32 0, ptr @pl_pmu_stop, i32 0)~n', []),
    format(S, '  call i32 @PL_register_foreign(ptr @str_pred_pmu_read, i32 1, ptr @pl_pmu_read, i32 0)~n', []),
    format(S, '  ret void~n', []),
    format(S, '}~n', []).
