%% swiglu_strict_emitter.pl — STRICT SwiGLU matching ggml's poly-exp at 0 ULP.
%%
%% CRITICAL: ggml uses TWO exp implementations:
%%   Vector path (4 floats, XMM): polynomial exp (degree-5 minimax)
%%   Scalar tail (n%4 elements): libm expf
%%   Must reproduce BOTH at the SAME boundary for strict 0 ULP.
%%
%% Polynomial coefficients lifted from ggml_vec_silu_f32 @ 0x68a40.
%% Evaluation order traced from disassembly.
%%
%% Author: mavchin (2026-06-03)

:- module(swiglu_strict_emitter, [emit_swiglu_strict/1]).

emit_swiglu_strict(OutFile) :-
    open(OutFile, write, S),
    format(S, '; STRICT SwiGLU: matches ggml_vec_silu_f32 poly-exp at 0 ULP~n', []),
    format(S, '; Vector path: degree-5 minimax exp (4 floats/iter, XMM)~n', []),
    format(S, '; Scalar tail: libm expf (n%4 elements)~n', []),
    format(S, '; Generated by swiglu_strict_emitter.pl~n~n', []),
    format(S, 'declare float @expf(float)~n~n', []),
    emit_vector_silu_exp(S),
    emit_main_function(S),
    close(S),
    format("Emitted strict SwiGLU to ~w~n", [OutFile]).

%% ============================================================
%% Vector exp: degree-5 minimax polynomial, 4 floats at a time
%% Matches ggml's eval order from 0x68ad0-0x68bd0
%% ============================================================

emit_vector_silu_exp(S) :-
    format(S, '; Vector silu: 4 floats via poly-exp (XMM, matches ggml 0x68ad0)~n', []),
    format(S, 'define void @silu_vec4(ptr %gate_ptr, ptr %up_ptr, ptr %out_ptr) #0 {~n', []),
    format(S, 'entry:~n', []),
    %% Load 4 gate values and 4 up values
    format(S, '  %gv = load <4 x float>, ptr %gate_ptr, align 4~n', []),
    format(S, '  %uv = load <4 x float>, ptr %up_ptr, align 4~n', []),
    format(S, '~n', []),
    %% Constants (from ggml disassembly, f32 widened to f64 hex)
    format(S, '  ; Constants from ggml_vec_silu_f32 @ 0x68a40~n', []),
    %% Splat constants
    emit_splat4(S, c_log2e,    '0x3FF7154760000000'),  % 1.44269502
    emit_splat4(S, c_ln2_hi,   '0x3FE62E4000000000'),  % 0.693145752
    emit_splat4(S, c_ln2_lo,   '0x3EB7F7D1C0000000'),  % 1.42860677e-06
    emit_splat4(S, c_magic,    '0x4168000000000000'),  % 12582912.0 (1.5*2^23)
    emit_splat4(S, c_c5,       '0x3F80E40200000000'),  % 0.00824739039
    emit_splat4(S, c_c4,       '0x3FA573E2E0000000'),  % 0.0418997668
    emit_splat4(S, c_c3,       '0x3FC555E660000000'),  % 0.166683957
    emit_splat4(S, c_c2,       '0x3FDFFFDB60000000'),  % 0.499991268
    emit_splat4(S, c_c1,       '0x3FEFFFFEC0000000'),  % 0.999999404
    emit_splat4(S, c_one,      '0x3FF0000000000000'),  % 1.0
    format(S, '~n', []),
    %% 1. neg = 0 - x
    format(S, '  ; Step 1: negate x~n', []),
    format(S, '  %zero = bitcast <4 x i32> zeroinitializer to <4 x float>~n', []),
    format(S, '  %neg = fsub <4 x float> %zero, %gv~n', []),
    %% 2. t = neg * log2(e)
    format(S, '  ; Step 2: t = neg * log2(e)~n', []),
    format(S, '  %t = fmul <4 x float> %neg, %c_log2e~n', []),
    %% 3. round: n = round(t) via magic number trick
    format(S, '  ; Step 3: round to integer via magic~n', []),
    format(S, '  %t_plus_magic = fadd <4 x float> %t, %c_magic~n', []),
    format(S, '  %t_minus_magic = fsub <4 x float> %t_plus_magic, %c_magic~n', []),
    format(S, '  %n = bitcast <4 x float> %t_minus_magic to <4 x float>~n', []),
    %% Build 2^n via integer exponent
    format(S, '  ; Step 3b: build 2^n~n', []),
    format(S, '  %n_plus_magic_i = bitcast <4 x float> %t_plus_magic to <4 x i32>~n', []),
    format(S, '  %exp_bits = shl <4 x i32> %n_plus_magic_i, <i32 23, i32 23, i32 23, i32 23>~n', []),
    format(S, '  %two_n = bitcast <4 x i32> %exp_bits to <4 x float>~n', []),
    %% 4. range reduce: r = neg - n*ln2_hi - n*ln2_lo
    format(S, '  ; Step 4: range reduction (2-part ln2)~n', []),
    format(S, '  %n_ln2_hi = fmul <4 x float> %n, %c_ln2_hi~n', []),
    format(S, '  %r1 = fsub <4 x float> %neg, %n_ln2_hi~n', []),
    format(S, '  %n_ln2_lo = fmul <4 x float> %n, %c_ln2_lo~n', []),
    format(S, '  %r = fsub <4 x float> %r1, %n_ln2_lo~n', []),
    %% 5. Horner polynomial: ((((c5*r+c4)*r+c3)*r+c2)*r+c1)*r+1.0
    format(S, '  ; Step 5: Horner polynomial (degree 5)~n', []),
    format(S, '  %p0 = fmul <4 x float> %c_c5, %r~n', []),
    format(S, '  %p1 = fadd <4 x float> %p0, %c_c4~n', []),
    format(S, '  %p2 = fmul <4 x float> %p1, %r~n', []),
    format(S, '  %p3 = fadd <4 x float> %p2, %c_c3~n', []),
    format(S, '  %p4 = fmul <4 x float> %p3, %r~n', []),
    format(S, '  %p5 = fadd <4 x float> %p4, %c_c2~n', []),
    format(S, '  %p6 = fmul <4 x float> %p5, %r~n', []),
    format(S, '  %p7 = fadd <4 x float> %p6, %c_c1~n', []),
    format(S, '  %p8 = fmul <4 x float> %p7, %r~n', []),
    format(S, '  %poly = fadd <4 x float> %p8, %c_one~n', []),
    %% 6. exp = poly * 2^n
    format(S, '  ; Step 6: exp(-x) = poly * 2^n~n', []),
    format(S, '  %exp_val = fmul <4 x float> %poly, %two_n~n', []),
    %% 7. denom = exp + 1.0
    format(S, '  ; Step 7: denom = 1 + exp(-x)~n', []),
    format(S, '  %denom = fadd <4 x float> %exp_val, %c_one~n', []),
    %% 8. silu = x / denom (DIVIDE form)
    format(S, '  ; Step 8: silu = x / (1+exp(-x)) [DIVIDE form]~n', []),
    format(S, '  %silu = fdiv <4 x float> %gv, %denom~n', []),
    %% 9. result = silu * up
    format(S, '  ; Step 9: fused multiply by up~n', []),
    format(S, '  %result = fmul <4 x float> %silu, %uv~n', []),
    format(S, '~n', []),
    format(S, '  store <4 x float> %result, ptr %out_ptr, align 4~n', []),
    format(S, '  ret void~n', []),
    format(S, '}~n~n', []),
    format(S, 'attributes #0 = { "target-features"="+sse,+sse2,+avx" }~n~n', []).

emit_splat4(S, Name, HexVal) :-
    format(S, '  %~w_s = insertelement <4 x float> undef, float ~w, i32 0~n', [Name, HexVal]),
    format(S, '  %~w = shufflevector <4 x float> %~w_s, <4 x float> undef, <4 x i32> zeroinitializer~n', [Name, Name]).

%% ============================================================
%% Main function: vector loop + scalar tail (matching ggml's split)
%% ============================================================

emit_main_function(S) :-
    format(S, '; Main entry: vector loop (4 at a time) + scalar tail (libm expf)~n', []),
    format(S, 'define void @bpd_swiglu_strict_cpu(ptr %gate, ptr %up, ptr %out, i32 %n) {~n', []),
    format(S, 'entry:~n', []),
    format(S, '  br label %vec_check~n~n', []),
    %% Vector loop (4 elements at a time)
    format(S, 'vec_check:~n', []),
    format(S, '  %vi = phi i32 [ 0, %entry ], [ %vi8, %vec_body ]~n', []),
    format(S, '  %vrem = sub i32 %n, %vi~n', []),
    format(S, '  %vcan = icmp sge i32 %vrem, 4~n', []),
    format(S, '  br i1 %vcan, label %vec_body, label %scalar_check~n~n', []),
    format(S, 'vec_body:~n', []),
    format(S, '  %vgp = getelementptr float, ptr %gate, i32 %vi~n', []),
    format(S, '  %vup = getelementptr float, ptr %up, i32 %vi~n', []),
    format(S, '  %vop = getelementptr float, ptr %out, i32 %vi~n', []),
    format(S, '  call void @silu_vec4(ptr %vgp, ptr %vup, ptr %vop)~n', []),
    format(S, '  %vi8 = add i32 %vi, 4~n', []),
    format(S, '  br label %vec_check~n~n', []),
    %% Scalar tail (libm expf — matches ggml's scalar tail)
    format(S, 'scalar_check:~n', []),
    format(S, '  %si = phi i32 [ %vi, %vec_check ], [ %si_next, %scalar_body ]~n', []),
    format(S, '  %sdone = icmp sge i32 %si, %n~n', []),
    format(S, '  br i1 %sdone, label %done, label %scalar_body~n~n', []),
    format(S, 'scalar_body:~n', []),
    format(S, '  %sgp = getelementptr float, ptr %gate, i32 %si~n', []),
    format(S, '  %sg = load float, ptr %sgp~n', []),
    format(S, '  %sup_p = getelementptr float, ptr %up, i32 %si~n', []),
    format(S, '  %su = load float, ptr %sup_p~n', []),
    %% Scalar silu: x / (1 + expf(-x)) using LIBM expf
    format(S, '  %sneg = fneg float %sg~n', []),
    format(S, '  %sexp = call float @expf(float %sneg)~n', []),
    format(S, '  %sdenom = fadd float 1.0, %sexp~n', []),
    format(S, '  %ssilu = fdiv float %sg, %sdenom~n', []),
    format(S, '  %sresult = fmul float %ssilu, %su~n', []),
    format(S, '  %sop = getelementptr float, ptr %out, i32 %si~n', []),
    format(S, '  store float %sresult, ptr %sop~n', []),
    format(S, '  %si_next = add i32 %si, 1~n', []),
    format(S, '  br label %scalar_check~n~n', []),
    format(S, 'done:~n', []),
    format(S, '  ret void~n', []),
    format(S, '}~n', []).
