#!/usr/bin/env python3
"""prolog_to_c.py — Generate C code from Prolog graph facts targeting ggml.

Reads model_graph.pl (auto-generated by pytorch_to_prolog.py) and emits
a standalone C file that builds and runs the compute graph using ggml.

Usage:
    python prolog_to_c.py model_graph.pl output.c

The generated C code:
  - Includes ggml.h
  - Builds compute graph with ggml_new_tensor + ggml_* ops
  - Loads weights from a .gguf file (or raw binary)
  - Runs forward pass via ggml_graph_compute
  - No Python dependency at all
"""
import sys, re
from collections import defaultdict, OrderedDict


# ggml dispatch table (mirrors ggml_dispatch_table.pl)
GGML_DISPATCH = {
    # Unary activations: ggml_*(ctx, a)
    'relu':        ('ggml_relu',        ['ctx', 'a']),
    'leaky_relu':  ('ggml_leaky_relu',  ['ctx', 'a']),
    'silu':        ('ggml_silu',        ['ctx', 'a']),
    'gelu':        ('ggml_gelu',        ['ctx', 'a']),
    'sigmoid':     ('ggml_sigmoid',     ['ctx', 'a']),
    'tanh':        ('ggml_tanh',        ['ctx', 'a']),
    'elu':         ('ggml_elu',         ['ctx', 'a']),
    'hardswish':   ('ggml_hardswish',   ['ctx', 'a']),
    'hardsigmoid': ('ggml_hardsigmoid', ['ctx', 'a']),
    # Binary
    'add':         ('ggml_add',         ['ctx', 'a', 'b']),
    'sub':         ('ggml_sub',         ['ctx', 'a', 'b']),
    'mul':         ('ggml_mul',         ['ctx', 'a', 'b']),
    'div':         ('ggml_div',         ['ctx', 'a', 'b']),
    # Math
    'abs':         ('ggml_abs',         ['ctx', 'a']),
    'neg':         ('ggml_neg',         ['ctx', 'a']),
    'sqrt':        ('ggml_sqrt',        ['ctx', 'a']),
    # Conv2d
    'conv2d':      ('ggml_conv_2d',     ['ctx', 'kernel', 'input', 's0', 's1', 'p0', 'p1', 'd0', 'd1']),
    # Norm
    'batchnorm':   ('ggml_norm',        ['ctx', 'a', 'eps']),
    'layernorm':   ('ggml_norm',        ['ctx', 'a', 'eps']),
    'rmsnorm':     ('ggml_rms_norm',    ['ctx', 'a', 'eps']),
    # Pool
    'maxpool':     ('ggml_pool_2d',     ['ctx', 'a', 'GGML_OP_POOL_MAX', 'k0', 'k1', 's0', 's1', 'p0', 'p1']),
    'avgpool':     ('ggml_pool_2d',     ['ctx', 'a', 'GGML_OP_POOL_AVG', 'k0', 'k1', 's0', 's1', 'p0', 'p1']),
    # Structural
    'concat':      ('ggml_concat',      ['ctx', 'a', 'b', 'dim']),
    'upsample':    ('ggml_upscale',     ['ctx', 'a', 'scale_factor']),
    # Reduction
    'sum_reduce':  ('ggml_sum',         ['ctx', 'a']),
    'mean_reduce': ('ggml_mean',        ['ctx', 'a']),
    'argmax':      ('ggml_argmax',      ['ctx', 'a']),
    # Softmax
    'softmax':     ('ggml_soft_max',    ['ctx', 'a']),
    # Matmul
    'matmul':      ('ggml_mul_mat',     ['ctx', 'a', 'b']),
    'linear':      ('ggml_mul_mat',     ['ctx', 'a', 'b']),
}


def parse_prolog(filename):
    """Parse Prolog facts into Python dicts."""
    ops = OrderedDict()
    outputs = {}
    inputs = {}
    attrs = defaultdict(dict)
    
    with open(filename) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('%') or line.startswith(':-'):
                continue
            
            m = re.match(r"op_kind\((\w+),\s*(\w+)\)\.", line)
            if m: ops[m.group(1)] = m.group(2); continue
            
            m = re.match(r"op_output\((\w+),\s*(\w+)\)\.", line)
            if m: outputs[m.group(1)] = m.group(2); continue
            
            m = re.match(r"op_inputs\((\w+),\s*\[([^\]]*)\]\)\.", line)
            if m:
                inputs[m.group(1)] = [x.strip() for x in m.group(2).split(',') if x.strip()]
                continue
            
            m = re.match(r"op_attr\((\w+),\s*(\w+),\s*(.+)\)\.", line)
            if m:
                val = m.group(3)
                try: val = int(val)
                except:
                    try: val = float(val)
                    except: val = val.strip("'\"")
                attrs[m.group(1)][m.group(2)] = val
    
    return ops, outputs, inputs, attrs


def topo_sort(ops, inputs, outputs):
    """Topological sort of ops based on data flow edges."""
    # Build output_tensor → producer_op mapping
    tensor_producer = {}
    for op_name, out_tensor in outputs.items():
        tensor_producer[out_tensor] = op_name
    
    # Build dependency graph
    deps = defaultdict(set)
    for op_name, inp_tensors in inputs.items():
        for t in inp_tensors:
            if t in tensor_producer:
                deps[op_name].add(tensor_producer[t])
    
    # Kahn's algorithm
    in_degree = defaultdict(int)
    for op in ops: in_degree[op] = 0
    for op, dep_set in deps.items():
        in_degree[op] = len(dep_set)
    
    queue = [op for op in ops if in_degree[op] == 0]
    result = []
    while queue:
        op = queue.pop(0)
        result.append(op)
        for other_op in ops:
            if op in deps.get(other_op, set()):
                in_degree[other_op] -= 1
                if in_degree[other_op] == 0:
                    queue.append(other_op)
    
    # Add any ops not reached (disconnected)
    for op in ops:
        if op not in result:
            result.append(op)
    
    return result


def emit_c(ops, outputs, inputs, attrs, output_file):
    """Generate C code targeting ggml."""
    
    sorted_ops = topo_sort(ops, inputs, outputs)
    
    # Collect weight tensor names (conv weights, bn params)
    weight_ops = {name for name, kind in ops.items() 
                  if kind in ('conv2d', 'batchnorm', 'linear')}
    
    c = []
    c.append('/* Auto-generated by prolog_to_c.py from Prolog graph facts.')
    c.append(' * Part of BPD Substrate: https://github.com/heath-hunnicutt-ruach-tov/bpd-substrate')
    c.append(' * No Python dependency. Calls ggml for compute dispatch.')
    c.append(' */')
    c.append('#include "ggml.h"')
    c.append('#include <stdio.h>')
    c.append('#include <stdlib.h>')
    c.append('#include <string.h>')
    c.append('')
    c.append('/* Model structure — holds weight tensors */')
    c.append('struct model {')
    c.append('    struct ggml_context * ctx_w;  /* weight context */')
    
    # Emit weight tensor fields
    for name in sorted_ops:
        kind = ops[name]
        a = attrs.get(name, {})
        if kind == 'conv2d':
            ic = a.get('in_channels', 0)
            oc = a.get('out_channels', 0)
            ks = a.get('kernel_size', 1)
            c.append(f'    struct ggml_tensor * {name}_weight;  /* [{oc},{ic},{ks},{ks}] */')
        elif kind == 'batchnorm':
            nf = a.get('num_features', a.get('out_channels', 0))
            c.append(f'    struct ggml_tensor * {name}_weight;  /* [{nf}] gamma */')
            c.append(f'    struct ggml_tensor * {name}_bias;    /* [{nf}] beta */')
            c.append(f'    struct ggml_tensor * {name}_mean;    /* [{nf}] running_mean */')
            c.append(f'    struct ggml_tensor * {name}_var;     /* [{nf}] running_var */')
    
    c.append('};')
    c.append('')
    
    # Model init — allocate weight tensors
    c.append('void model_init(struct model * m) {')
    c.append('    struct ggml_init_params params = {')
    c.append('        .mem_size   = 256 * 1024 * 1024,  /* 256 MB for weights */')
    c.append('        .mem_buffer = NULL,')
    c.append('        .no_alloc   = false,')
    c.append('    };')
    c.append('    m->ctx_w = ggml_init(params);')
    c.append('')
    
    for name in sorted_ops:
        kind = ops[name]
        a = attrs.get(name, {})
        if kind == 'conv2d':
            ic = a.get('in_channels', 3)
            oc = a.get('out_channels', 16)
            ks = a.get('kernel_size', 3)
            c.append(f'    m->{name}_weight = ggml_new_tensor_4d(m->ctx_w, GGML_TYPE_F32, {ks}, {ks}, {ic}, {oc});')
            c.append(f'    ggml_set_name(m->{name}_weight, "{name}.weight");')
        elif kind == 'batchnorm':
            nf = a.get('num_features', 16)
            c.append(f'    m->{name}_weight = ggml_new_tensor_1d(m->ctx_w, GGML_TYPE_F32, {nf});')
            c.append(f'    m->{name}_bias   = ggml_new_tensor_1d(m->ctx_w, GGML_TYPE_F32, {nf});')
            c.append(f'    m->{name}_mean   = ggml_new_tensor_1d(m->ctx_w, GGML_TYPE_F32, {nf});')
            c.append(f'    m->{name}_var    = ggml_new_tensor_1d(m->ctx_w, GGML_TYPE_F32, {nf});')
            c.append(f'    ggml_set_name(m->{name}_weight, "{name}.weight");')
    
    c.append('}')
    c.append('')
    
    # Forward pass — build compute graph
    c.append('struct ggml_tensor * model_forward(')
    c.append('        struct model * m,')
    c.append('        struct ggml_context * ctx,')
    c.append('        struct ggml_tensor * input) {')
    c.append('')
    c.append('    struct ggml_tensor * cur = input;')
    c.append('')
    
    # Track tensor names for data flow
    tensor_map = {'input': 'input'}
    
    for name in sorted_ops:
        kind = ops[name]
        a = attrs.get(name, {})
        inp = inputs.get(name, [])
        out = outputs.get(name, name + '_out')
        
        # Determine input tensor variable name
        if inp:
            inp_var = tensor_map.get(inp[0], 'cur')
        else:
            inp_var = 'cur'
        
        if kind in GGML_DISPATCH:
            func_name, arg_pattern = GGML_DISPATCH[kind]
            
            if kind == 'conv2d':
                s = a.get('stride', 1)
                p = a.get('padding', 0)
                c.append(f'    /* {name}: Conv2d */')
                c.append(f'    cur = {func_name}(ctx, m->{name}_weight, {inp_var}, {s}, {s}, {p}, {p}, 1, 1);')
                c.append(f'    ggml_set_name(cur, "{out}");')
                
            elif kind == 'batchnorm':
                eps = a.get('eps', 0.001)
                c.append(f'    /* {name}: BatchNorm2d — norm + scale + shift */')
                c.append(f'    cur = ggml_norm(ctx, {inp_var}, {eps}f);')
                c.append(f'    cur = ggml_mul(ctx, cur, m->{name}_weight);')
                c.append(f'    cur = ggml_add(ctx, cur, m->{name}_bias);')
                c.append(f'    ggml_set_name(cur, "{out}");')
                
            elif kind in ('silu', 'relu', 'gelu', 'sigmoid', 'tanh', 'elu', 'hardswish', 'hardsigmoid'):
                c.append(f'    cur = {func_name}(ctx, {inp_var});  /* {name} */')
                
            elif kind == 'add':
                if len(inp) >= 2:
                    inp2_var = tensor_map.get(inp[1], 'cur')
                    c.append(f'    cur = ggml_add(ctx, {inp_var}, {inp2_var});  /* {name}: residual add */')
                
            elif kind == 'maxpool':
                ks = a.get('kernel_size', 5)
                st = a.get('stride', 1)
                pd = a.get('padding', ks // 2)
                c.append(f'    cur = ggml_pool_2d(ctx, {inp_var}, GGML_OP_POOL_MAX, {ks}, {ks}, {st}, {st}, {pd}, {pd});  /* {name} */')
                
            elif kind == 'concat':
                if len(inp) >= 2:
                    inp2_var = tensor_map.get(inp[1], 'cur')
                    c.append(f'    cur = ggml_concat(ctx, {inp_var}, {inp2_var}, 2);  /* {name}: concat dim=1 */')
                    # Handle 3+ inputs
                    for extra in inp[2:]:
                        extra_var = tensor_map.get(extra, 'cur')
                        c.append(f'    cur = ggml_concat(ctx, cur, {extra_var}, 2);')
                        
            elif kind == 'upsample':
                sf = a.get('scale_factor', 2)
                c.append(f'    cur = ggml_upscale(ctx, {inp_var}, {sf});  /* {name} */')
                
            elif kind == 'softmax':
                c.append(f'    cur = ggml_soft_max(ctx, {inp_var});  /* {name} */')
                
            else:
                c.append(f'    cur = {func_name}(ctx, {inp_var});  /* {name}: {kind} */')
        else:
            c.append(f'    /* {name}: {kind} — NO ggml equivalent, needs BPD fallback */')
        
        # Register output tensor
        tensor_map[out] = 'cur'
        # Also register by name for skip connections
        tensor_map[name] = 'cur'
        
        c.append('')
    
    c.append('    return cur;')
    c.append('}')
    c.append('')
    
    # Main
    c.append('int main(int argc, char ** argv) {')
    c.append('    struct model m;')
    c.append('    model_init(&m);')
    c.append('')
    c.append('    /* Compute context */')
    c.append('    struct ggml_init_params params = {')
    c.append('        .mem_size   = 512 * 1024 * 1024,')
    c.append('        .mem_buffer = NULL,')
    c.append('        .no_alloc   = false,')
    c.append('    };')
    c.append('    struct ggml_context * ctx = ggml_init(params);')
    c.append('')
    c.append('    /* Input tensor: [1, 3, 640, 640] */')
    c.append('    struct ggml_tensor * input = ggml_new_tensor_4d(ctx, GGML_TYPE_F32, 640, 640, 3, 1);')
    c.append('    ggml_set_name(input, "input");')
    c.append('')
    c.append('    /* Build forward graph */')
    c.append('    struct ggml_tensor * output = model_forward(&m, ctx, input);')
    c.append('')
    c.append('    /* TODO: Load weights from .gguf file */')
    c.append('    /* TODO: Fill input tensor with image data */')
    c.append('    /* TODO: ggml_graph_compute to execute */')
    c.append('')
    c.append('    printf("Model built: %d ops\\n", ggml_graph_n_nodes(ggml_new_graph(ctx)));')
    c.append('')
    c.append('    ggml_free(ctx);')
    c.append('    ggml_free(m.ctx_w);')
    c.append('    return 0;')
    c.append('}')
    
    with open(output_file, 'w') as f:
        f.write('\n'.join(c))
    
    n_ops = len(ops)
    n_ggml = sum(1 for k in ops.values() if k in GGML_DISPATCH)
    n_fallback = n_ops - n_ggml
    print(f"Generated {output_file} ({len(c)} lines)")
    print(f"  {n_ops} ops total, {n_ggml} via ggml, {n_fallback} need BPD fallback")


if __name__ == '__main__':
    pl_file = sys.argv[1] if len(sys.argv) > 1 else '/tmp/auto_graph.pl'
    c_file = sys.argv[2] if len(sys.argv) > 2 else '/tmp/generated_model.c'
    
    ops, outputs, inputs, attrs = parse_prolog(pl_file)
    emit_c(ops, outputs, inputs, attrs, c_file)
