#!/usr/bin/env python3
"""prolog_to_pytorch.py — Generate PyTorch nn.Module from Prolog graph facts.

The reverse of pytorch_to_prolog.py. Reads a Prolog model_graph.pl
and emits a standalone Python file defining the model as nn.Module subclasses.

Usage:
    python prolog_to_pytorch.py model_graph.pl output_model.py

The generated Python file has ZERO dependencies beyond torch.
No cv2, no yolov5, no external model definitions.
"""
import sys, re
from collections import defaultdict


def parse_prolog(filename):
    """Parse Prolog facts into Python dicts."""
    ops = {}      # name → kind
    outputs = {}  # name → output_tensor
    inputs = {}   # name → [input_tensors]
    attrs = defaultdict(dict)  # name → {key: value}
    
    with open(filename) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('%') or line.startswith(':-'):
                continue
            
            # op_kind(name, kind).
            m = re.match(r"op_kind\((\w+),\s*(\w+)\)\.", line)
            if m:
                ops[m.group(1)] = m.group(2)
                continue
            
            # op_output(name, output).
            m = re.match(r"op_output\((\w+),\s*(\w+)\)\.", line)
            if m:
                outputs[m.group(1)] = m.group(2)
                continue
            
            # op_inputs(name, [inputs]).
            m = re.match(r"op_inputs\((\w+),\s*\[([^\]]*)\]\)\.", line)
            if m:
                inp_list = [x.strip() for x in m.group(2).split(',') if x.strip()]
                inputs[m.group(1)] = inp_list
                continue
            
            # op_attr(name, key, value).
            m = re.match(r"op_attr\((\w+),\s*(\w+),\s*(.+)\)\.", line)
            if m:
                name, key, val = m.group(1), m.group(2), m.group(3)
                # Parse value
                try:
                    val = int(val)
                except ValueError:
                    try:
                        val = float(val)
                    except ValueError:
                        val = val.strip("'\"")
                attrs[name][key] = val
    
    return ops, outputs, inputs, attrs


def find_cbs_groups(ops, inputs):
    """Find Conv→BN→SiLU chains (CBS groups)."""
    groups = []
    for name, kind in ops.items():
        if kind == 'conv2d':
            out = name + '_out'
            # Find BN that reads this conv's output
            for bn_name, bn_ins in inputs.items():
                if ops.get(bn_name) == 'batchnorm' and out in bn_ins:
                    bn_out = bn_name + '_out'
                    # Find activation that reads BN output
                    for act_name, act_ins in inputs.items():
                        if ops.get(act_name) in ('silu', 'relu', 'leaky_relu', 'gelu') and bn_out in act_ins:
                            groups.append({
                                'conv': name, 'bn': bn_name, 'act': act_name,
                                'act_type': ops[act_name]
                            })
    return groups


def generate_pytorch(ops, outputs, inputs, attrs, output_file):
    """Generate a standalone PyTorch model file from Prolog facts."""
    
    # Find the model structure
    cbs_groups = find_cbs_groups(ops, inputs)
    
    # Build a topological ordering
    # Find all unique op names sorted by their position in the graph
    all_names = sorted(ops.keys())
    
    code = []
    code.append('"""Auto-generated PyTorch model from Prolog graph facts.')
    code.append('Generated by prolog_to_pytorch.py — the reverse of pytorch_to_prolog.py.')
    code.append('No external dependencies beyond torch.')
    code.append('"""')
    code.append('import torch')
    code.append('import torch.nn as nn')
    code.append('')
    code.append('')
    code.append('def autopad(k, p=None, d=1):')
    code.append('    """Compute padding for same-size output."""')
    code.append('    if d > 1: k = d * (k - 1) + 1')
    code.append('    if p is None: p = k // 2')
    code.append('    return p')
    code.append('')
    code.append('')
    code.append('class Conv(nn.Module):')
    code.append('    """Conv2d + BatchNorm2d + Activation (CBS block)."""')
    code.append('')
    code.append('    def __init__(self, c1, c2, k=1, s=1, p=None, g=1, act=True):')
    code.append('        super().__init__()')
    code.append('        self.conv = nn.Conv2d(c1, c2, k, s, autopad(k, p), groups=g, bias=False)')
    code.append('        self.bn = nn.BatchNorm2d(c2, eps=0.001)')
    code.append('        self.act = nn.SiLU() if act is True else act if isinstance(act, nn.Module) else nn.Identity()')
    code.append('')
    code.append('    def forward(self, x):')
    code.append('        return self.act(self.bn(self.conv(x)))')
    code.append('')
    code.append('')
    code.append('class Bottleneck(nn.Module):')
    code.append('    """Bottleneck with optional residual shortcut."""')
    code.append('')
    code.append('    def __init__(self, c1, c2, shortcut=True, g=1, e=0.5):')
    code.append('        super().__init__()')
    code.append('        c_ = int(c2 * e)')
    code.append('        self.cv1 = Conv(c1, c_, 1, 1)')
    code.append('        self.cv2 = Conv(c_, c2, 3, 1, g=g)')
    code.append('        self.add = shortcut and c1 == c2')
    code.append('')
    code.append('    def forward(self, x):')
    code.append('        return x + self.cv2(self.cv1(x)) if self.add else self.cv2(self.cv1(x))')
    code.append('')
    code.append('')
    code.append('class C3(nn.Module):')
    code.append('    """CSP Bottleneck with 3 convolutions."""')
    code.append('')
    code.append('    def __init__(self, c1, c2, n=1, shortcut=True, g=1, e=0.5):')
    code.append('        super().__init__()')
    code.append('        c_ = int(c2 * e)')
    code.append('        self.cv1 = Conv(c1, c_, 1, 1)')
    code.append('        self.cv2 = Conv(c1, c_, 1, 1)')
    code.append('        self.cv3 = Conv(2 * c_, c2, 1)')
    code.append('        self.m = nn.Sequential(*(Bottleneck(c_, c_, shortcut, g, e=1.0) for _ in range(n)))')
    code.append('')
    code.append('    def forward(self, x):')
    code.append('        return self.cv3(torch.cat((self.m(self.cv1(x)), self.cv2(x)), 1))')
    code.append('')
    code.append('')
    code.append('class SPPF(nn.Module):')
    code.append('    """Spatial Pyramid Pooling - Fast."""')
    code.append('')
    code.append('    def __init__(self, c1, c2, k=5):')
    code.append('        super().__init__()')
    code.append('        c_ = c1 // 2')
    code.append('        self.cv1 = Conv(c1, c_, 1, 1)')
    code.append('        self.cv2 = Conv(c_ * 4, c2, 1, 1)')
    code.append('        self.m = nn.MaxPool2d(kernel_size=k, stride=1, padding=k // 2)')
    code.append('')
    code.append('    def forward(self, x):')
    code.append('        x = self.cv1(x)')
    code.append('        y1 = self.m(x); y2 = self.m(y1); y3 = self.m(y2)')
    code.append('        return self.cv2(torch.cat((x, y1, y2, y3), 1))')
    code.append('')
    code.append('')
    code.append('class Concat(nn.Module):')
    code.append('    """Concatenate tensors along dimension."""')
    code.append('')
    code.append('    def __init__(self, dimension=1):')
    code.append('        super().__init__()')
    code.append('        self.d = dimension')
    code.append('')
    code.append('    def forward(self, x):')
    code.append('        return torch.cat(x, self.d)')
    code.append('')
    
    # Now emit the specific model architecture from the Prolog facts
    # Extract layer parameters from attrs
    code.append('')
    code.append('class GeneratedModel(nn.Module):')
    code.append('    """Model auto-generated from Prolog graph facts."""')
    code.append('')
    code.append('    def __init__(self):')
    code.append('        super().__init__()')
    
    # Find top-level layers (model_0, model_1, ...)
    top_layers = []
    for name in sorted(ops.keys()):
        parts = name.split('_')
        if len(parts) == 2 and parts[0] == 'model' and parts[1].isdigit():
            kind = ops[name]
            layer_attrs = {}
            # Collect attrs for this layer and its children
            for aname, adict in attrs.items():
                if aname.startswith(name + '_') or aname == name:
                    for k, v in adict.items():
                        layer_attrs[f"{aname}.{k}"] = v
            top_layers.append((name, kind, layer_attrs))
    
    # Emit layer definitions
    for name, kind, la in top_layers:
        idx = name.split('_')[1]
        conv_key = f"{name}_conv"
        
        if kind == 'cbs':
            ic = attrs.get(conv_key, {}).get('in_channels', '?')
            oc = attrs.get(conv_key, {}).get('out_channels', '?')
            ks = attrs.get(conv_key, {}).get('kernel_size', 1)
            st = attrs.get(conv_key, {}).get('stride', 1)
            pd = attrs.get(conv_key, {}).get('padding', None)
            code.append(f'        self.layer{idx} = Conv({ic}, {oc}, {ks}, {st}, {pd})')
            
        elif kind == 'c3':
            cv1_key = f"{name}_cv1_conv"
            cv3_key = f"{name}_cv3_conv"
            ic = attrs.get(cv1_key, {}).get('in_channels', '?')
            oc = attrs.get(cv3_key, {}).get('out_channels', '?')
            # Count bottlenecks
            n_bot = sum(1 for n in ops if n.startswith(f"{name}_bot") and ops[n] == 'add')
            if n_bot == 0: n_bot = 1
            code.append(f'        self.layer{idx} = C3({ic}, {oc}, n={n_bot})')
            
        elif kind == 'sppf':
            cv1_key = f"{name}_cv1_conv"
            ic = attrs.get(cv1_key, {}).get('in_channels', '?')
            cv2_key = f"{name}_cv2_conv"
            oc = attrs.get(cv2_key, {}).get('out_channels', '?')
            code.append(f'        self.layer{idx} = SPPF({ic}, {oc})')
            
        elif kind == 'upsample':
            sf = attrs.get(name, {}).get('scale_factor', 2)
            code.append(f'        self.layer{idx} = nn.Upsample(scale_factor={sf}, mode="nearest")')
            
        elif kind == 'concat':
            code.append(f'        self.layer{idx} = Concat(dimension=1)')
            
        elif kind == 'detect':
            code.append(f'        # Detect head — needs anchor config')
            code.append(f'        self.layer{idx} = None  # TODO: Detect(...)')
        else:
            code.append(f'        # self.layer{idx} = {kind}  # TODO')
    
    # Emit forward method
    code.append('')
    code.append('    def forward(self, x):')
    code.append('        """Forward pass — auto-generated from Prolog data flow edges."""')
    code.append('        save = {}')
    
    for name, kind, _ in top_layers:
        idx = name.split('_')[1]
        # Check if this layer reads from a saved tensor (concat/skip)
        inp = inputs.get(name, [])
        code.append(f'        x = self.layer{idx}(x)  # {kind}')
        code.append(f'        save[{idx}] = x')
    
    code.append('        return x')
    code.append('')
    code.append('')
    code.append('def load_weights(model, checkpoint_path):')
    code.append('    """Load weights from original YOLOv5 checkpoint."""')
    code.append('    # The state_dict keys need remapping from model.N.* to layerN.*')
    code.append('    pass  # TODO: weight remapping')
    code.append('')
    code.append('')
    code.append('if __name__ == "__main__":')
    code.append('    model = GeneratedModel()')
    code.append('    print(model)')
    code.append('    x = torch.randn(1, 3, 640, 640)')
    code.append('    # y = model(x)  # uncomment when Detect is implemented')
    code.append('')
    
    with open(output_file, 'w') as f:
        f.write('\n'.join(code))
    
    print(f"Generated {output_file} ({len(code)} lines)")
    print(f"  {len(top_layers)} top-level layers")
    print(f"  Classes: Conv, Bottleneck, C3, SPPF, Concat")
    print(f"  Dependencies: torch only (no cv2, no yolov5)")


if __name__ == '__main__':
    pl_file = sys.argv[1] if len(sys.argv) > 1 else '/tmp/auto_graph.pl'
    py_file = sys.argv[2] if len(sys.argv) > 2 else '/tmp/generated_model.py'
    
    ops, outputs, inputs, attrs = parse_prolog(pl_file)
    generate_pytorch(ops, outputs, inputs, attrs, py_file)
